/* ============================================================
   ПАЧКА 4 · МОСТ К IELTS — то, что стоит между «база закрыта»
   и «можно готовиться к экзамену».

   Отбор не по учебнику, а по тому, что реально приносит баллы
   в Writing и Reading: сложные конструкции, которые поднимают
   Grammatical Range, академическая лексика вместо разговорной,
   язык описания графиков (Task 1) и язык аргумента (Task 2).

   Это ещё НЕ экзаменационные задания: одно предложение — один
   приём. Целые эссе и тексты на время — следующий этап, когда
   кирпичи держат форму (тот же принцип, что в курсе ielts).

   Метки: r4:true — пачка 4, lex:true — лексика,
   tag: wgram · wlex · task1 · task2 · reg2.
   ============================================================ */

export const IELTS_QUESTIONS = [

/* ============================================================
   ГРАММАТИКА ДЛЯ ПИСЬМА (tag:wgram)
   Экзаменатор смотрит на разнообразие конструкций. Тут не
   «правильно/неправильно вообще», а «звучит на 5 или на 7».
   ============================================================ */
{ g:'B1 · Конструкции', r4:true, tag:['wgram'], type:'choose',
  q:'If governments ___ more in public transport, cities ___ less polluted.',
  options:['invest / will be','invested / would be','had invested / would be'], answer:1,
  ru:'если бы государства больше вкладывали в транспорт, города были бы чище',
  why:'гипотеза о настоящем → второй тип: Past Simple + would. Рабочая лошадка эссе Task 2.' },
{ g:'B1 · Конструкции', r4:true, tag:['wgram'], type:'choose',
  q:'___ the funding been approved, the project would have started in May.',
  options:['If','Had','Would'], answer:1,
  ru:'если бы финансирование одобрили, проект стартовал бы в мае',
  why:'инверсия вместо if: Had + подлежащее + V3. Дороже выглядит, чем «If the funding had been approved».' },
{ g:'B1 · Конструкции', r4:true, tag:['wgram'], type:'error',
  q:'If I would have more time, I would read more.',
  tokens:['If','I','would','have','more','time,','I','would','read','more'], answer:2, fix:'had',
  ru:'если бы у меня было больше времени, я бы больше читал',
  why:'в части с if — would не ставим: If I had more time. Would живёт только во второй половине.' },
{ g:'B1 · Конструкции', r4:true, tag:['wgram'], type:'gap',
  q:'It is widely ___ that social media affects attention span. (believe → V3)',
  answer:['believed'], ru:'широко распространено мнение, что соцсети влияют на внимание',
  why:'безличный пассив «It is believed / argued / said that…» — способ дать мнение без «I think».' },
{ g:'B1 · Конструкции', r4:true, tag:['wgram'], type:'choose',
  q:'The data ___ over a period of ten years.',
  options:['were collecting','were collected','have collecting'], answer:1,
  ru:'данные собирали в течение десяти лет',
  why:'данные не собирают себя сами → пассив: were collected. В академическом письме пассив уместен и част.' },
{ g:'B1 · Конструкции', r4:true, tag:['wgram'], type:'choose',
  q:'Many students avoid ___ in seminars because they fear ___ mistakes.',
  options:['to speak / to make','speaking / making','speaking / to make'], answer:1,
  ru:'многие студенты избегают выступать на семинарах, потому что боятся ошибиться',
  why:'avoid и fear (как «бояться делать») берут -ing. Список «avoid / suggest / consider / involve» — учить целиком.' },
{ g:'B1 · Конструкции', r4:true, tag:['wgram'], type:'choose',
  q:'We stopped ___ the results — the printer had run out of paper.',
  options:['printing','to print','print'], answer:0,
  ru:'мы перестали печатать результаты',
  why:'stop DOING = прекратить это занятие. stop TO DO = остановиться, чтобы сделать. Смысл меняется целиком.' },
{ g:'B1 · Конструкции', r4:true, tag:['wgram'], type:'error',
  q:'The government should to reduce the tax on fuel.',
  tokens:['The','government','should','to','reduce','the','tax','on','fuel'], answer:3, fix:'—',
  ru:'государству следует снизить налог на топливо',
  why:'после модального — без to. Should reduce. Частая порча самой ходовой фразы Task 2.' },
{ g:'B1 · Конструкции', r4:true, tag:['wgram'], type:'choose',
  q:'The report, ___ was published last week, criticises the policy.',
  options:['that','which','what'], answer:1,
  ru:'отчёт, опубликованный на прошлой неделе, критикует эту политику',
  why:'после запятой (добавочное придаточное) — только which, никогда that и тем более what.' },
{ g:'B1 · Конструкции', r4:true, tag:['wgram'], type:'choose',
  q:'Students ___ in rural areas often have limited access to the internet.',
  options:['live','living','who living'], answer:1,
  ru:'студенты, живущие в сельской местности, часто ограничены в доступе к интернету',
  why:'сокращённое придаточное: who live → living. Экономит слова и поднимает Grammatical Range.' },
{ g:'B1 · Конструкции', r4:true, tag:['wgram'], type:'choose',
  q:'She said she ___ the assignment the day before.',
  options:['finished','had finished','has finished'], answer:1,
  ru:'она сказала, что закончила задание накануне',
  why:'косвенная речь сдвигает время назад: finished → had finished; yesterday → the day before.' },
{ g:'B1 · Конструкции', r4:true, tag:['wgram'], type:'error',
  q:'Could you tell me where is the library?',
  tokens:['Could','you','tell','me','where','is','the','library'], answer:5, fix:'the library is',
  ru:'не подскажете, где библиотека?',
  why:'непрямой вопрос — прямой порядок слов: where the library is. Инверсия остаётся только в первой части.' },
{ g:'B1 · Конструкции', r4:true, tag:['wgram'], type:'mgap',
  q:'Not only ___ the cost high, but the quality ___ (be) poor as well.',
  answer:[['is','was'],['is','was']],
  ru:'мало того, что цена высокая, так ещё и качество плохое',
  why:'после «not only» в начале — инверсия: Not only IS the cost high. Приём для эмфазы в эссе.' },
{ g:'B1 · Конструкции', r4:true, tag:['wgram'], type:'choose',
  q:'The city has ___ a new metro line built.',
  options:['have','had','been'], answer:1,
  ru:'город построил новую линию метро (силами подрядчиков)',
  why:'have something done = сделали не сам, а по твоему заказу. Конструкция, которую почти никто не использует, — и зря.' },
{ g:'B1 · Конструкции', r4:true, tag:['wgram'], type:'order',
  ru:'если бы не поддержка, проект бы провалился',
  tokens:['If','it','had','not','been','for','the','support,','the','project','would','have','failed'],
  answer:'If it had not been for the support, the project would have failed',
  why:'«if it had not been for X» = «если бы не X». Готовый оборот третьего типа.' },
{ g:'B1 · Конструкции', r4:true, tag:['wgram'], type:'choose',
  q:'I wish I ___ more attention to grammar at school.',
  options:['paid','had paid','would pay'], answer:1,
  ru:'жаль, что я не уделял грамматике больше внимания в школе',
  why:'сожаление о прошлом → I wish + Past Perfect (had paid).' },
{ g:'B1 · Конструкции', r4:true, tag:['wgram'], type:'pick',
  q:'Отметь ВСЕ грамматически корректные варианты.',
  options:[
    'Despite the cost, the project continued.',
    'Despite of the cost, the project continued.',
    'Although the cost was high, the project continued.',
    'Although the high cost, the project continued.'],
  answers:[0,2], ru:'',
  why:'despite + существительное (без of), although + подлежащее с глаголом. Самая частая порча связок в эссе.' },
{ g:'B1 · Конструкции', r4:true, tag:['wgram'], type:'choose',
  q:'The more people work remotely, ___ traffic there is in city centres.',
  options:['the less','less','the fewer'], answer:0,
  ru:'чем больше людей работает удалённо, тем меньше пробок в центре',
  why:'конструкция the more … the less … Traffic неисчисляемо, поэтому less, а не fewer.' },

/* ============================================================
   АКАДЕМИЧЕСКАЯ ЛЕКСИКА (tag:wlex)
   Балл за Lexical Resource растёт не от редких слов, а от точных.
   Здесь: AWL в контексте, коллокации, словообразование, путаницы.
   ============================================================ */
{ g:'B1 · Лексика', r4:true, lex:true, tag:['wlex'], type:'choose',
  q:'The study found a ___ difference between the two groups.',
  options:['big','significant','strong'], answer:1,
  ru:'исследование выявило существенное различие между группами',
  why:'significant difference — стандартная академическая пара. «big» звучит разговорно.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['wlex'], type:'gap',
  q:'Слово от «analyse»: The ___ of the data took two weeks. (существительное)',
  answer:['analysis'], ru:'анализ данных занял две недели',
  why:'analyse (глагол) → analysis (сущ.) → analytical (прил.). Классика словообразования в Task 1.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['wlex'], type:'choose',
  q:'Higher taxes could ___ people from buying large cars.',
  options:['prevent','discourage','avoid'], answer:1,
  ru:'высокие налоги могли бы отбить у людей желание покупать большие машины',
  why:'discourage somebody FROM doing — точное слово. prevent тоже с from, но это «не дать физически».' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['wlex'], type:'pick',
  q:'Отметь ВСЕ верные коллокации.',
  options:['carry out research','make research','do damage','make a decision','take an effect'],
  answers:[0,2,3], ru:'',
  why:'research — carry out / conduct / do, но не make. Эффект — HAVE an effect, не take.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['wlex'], type:'choose',
  q:'The new law will ___ the number of accidents.',
  options:['affect','effect','effective'], answer:0,
  ru:'новый закон повлияет на число аварий',
  why:'affect — глагол «влиять», effect — существительное «эффект». Проверка: перед ним стоит will → нужен глагол.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['wlex'], type:'gap',
  q:'The effect ___ the economy was immediate. (предлог)', answer:['on'],
  ru:'воздействие на экономику было немедленным',
  why:'an effect ON something — и в паре с этим: to have an effect on.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['wlex'], type:'choose',
  q:'There is ___ evidence to support this theory.',
  options:['enough big','sufficient','a lot'], answer:1,
  ru:'доказательств достаточно, чтобы поддержать эту теорию',
  why:'sufficient evidence — академический регистр. AWL-ядро: sufficient / adequate / considerable.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['wlex'], type:'choose',
  q:'This approach ___ several advantages.',
  options:['has','makes','does'], answer:0,
  ru:'у этого подхода несколько преимуществ',
  why:'have advantages / benefits. А «предпринять подход» — take / adopt an approach.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['wlex'], type:'pick',
  q:'Отметь ВСЕ слова, которые могут заменить «very important» в эссе.',
  options:['crucial','vital','very big','essential','super'],
  answers:[0,1,3], ru:'',
  why:'crucial / vital / essential — точнее и формальнее. «very big» и «super» в эссе не идут.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['wlex'], type:'choose',
  q:'Governments should ___ stricter rules on emissions.',
  options:['do','impose','put'], answer:1,
  ru:'государствам следует ввести более строгие правила по выбросам',
  why:'impose / introduce / implement rules — рабочие глаголы Task 2.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['wlex'], type:'gap',
  q:'Слово от «economy»: The ___ crisis lasted two years. (прилагательное про экономику в целом)',
  answer:['economic'], ru:'экономический кризис длился два года',
  why:'economic = про экономику; economical = экономный, бережливый. Разные слова.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['wlex'], type:'choose',
  q:'She was ___ by the results — she had expected the opposite.',
  options:['surprising','surprised','surprise'], answer:1,
  ru:'она была удивлена результатами',
  why:'-ed про того, кто чувствует; -ing про то, что вызывает. The results were surprising, she was surprised.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['wlex'], type:'choose',
  q:'The company failed to ___ the demand for the product.',
  options:['meet','reach','arrive'], answer:0,
  ru:'компания не смогла удовлетворить спрос на продукт',
  why:'meet demand / meet a deadline / meet requirements — одна семья коллокаций.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['wlex'], type:'pick',
  q:'Отметь ВСЕ пары, где слова НЕ синонимы.',
  options:['job / work','lend / borrow','raise / rise','study / learn'],
  answers:[1,2], ru:'',
  why:'lend = давать в долг, borrow = брать. raise берёт объект (raise prices), rise — нет (prices rise). А job/work и study/learn близки.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['wlex'], type:'gap',
  q:'Фразовый: We need to come ___ with a better solution. (придумать)',
  answer:['up'], ru:'нам нужно придумать решение получше',
  why:'come up with = придумать. В эссе лучше заменить на «propose / devise» — фразовые считаются разговорными.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['wlex'], type:'choose',
  q:'Формальный синоним «put off»:',
  options:['postpone','delay off','cancel'], answer:0,
  ru:'отложить', why:'put off → postpone. Пара «фразовый → латинский синоним» — прямой путь к Lexical Resource.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['wlex'], type:'choose',
  q:'The two countries have ___ approaches to education.',
  options:['different','differ','difference'], answer:0,
  ru:'у двух стран разные подходы к образованию',
  why:'перед существительным — прилагательное: different approaches. differ — глагол, difference — существительное.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['wlex'], type:'choose',
  q:'Which is more academic?',
  options:['Lots of people think that…','A considerable proportion of the population believes that…'],
  answer:1, ru:'',
  why:'точность + формальность. «Lots of» — разговорное, в письменном IELTS снижает балл.' },

/* ============================================================
   TASK 1 · ЯЗЫК ГРАФИКОВ (tag:task1)
   Здесь балл берут не идеями, а точностью описания. Набор
   формул небольшой и закрытый — его надо просто иметь.
   ============================================================ */
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task1'], type:'choose',
  q:'Sales ___ sharply between 2015 and 2018.',
  options:['raised','rose','arose'], answer:1,
  ru:'продажи резко выросли с 2015 по 2018',
  why:'rise — без объекта (rose). raise требует объект: they raised prices.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task1'], type:'mgap',
  q:'The figure fell ___ 12% ___ 2019. (на сколько / в каком году)',
  answer:[['by'],['in']],
  ru:'показатель упал на 12% в 2019 году',
  why:'по величине → by, год → in. Пара, которая ломается чаще всего.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task1'], type:'choose',
  q:'There was a ___ increase in energy consumption.',
  options:['dramatically','dramatic','drama'], answer:1,
  ru:'произошёл резкий рост потребления энергии',
  why:'перед существительным — прилагательное: a dramatic increase. Через глагол было бы: increased dramatically.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task1'], type:'gap',
  q:'The number ___ at 40% in 2020 — the highest point on the chart. (достиг пика)',
  answer:['peaked'], ru:'показатель достиг пика в 40% в 2020 году',
  why:'peaked AT 40%. Пара: bottomed out at / reached a low of.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task1'], type:'choose',
  q:'Cars ___ nearly half of all vehicles on the road.',
  options:['accounted for','counted','were consisted of'], answer:0,
  ru:'на автомобили приходилась почти половина всего транспорта',
  why:'account for = составлять долю. Синонимы: made up, represented, comprised.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task1'], type:'choose',
  q:'The figures remained ___ throughout the period.',
  options:['stable','stably','stability'], answer:0,
  ru:'показатели оставались стабильными весь период',
  why:'remain / stay — глаголы-связки, после них прилагательное: remained stable.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task1'], type:'pick',
  q:'Отметь ВСЁ, что уместно в Overview (общий вывод Task 1).',
  options:[
    'Overall, the trend was upward for all three countries.',
    'In 2011 the figure was exactly 43.2%.',
    'It is clear that men outnumbered women throughout.',
    'I think this chart is very interesting.'],
  answers:[0,2], ru:'',
  why:'Overview — про общие тенденции без точных цифр и без личного мнения. Цифры идут в основные абзацы.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task1'], type:'error',
  q:'The graph shows the amount of people who use public transport.',
  tokens:['The','graph','shows','the','amount','of','people','who','use','public','transport'],
  answer:4, fix:'number',
  ru:'график показывает число людей, пользующихся общественным транспортом',
  why:'people считаются → the NUMBER of. amount — для неисчисляемого (the amount of water).' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task1'], type:'choose',
  q:'Rice consumption in Japan fell, ___ in India it rose steadily.',
  options:['whereas','however','despite'], answer:0,
  ru:'потребление риса в Японии упало, тогда как в Индии росло',
  why:'whereas / while соединяют два контраста в ОДНОМ предложении. however требует точку или точку с запятой.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task1'], type:'order',
  ru:'показатель вырос с 20% до 35% за десять лет',
  tokens:['The','figure','rose','from','20%','to','35%','over','a','decade'],
  answer:'The figure rose from 20% to 35% over a decade',
  why:'from … to … про интервал, over про промежуток времени. Готовый каркас предложения Task 1.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task1'], type:'choose',
  q:'В Task 1 про диаграмму 2005 года правильнее писать:',
  options:['The chart shows how many people use…','The chart showed how many people used…'],
  answer:0, ru:'',
  why:'описание самого графика — настоящее время (shows). А данные внутри за 2005 год — прошедшее (used).' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task1'], type:'gap',
  q:'Синоним «slightly» для маленького изменения: the figure rose ___ . (marg…)',
  answer:['marginally'], ru:'показатель вырос незначительно',
  why:'slightly / marginally — маленькое изменение; sharply / dramatically — резкое; steadily — ровное.' },

/* ============================================================
   TASK 2 · ЯЗЫК АРГУМЕНТА (tag:task2)
   Позиция, осторожность формулировок, примеры, вывод. Здесь
   ломается не грамматика, а тон: слишком категорично и слишком
   разговорно — два самых частых способа потерять балл.
   ============================================================ */
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task2'], type:'choose',
  q:'Осторожная формулировка вместо «This always causes crime»:',
  options:['This may contribute to crime.','This causes crime 100%.','This never causes crime.'],
  answer:0, ru:'',
  why:'hedging: may / tend to / is likely to / can contribute. Категоричность легко опровергнуть — и балл падает.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task2'], type:'pick',
  q:'Отметь ВСЁ, чего в эссе IELTS быть НЕ должно.',
  options:['don’t','Furthermore,','stuff like that','In my opinion I think','To conclude,'],
  answers:[0,2,3], ru:'',
  why:'сокращения, разговорные обороты и «In my opinion I think» (двойное мнение). Furthermore и To conclude — норма.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task2'], type:'choose',
  q:'Введение примера в академическом тоне:',
  options:['For instance, Norway invests heavily in renewables.','Like Norway and stuff.','Take Norway for example, yeah.'],
  answer:0, ru:'', why:'For instance / For example / A case in point is… — нейтрально-формально.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task2'], type:'choose',
  q:'While this policy has clear benefits, it ___ several risks.',
  options:['also carries','also carry','is also carry'], answer:0,
  ru:'хотя у этой политики есть плюсы, она несёт и риски',
  why:'it → carries. Заодно каркас «While X…, it also…» — способ показать обе стороны в одном предложении.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task2'], type:'gap',
  q:'Связка-уступка: ___, this argument ignores the cost. (однако, с большой буквы)',
  answer:['however'], ru:'однако этот аргумент не учитывает стоимость',
  why:'However, … в начале предложения и с запятой. Внутри предложения — точка с запятой: …; however, …' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task2'], type:'error',
  q:'In conclusion, I strongly believe that governments must to act now.',
  tokens:['In','conclusion,','I','strongly','believe','that','governments','must','to','act','now'],
  answer:8, fix:'—',
  ru:'в заключение, я убеждён, что государствам необходимо действовать сейчас',
  why:'must + начальная форма, без to. Всё остальное в этой фразе — рабочий шаблон вывода.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task2'], type:'choose',
  q:'Что сильнее подходит для позиции автора в Task 2?',
  options:['I completely agree with this statement.','Maybe yes, maybe no.','I don’t know really.'],
  answer:0, ru:'',
  why:'позиция должна быть ясной с первого абзаца. Размытость снижает Task Response.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task2'], type:'choose',
  q:'The main reason ___ this trend is the cost of housing.',
  options:['of','for','to'], answer:1,
  ru:'главная причина этой тенденции — стоимость жилья',
  why:'the reason FOR something. Пара: the cause OF something.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task2'], type:'pick',
  q:'Отметь ВСЕ связки со значением «следовательно».',
  options:['therefore','thus','whereas','consequently','moreover'],
  answers:[0,1,3], ru:'',
  why:'whereas — контраст, moreover — добавление. Путаница в функции связки читается сразу.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task2'], type:'order',
  ru:'хотя у этого подхода есть преимущества, его недостатки перевешивают',
  tokens:['Although','this','approach','has','advantages,','its','drawbacks','outweigh','them'],
  answer:'Although this approach has advantages, its drawbacks outweigh them',
  why:'outweigh — глагол «перевешивать», ходовой в эссе «advantages vs disadvantages». И its без апострофа.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task2'], type:'error',
  q:'Its clear that the problem is getting worse.',
  tokens:['Its','clear','that','the','problem','is','getting','worse'], answer:0, fix:'It’s',
  ru:'ясно, что проблема усугубляется',
  why:'it’s = it is; its = притяжательное. В эссе, впрочем, лучше «It is clear» — без сокращения.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task2'], type:'choose',
  q:'Перефразируй тему во вступлении: «Some people think exams are useless.» →',
  options:['It is sometimes argued that examinations serve no purpose.',
           'Some people think exams are useless.'],
  answer:0, ru:'',
  why:'вступление должно перефразировать вопрос, а не переписать его. Копия задания не считается твоими словами.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task2'], type:'error',
  q:'Firstly, I want to talk about the economical benefits.',
  tokens:['Firstly,','I','want','to','talk','about','the','economical','benefits'],
  answer:7, fix:'economic',
  ru:'во-первых, об экономических выгодах',
  why:'economic = относящийся к экономике; economical = экономный. Заодно «I want to talk about» разговорно — лучше «This essay will examine».' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task2'], type:'gap',
  q:'Уступка перед своим аргументом: ___ this view has some merit, it overlooks the cost. (although/…)',
  answer:['although','while','whilst'],
  ru:'хотя в этом взгляде есть резон, он не учитывает стоимость',
  why:'although / while + подлежащее с глаголом. Признать чужой аргумент и тут же возразить — сильный ход в Task 2.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task2'], type:'pick',
  q:'Отметь ВСЁ, что должно быть в выводе Task 2.',
  options:['повтор позиции другими словами','краткая сводка аргументов',
           'новый аргумент, которого не было','точные цифры из головы'],
  answers:[0,1], ru:'',
  why:'вывод не вводит нового. Новая мысль в последнем абзаце читается как незаконченная работа.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['task2'], type:'choose',
  q:'A number of studies ___ shown a link between sleep and memory.',
  options:['has','have','is'], answer:1,
  ru:'ряд исследований показал связь между сном и памятью',
  why:'a number of + множественное → have. Сравни: the number of studies HAS risen.' },

/* ============================================================
   РЕГИСТР И СВЯЗНОСТЬ (tag:reg2)
   Coherence & Cohesion — четверть балла за Writing, и берётся
   она дешевле всего: отсылки, порядок, отсутствие повторов.
   ============================================================ */
{ g:'B1 · Лексика', r4:true, lex:true, tag:['reg2'], type:'choose',
  q:'Formal: «The company needs to ___ its spending.»',
  options:['cut down on','reduce','slash'], answer:1,
  ru:'компании нужно сократить расходы',
  why:'reduce — нейтрально-формально. cut down on — разговорно, slash — газетный жаргон.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['reg2'], type:'choose',
  q:'Чтобы не повторять «pollution» третий раз, лучше написать:',
  options:['this issue','that thing','pollution again'], answer:0,
  ru:'', why:'отсылки (this issue / such measures / the former) — самый дешёвый способ поднять Cohesion.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['reg2'], type:'error',
  q:'But there is another problem which is more serious.',
  tokens:['But','there','is','another','problem','which','is','more','serious'], answer:0,
  fix:'However,',
  ru:'однако есть и другая, более серьёзная проблема',
  why:'в письменном тексте предложение с But не начинают — берут However, / Nevertheless,.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['reg2'], type:'pick',
  q:'Отметь ВСЁ, что уместно в формальном письме или эссе.',
  options:['I would like to enquire about…','Hey, quick question','Please find attached…','Gonna send it tomorrow'],
  answers:[0,2], ru:'',
  why:'Hey и gonna — только для переписки с друзьями.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['reg2'], type:'choose',
  q:'Nowadays many people work from home. ___, this trend has accelerated since 2020.',
  options:['Indeed','Whereas','Despite'], answer:0,
  ru:'более того, эта тенденция ускорилась с 2020 года',
  why:'Indeed / In fact — усиление сказанного. Whereas и despite здесь не подходят по функции.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['reg2'], type:'choose',
  q:'Формальный вариант «a lot of research has been done»:',
  options:['considerable research has been conducted','tons of research was made'],
  answer:0, ru:'',
  why:'considerable + conducted. Заодно: research неисчисляемо, поэтому has, а не have.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['reg2'], type:'gap',
  q:'Связка контраста внутри предложения: cities grew, ___ villages emptied. (wh…)',
  answer:['whereas','while'], ru:'города росли, тогда как деревни пустели',
  why:'whereas / while — контраст без точки. Ходовой способ соединить два предложения в одно.' },
{ g:'B1 · Лексика', r4:true, lex:true, tag:['reg2'], type:'choose',
  q:'Сколько идей должно быть в одном абзаце эссе Task 2?',
  options:['одна главная, развёрнутая','как можно больше','ни одной, только связки'],
  answer:0, ru:'',
  why:'один абзац — одна мысль: заявление, объяснение, пример. Это и есть Coherence.' },
];
