/* ============================================================
   ПАЧКА 5 · МЕСЯЦ — топливо для дозы дня.

   Собрана 2026-08-31 под одну претензию: доза повторяла одни и те же
   предложения. Половина причины была в механике (см. engine/review.js,
   броня под новое), вторая — здесь: в горячих зонах лежало по 10–18
   вопросов, а «Ремонт» берёт по 10–14 за заход. При таком запасе
   любой тест — это один и тот же тест.

   Считалось так: доза 12 в день, месяц — 360 мест, из них по брони
   не меньше 40% новых → ~150 новых вопросов в месяц. Пачка даёт
   больше, потому что часть уйдёт в тесты «Ремонта» и миксы.

   Порядок зон — по доказанности, как в пачке 4: сначала то, где
   реально спотыкался (журнал устной практики и Past 4/7 в замере),
   потом расширение программы вширь.

   Метки: r5:true — пачка 5, mine:true — построено на твоей ошибке,
   lex:true — лексический вопрос. Метки зон те же, что в пачке 4:
   вопрос с tag:['prep3'] сам приезжает в тест «Предлоги · пары».
   ============================================================ */

export const DAILY_QUESTIONS = [

/* ============================================================
   PAST · НАРРАТИВ (tag:narr2) — главная пробоина замера, 4/7.
   Как и в пачке 4, почти каждый вопрос — два действия рядом:
   поодиночке эти времена ты знаешь, ломается выбор между ними.
   ============================================================ */
{ g:'Past', r5:true, tag:['narr2'], type:'choose',
  q:'By the time the police arrived, the thief ___.',
  options:['ran away','was running away','had run away'], answer:2,
  ru:'к приезду полиции вор уже сбежал',
  why:'«by the time + Past Simple» → то, что было раньше, уходит в Past Perfect: had run away.' },
{ g:'Past', r5:true, tag:['narr2'], type:'mgap',
  q:'She ___ (read) the letter twice before she ___ (answer) it.',
  answer:[['had read'],['answered']],
  ru:'она перечитала письмо дважды, прежде чем ответить',
  why:'before делит два прошлых действия: раньшее — Past Perfect, позднее — Past Simple.' },
{ g:'Past', r5:true, tag:['narr2'], type:'choose',
  q:'When I got to the office, I realised I ___ my badge at home.',
  options:['left','had left','was leaving'], answer:1,
  ru:'придя в офис, я понял, что оставил пропуск дома',
  why:'осознал позже, оставил раньше — два момента в одном предложении → Past Perfect.' },
{ g:'Past', r5:true, tag:['narr2'], type:'error',
  q:'While I was walk home, it started to rain.',
  tokens:['While','I','was','walk','home,','it','started','to','rain'], answer:3, fix:'walking',
  ru:'пока я шёл домой, начался дождь',
  why:'was + V-ing: was walking. Без -ing конструкция Past Continuous разваливается.' },
{ g:'Past', r5:true, tag:['narr2'], type:'choose',
  q:'The kids ___ in the garden when it started to snow.',
  options:['played','were playing','had played'], answer:1,
  ru:'дети играли в саду, когда пошёл снег',
  why:'длинный фон → Past Continuous; короткое событие, которое его прервало → Past Simple.' },
{ g:'Past', r5:true, tag:['narr2'], type:'order',
  ru:'она уже ушла, когда я позвонил',
  tokens:['She','had','already','left','when','I','called'],
  answer:'She had already left when I called',
  why:'already между had и V3 — стандартное место наречия в Perfect.' },
{ g:'Past', r5:true, tag:['narr2'], type:'form',
  q:'They ___ (live) in Kazan before they moved to Moscow.',
  answer:['had lived','had been living'],
  ru:'до переезда в Москву они жили в Казани',
  why:'before задаёт порядок: то, что было до, → Past Perfect.' },
{ g:'Past', r5:true, tag:['narr2'], type:'choose',
  q:'I ___ to that café before, so I knew the way.',
  options:['have been','had been','was'], answer:1,
  ru:'я бывал в том кафе раньше, поэтому знал дорогу',
  why:'опыт ДО момента в прошлом → had been. have been отсчитывает от сейчас, а рассказ идёт в прошлом.' },
{ g:'Past', r5:true, tag:['narr2'], type:'error',
  q:'When she was young, she use to play the violin.',
  tokens:['When','she','was','young,','she','use','to','play','the','violin'], answer:5, fix:'used',
  ru:'в детстве она играла на скрипке',
  why:'в утверждении — used to. Форма use to живёт только после didn’t.' },
{ g:'Past', r5:true, tag:['narr2'], type:'choose',
  q:'He didn’t recognise me because we ___ for ten years.',
  options:['didn’t meet','hadn’t met','weren’t meeting'], answer:1,
  ru:'он не узнал меня, потому что мы не виделись десять лет',
  why:'состояние «к тому моменту уже десять лет» → Past Perfect: hadn’t met.' },
{ g:'Past', r5:true, tag:['narr2'], type:'mgap',
  q:'I ___ (wait) for twenty minutes when she finally ___ (turn) up.',
  answer:[['had been waiting'],['turned']],
  ru:'я ждал уже двадцать минут, когда она наконец появилась',
  why:'«уже сколько-то времени К моменту в прошлом» → Past Perfect Continuous.' },
{ g:'Past', r5:true, tag:['narr2'], type:'choose',
  q:'Что случилось раньше: «He had finished the report when the boss came in»?',
  options:['пришёл начальник','он дописал отчёт','одновременно'], answer:1, ru:'',
  why:'had finished — то, что раньше. Past Perfect всегда отматывает назад от второго действия.' },
{ g:'Past', r5:true, tag:['narr2'], type:'error',
  q:'Yesterday she has called me twice.',
  tokens:['Yesterday','she','has','called','me','twice'], answer:2, fix:'—', altfix:'called',
  ru:'вчера она звонила мне дважды',
  why:'есть «yesterday» — точка в прошлом → Past Simple: she called. Perfect с точным временем не живёт.', mine:true },
{ g:'Past', r5:true, tag:['narr2'], type:'order',
  ru:'к девяти вечера мы уже поужинали',
  tokens:['By','nine','we','had','already','had','dinner'],
  answer:'By nine we had already had dinner',
  why:'had had — не опечатка: первое had строит Perfect, второе значит «поужинали».' },
{ g:'Past', r5:true, tag:['narr2'], type:'choose',
  q:'Как сказать «я не знал, что она уже уехала»?',
  options:['I didn’t know she already left.','I didn’t know she had already left.','I don’t know she had already left.'],
  answer:1, ru:'',
  why:'главное в прошлом → придаточное отматывает ещё дальше: had left.' },
{ g:'Past', r5:true, tag:['narr2'], type:'pick',
  q:'Отметь ВСЕ предложения, где нарратив собран верно.',
  options:[
    'She had cooked dinner before we arrived.',
    'While he read, the door was opening.',
    'They were arguing when I walked in.',
    'I use to live here.'],
  answers:[0,2], ru:'',
  why:'2 — фон и прерывание перепутаны местами: While he WAS READING, the door OPENED. 4 — used to, а не use to.' },
{ g:'Past', r5:true, tag:['narr2'], type:'choose',
  q:'We ___ in that flat for three years before the landlord sold it.',
  options:['lived','had lived','were living'], answer:1,
  ru:'мы прожили в той квартире три года, пока хозяин её не продал',
  why:'срок, закрывшийся ДО второго прошлого события → Past Perfect.' },
{ g:'Past', r5:true, tag:['narr2'], type:'error',
  q:'The film had started at seven o’clock.',
  tokens:['The','film','had','started','at','seven','o’clock'], answer:2, fix:'—', altfix:'started',
  ru:'фильм начался в семь',
  why:'Past Perfect нужен рядом со вторым прошлым действием. Одинокий факт с точным временем → Past Simple.' },
{ g:'Past', r5:true, tag:['narr2'], type:'mgap',
  q:'When the guests ___ (arrive), she ___ (still, cook).',
  answer:[['arrived'],['was still cooking']],
  ru:'когда гости пришли, она ещё готовила',
  why:'процесс в тот момент → Past Continuous; still встаёт между was и глаголом.' },
{ g:'Past', r5:true, tag:['narr2'], type:'choose',
  q:'He ___ get up at five when he worked at the bakery.',
  options:['would','will','was'], answer:0,
  ru:'когда он работал в пекарне, он вставал в пять',
  why:'повторяющееся действие в прошлом → would + начальная форма (как used to).' },
{ g:'Past', r5:true, tag:['narr2'], type:'gap',
  q:'I didn’t ___ to like olives, but now I love them. (use/used)', answer:['use'],
  ru:'раньше я не любил оливки, а теперь обожаю',
  why:'после didn’t — начальная форма: didn’t use to. То же правило, что didn’t go.' },
{ g:'Past', r5:true, tag:['narr2'], type:'choose',
  q:'She looked exhausted — she ___ all night.',
  options:['worked','had been working','was working'], answer:1,
  ru:'она выглядела вымотанной — работала всю ночь',
  why:'причина видимого состояния, тянувшаяся до момента → Past Perfect Continuous.' },

/* ============================================================
   ПРЕДЛОГИ (tag:prep3) — горячая зона №1 по журналу, 4 повтора.
   Пары «глагол + предлог» и «существительное + предлог», где
   русский подсказывает не тот предлог.
   ============================================================ */
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'gap',
  q:'It depends ___ the weather. (on/from/of)', answer:['on'],
  ru:'это зависит от погоды',
  why:'depend ON — всегда. Русское «от» тянет к from, и это ошибка №1 в зоне.', mine:true },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'choose',
  q:'The report notes a steady decline ___ birth rates.',
  options:['of','in','to'], answer:1,
  ru:'в отчёте отмечен устойчивый спад рождаемости',
  why:'rise / increase / fall + IN + чего именно. Того же требует decline и growth.' },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'error',
  q:'She is married with a doctor.',
  tokens:['She','is','married','with','a','doctor'], answer:3, fix:'to',
  ru:'она замужем за врачом',
  why:'married TO — калька «с кем» здесь не работает.' },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'gap',
  q:'I’m not very good ___ maths. (at/in/on)', answer:['at'],
  ru:'у меня не очень с математикой',
  why:'good AT + дело, в котором ты хорош.' },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'choose',
  q:'He apologised ___ being late.',
  options:['for','about','of'], answer:0,
  ru:'он извинился за опоздание',
  why:'apologise FOR + что сделал. После предлога — форма на -ing.' },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'choose',
  q:'This book is different ___ the one I read last year.',
  options:['from','than','of'], answer:0,
  ru:'эта книга не такая, как та, что я читал в прошлом году',
  why:'different FROM. Вариант different than встречается в США, но на экзамене безопаснее from.' },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'error',
  q:'We discussed about the budget for an hour.',
  tokens:['We','discussed','about','the','budget','for','an','hour'], answer:2, fix:'—',
  ru:'мы час обсуждали бюджет',
  why:'discuss берёт прямое дополнение, без предлога: discuss the budget. Предлог нужен у talk about.' },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'gap',
  q:'The number ___ applicants doubled this year. (of/in/for)', answer:['of'],
  ru:'число заявок в этом году удвоилось',
  why:'the number OF — про количество. Дальше глагол в единственном: the number was.' },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'choose',
  q:'I’m looking forward ___ from you.',
  options:['to hear','to hearing','hearing'], answer:1,
  ru:'жду вашего ответа',
  why:'look forward TO — здесь to предлог, а не частица инфинитива → дальше -ing.' },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'error',
  q:'She insisted to pay for everything.',
  tokens:['She','insisted','to','pay','for','everything'], answer:2, fix:'on paying',
  ru:'она настояла на том, чтобы заплатить за всё',
  why:'insist ON + -ing. Инфинитив после insist невозможен.' },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'gap',
  q:'Prices fell ___ 12% last year. (by/on/at)', answer:['by'],
  ru:'цены упали на 12%',
  why:'на сколько изменилось → BY. «Упали ДО отметки» — to: fell to 40%.' },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'choose',
  q:'Smoking can lead ___ serious health problems.',
  options:['to','on','into'], answer:0,
  ru:'курение может привести к серьёзным проблемам со здоровьем',
  why:'lead TO — базовая связка причины и следствия для эссе.' },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'gap',
  q:'He’s responsible ___ hiring new staff. (for/of/on)', answer:['for'],
  ru:'он отвечает за наём сотрудников',
  why:'responsible FOR — запоминать парой.' },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'choose',
  q:'There’s no need to worry ___ the results.',
  options:['about','for','of'], answer:0,
  ru:'не о чем волноваться по поводу результатов',
  why:'worry ABOUT. С for живёт другое слово: care for.' },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'error',
  q:'I have never been in Japan.',
  tokens:['I','have','never','been','in','Japan'], answer:4, fix:'to',
  ru:'я никогда не был в Японии',
  why:'been TO — про поездку. been IN значит «находился внутри», это про место, а не про опыт.' },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'choose',
  q:'The results ___ the survey were published in May.',
  options:['of','from','about'], answer:0,
  ru:'результаты опроса опубликовали в мае',
  why:'результаты ЧЕГО → of. Русское «из» сбивает на from.', mine:true },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'gap',
  q:'She graduated ___ Moscow State University. (from/in/at)', answer:['from'],
  ru:'она окончила МГУ',
  why:'graduate FROM + учебное заведение.' },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'choose',
  q:'He has been working ___ this company since 2019.',
  options:['for','from','since'], answer:0,
  ru:'он работает в этой компании с 2019 года',
  why:'work FOR + компания как работодатель. Since уже стоит дальше и второй раз не нужен.' },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'error',
  q:'It depends of how much time we have.',
  tokens:['It','depends','of','how','much','time','we','have'], answer:2, fix:'on',
  ru:'это зависит от того, сколько у нас времени',
  why:'depend ON, без вариантов.', mine:true },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'choose',
  q:'I’m interested ___ applying for the scholarship.',
  options:['in','on','for'], answer:0,
  ru:'мне интересно подать на стипендию',
  why:'interested IN + -ing.' },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'gap',
  q:'The demand ___ housing keeps growing. (for/of/on)', answer:['for'],
  ru:'спрос на жильё продолжает расти',
  why:'demand FOR — пара для эссе про экономику.' },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'choose',
  q:'She’s afraid ___ flying.',
  options:['of','from','for'], answer:0,
  ru:'она боится летать',
  why:'afraid OF + -ing.' },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'error',
  q:'We arrived to the airport at six.',
  tokens:['We','arrived','to','the','airport','at','six'], answer:2, fix:'at',
  ru:'мы приехали в аэропорт в шесть',
  why:'arrive AT + точка (вокзал, аэропорт), arrive IN + город или страна. С to не бывает вовсе.' },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'pick',
  q:'Отметь ВСЕ пары, где предлог стоит верно.',
  options:['depend on','consist of','discuss about','result in'],
  answers:[0,1,3], ru:'',
  why:'discuss — без предлога. Остальные три — устойчивые пары, которые стоит выучить целиком.' },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'gap',
  q:'The graph shows a fall ___ sales between May and July. (in/of/to)', answer:['in'],
  ru:'график показывает падение продаж с мая по июль',
  why:'fall IN — как rise in и increase in. Прямо пригодится в Task 1.' },
{ g:'Предлоги+', r5:true, tag:['prep3'], type:'choose',
  q:'They accused him ___ stealing the data.',
  options:['of','in','for'], answer:0,
  ru:'его обвинили в краже данных',
  why:'accuse OF + -ing. Рядом живёт blame FOR — предлоги разные.' },

/* ============================================================
   PERFECT ↔ PAST (tag:perf3) — «Present Perfect вместо did» и
   обратно, 2 повтора в журнале. Ключ везде один: есть ли в
   предложении точка в прошлом и тянется ли действие до сейчас.
   ============================================================ */
{ g:'Времена+', r5:true, tag:['perf3'], type:'choose',
  q:'I ___ my wallet. Can you lend me some money?',
  options:['lost','have lost','had lost'], answer:1,
  ru:'я потерял кошелёк, займёшь денег?',
  why:'результат важен сейчас (кошелька нет) → Present Perfect.' },
{ g:'Времена+', r5:true, tag:['perf3'], type:'error',
  q:'I have seen him three days ago.',
  tokens:['I','have','seen','him','three','days','ago'], answer:1, fix:'—', altfix:'saw',
  ru:'я видел его три дня назад',
  why:'ago — точка в прошлом → Past Simple: I saw him. Perfect и ago несовместимы.', mine:true },
{ g:'Времена+', r5:true, tag:['perf3'], type:'mgap',
  q:'She ___ (work) here since 2020 and she ___ (not, plan) to leave.',
  answer:[['has worked','has been working'],['doesn’t plan','does not plan']],
  ru:'она работает здесь с 2020-го и уходить не собирается',
  why:'since + до сих пор → Present Perfect. Второе — обычный факт сейчас, Present Simple.' },
{ g:'Времена+', r5:true, tag:['perf3'], type:'choose',
  q:'How long ___ you ___ English?',
  options:['did / learn','have / been learning','are / learning'], answer:1,
  ru:'как долго ты учишь английский?',
  why:'«сколько времени и до сих пор» → have been + -ing.' },
{ g:'Времена+', r5:true, tag:['perf3'], type:'choose',
  q:'— Where’s Tom? — He ___ to the bank.',
  options:['has been','has gone','went'], answer:1,
  ru:'— где Том? — ушёл в банк',
  why:'gone — ушёл и ещё там. been — сходил и вернулся. Здесь его нет на месте.' },
{ g:'Времена+', r5:true, tag:['perf3'], type:'choose',
  q:'She ___ to Paris twice, so she knows the city well.',
  options:['has been','has gone','was going'], answer:0,
  ru:'она дважды была в Париже, поэтому хорошо знает город',
  why:'опыт «бывала и вернулась» → has been.' },
{ g:'Времена+', r5:true, tag:['perf3'], type:'error',
  q:'I am living here since March.',
  tokens:['I','am','living','here','since','March'], answer:1, fix:'have been',
  ru:'я живу здесь с марта',
  why:'since тянет от прошлого до сейчас → have been living. Present Continuous так далеко не достаёт.' },
{ g:'Времена+', r5:true, tag:['perf3'], type:'gap',
  q:'We haven’t seen each other ___ 2019. (since/for/from)', answer:['since'],
  ru:'мы не виделись с 2019 года',
  why:'since + момент начала. for + длительность.' },
{ g:'Времена+', r5:true, tag:['perf3'], type:'gap',
  q:'They have known each other ___ ten years. (for/since/during)', answer:['for'],
  ru:'они знакомы десять лет',
  why:'for + сколько длится. during так не работает вовсе.' },
{ g:'Времена+', r5:true, tag:['perf3'], type:'choose',
  q:'I ___ this film before — let’s watch something else.',
  options:['saw','have seen','had seen'], answer:1,
  ru:'я уже видел этот фильм, давай другой',
  why:'опыт без указания когда → Present Perfect.' },
{ g:'Времена+', r5:true, tag:['perf3'], type:'error',
  q:'Did you ever been to Spain?',
  tokens:['Did','you','ever','been','to','Spain'], answer:0, fix:'Have',
  ru:'ты когда-нибудь был в Испании?',
  why:'been живёт только с have/has. did + been вместе не бывает — твоя ошибка из Рубежа 2.', mine:true },
{ g:'Времена+', r5:true, tag:['perf3'], type:'choose',
  q:'He ___ his leg, so he can’t play on Saturday.',
  options:['broke','has broken','was breaking'], answer:1,
  ru:'он сломал ногу и в субботу не сыграет',
  why:'последствие живо сейчас → Present Perfect.' },
{ g:'Времена+', r5:true, tag:['perf3'], type:'pick',
  q:'Отметь ВСЕ маркеры, которые тянут Present Perfect.',
  options:['just','in 2015','yet','so far','last week'],
  answers:[0,2,3], ru:'',
  why:'in 2015 и last week — закрытые точки в прошлом, им положен Past Simple.' },
{ g:'Времена+', r5:true, tag:['perf3'], type:'mgap',
  q:'I ___ (finish) the report yesterday, but I ___ (not, send) it yet.',
  answer:[['finished'],['haven’t sent','have not sent']],
  ru:'отчёт я дописал вчера, но ещё не отправил',
  why:'yesterday → Past Simple; yet → Present Perfect. Два времени в одном предложении — норма.' },
{ g:'Времена+', r5:true, tag:['perf3'], type:'choose',
  q:'Your English ___ a lot this year.',
  options:['improved','has improved','is improving'], answer:1,
  ru:'твой английский сильно вырос за этот год',
  why:'this year ещё не кончился → период открыт → Present Perfect.' },
{ g:'Времена+', r5:true, tag:['perf3'], type:'choose',
  q:'She’s tired because she ___ all morning.',
  options:['has cleaned','has been cleaning','cleaned'], answer:1,
  ru:'она устала, потому что убиралась всё утро',
  why:'важен процесс и его след (усталость) → Perfect Continuous.' },
{ g:'Времена+', r5:true, tag:['perf3'], type:'choose',
  q:'I ___ three chapters today — two more to go.',
  options:['have read','have been reading','read'], answer:0,
  ru:'сегодня я прочитал три главы, осталось две',
  why:'важен счёт сделанного → Present Perfect. Perfect Continuous не считает штуки.' },
{ g:'Времена+', r5:true, tag:['perf3'], type:'form',
  q:'He ___ (not, reply) to my email yet.', answer:['hasn’t replied','has not replied'],
  ru:'он ещё не ответил на моё письмо',
  why:'yet в отрицании → Present Perfect.' },
{ g:'Времена+', r5:true, tag:['perf3'], type:'order',
  ru:'я живу здесь с прошлого года',
  tokens:['I','have','lived','here','since','last','year'],
  answer:'I have lived here since last year',
  why:'since + точка старта, действие тянется до сейчас.' },
{ g:'Времена+', r5:true, tag:['perf3'], type:'error',
  q:'How long have you been work here?',
  tokens:['How','long','have','you','been','work','here'], answer:5, fix:'working',
  ru:'как долго ты здесь работаешь?',
  why:'have been + V-ing. После been нужна форма на -ing.' },

/* ============================================================
   ЛИШНИЙ -ING (tag:ing2) — 2 повтора в журнале.
   Глаголы состояния не идут в Continuous, но половина из них
   умеет быть и действием — и тогда -ing внезапно можно.
   Поэтому здесь не список запретов, а пары «состояние ↔ действие».
   ============================================================ */
{ g:'Present', r5:true, tag:['ing2'], type:'error',
  q:'She is having two brothers.',
  tokens:['She','is','having','two','brothers'], answer:1, fix:'—', altfix:'has',
  ru:'у неё два брата',
  why:'have в значении «иметь» — состояние: She has two brothers. А have breakfast — действие, там -ing можно.' },
{ g:'Present', r5:true, tag:['ing2'], type:'choose',
  q:'This soup ___ delicious.',
  options:['is tasting','tastes','is taste'], answer:1,
  ru:'этот суп очень вкусный',
  why:'taste про вкус блюда — состояние. «Is tasting» значило бы «пробует на вкус».' },
{ g:'Present', r5:true, tag:['ing2'], type:'choose',
  q:'I ___ you’re right about this.',
  options:['am thinking','think','thinks'], answer:1,
  ru:'я думаю, ты прав',
  why:'think «считать» — состояние. Think «обдумывать» — действие: I’m thinking about it.' },
{ g:'Present', r5:true, tag:['ing2'], type:'choose',
  q:'He ___ the car at the moment — that’s why he isn’t answering.',
  options:['washes','is washing','wash'], answer:1,
  ru:'он сейчас моет машину, поэтому не берёт трубку',
  why:'wash — обычное действие, прямо сейчас → Continuous. Запрет касается только состояний.' },
{ g:'Present', r5:true, tag:['ing2'], type:'pick',
  q:'Отметь ВСЕ глаголы, которые обычно НЕ ставят в -ing.',
  options:['belong','build','seem','contain','carry'],
  answers:[0,2,3], ru:'',
  why:'belong / seem / contain — состояния. build и carry — действия, им -ing положен.' },
{ g:'Present', r5:true, tag:['ing2'], type:'choose',
  q:'What ___ you ___ about? — Nothing important.',
  options:['do / think','are / thinking','are / think'], answer:1,
  ru:'о чём думаешь? — да так, ни о чём',
  why:'здесь think — процесс в голове прямо сейчас, а не мнение → Continuous можно.' },
{ g:'Present', r5:true, tag:['ing2'], type:'error',
  q:'I am seeing what you mean.',
  tokens:['I','am','seeing','what','you','mean'], answer:1, fix:'—', altfix:'see',
  ru:'я понимаю, о чём ты',
  why:'see «понимать» — состояние: I see. А I’m seeing the dentist — встреча, там -ing законен.' },
{ g:'Present', r5:true, tag:['ing2'], type:'choose',
  q:'We ___ the flat on Friday — the agent has confirmed it.',
  options:['see','are seeing','are being seen'], answer:1,
  ru:'мы смотрим квартиру в пятницу — агент подтвердил',
  why:'договорённость на будущее → Present Continuous. See здесь действие, а не состояние.' },
{ g:'Present', r5:true, tag:['ing2'], type:'error',
  q:'She is owning three flats in the city.',
  tokens:['She','is','owning','three','flats','in','the','city'], answer:1, fix:'—', altfix:'owns',
  ru:'у неё в городе три квартиры',
  why:'own — состояние, Continuous не берёт ни в каком времени: She owns.' },
{ g:'Present', r5:true, tag:['ing2'], type:'choose',
  q:'I ___ a headache since this morning.',
  options:['am having','have had','have been having'], answer:1,
  ru:'у меня с утра болит голова',
  why:'have тут «испытывать» — состояние → have had. С since всё равно нужен Perfect.' },
{ g:'Present', r5:true, tag:['ing2'], type:'gap',
  q:'This bag ___ to Karina, not to me. (belong)', answer:['belongs'],
  ru:'эта сумка Карины, а не моя',
  why:'belong — состояние, только Simple: belongs. Формы is belonging не существует.' },
{ g:'Present', r5:true, tag:['ing2'], type:'choose',
  q:'He ___ rude today, but normally he’s very polite.',
  options:['is','is being','be'], answer:1,
  ru:'он сегодня грубит, хотя вообще вежливый',
  why:'is being = ведёт себя так временно. Редкий случай, когда be само идёт в Continuous.' },
{ g:'Present', r5:true, tag:['ing2'], type:'error',
  q:'They are knowing the answer already.',
  tokens:['They','are','knowing','the','answer','already'], answer:1, fix:'—', altfix:'know',
  ru:'они уже знают ответ',
  why:'know — состояние, -ing не берёт никогда: They know.', mine:true },
{ g:'Present', r5:true, tag:['ing2'], type:'pick',
  q:'Отметь ВСЕ верные предложения.',
  options:['I am liking this course.','I like this course.','She is needing help.','She needs help.'],
  answers:[1,3], ru:'',
  why:'like и need — состояния: I like, she needs. Вариантов с -ing у них нет.' },
{ g:'Present', r5:true, tag:['ing2'], type:'choose',
  q:'Sorry, I ___ the question. Could you repeat it?',
  options:['am not understanding','don’t understand','not understand'], answer:1,
  ru:'извини, я не понял вопрос, повтори',
  why:'understand — состояние, отрицание через don’t: I don’t understand.', mine:true },
{ g:'Present', r5:true, tag:['ing2'], type:'choose',
  q:'The soup ___ — can you turn the heat down?',
  options:['boils','is boiling','boil'], answer:1,
  ru:'суп кипит, убавь огонь',
  why:'происходит прямо сейчас, и boil — действие → Continuous. Не всё подряд запрещено.' },

/* ============================================================
   АРТИКЛИ И КВАНТОРЫ (tag:quant2) — «артикль с неисчисляемым»
   из журнала. Русскому здесь не на что опереться: артиклей нет,
   а деление на исчисляемое и неисчисляемое проходит не там.
   ============================================================ */
{ g:'Кванторы', r5:true, tag:['quant2'], type:'choose',
  q:'Could you give me ___ advice?',
  options:['an','some','a few'], answer:1,
  ru:'посоветуешь что-нибудь?',
  why:'advice неисчисляемое: ни an, ни a few. Штуками — a piece of advice.', mine:true },
{ g:'Кванторы', r5:true, tag:['quant2'], type:'error',
  q:'I need some informations about the course.',
  tokens:['I','need','some','informations','about','the','course'], answer:3, fix:'information',
  ru:'мне нужна информация о курсе',
  why:'information не имеет множественного числа. Как и advice, research, equipment.' },
{ g:'Кванторы', r5:true, tag:['quant2'], type:'choose',
  q:'There isn’t ___ milk left.',
  options:['many','much','a few'], answer:1,
  ru:'молока почти не осталось',
  why:'неисчисляемое → much. many и a few только со счётным.' },
{ g:'Кванторы', r5:true, tag:['quant2'], type:'choose',
  q:'She has ___ friends in Berlin — three or four.',
  options:['a few','a little','little'], answer:0,
  ru:'у неё в Берлине есть пара друзей',
  why:'friends счётные → a few. a little — для неисчисляемого.' },
{ g:'Кванторы', r5:true, tag:['quant2'], type:'choose',
  q:'We have ___ time, so let’s not rush.',
  options:['a little','a few','few'], answer:0,
  ru:'времени немного есть, так что не будем спешить',
  why:'a little = немного, но есть. Без артикля little значило бы «почти нет».' },
{ g:'Кванторы', r5:true, tag:['quant2'], type:'choose',
  q:'There is ___ hope left — almost none.',
  options:['little','a little','few'], answer:0,
  ru:'надежды почти не осталось',
  why:'little без артикля — «мало, и это плохо». Артикль переворачивает смысл.' },
{ g:'Кванторы', r5:true, tag:['quant2'], type:'gap',
  q:'He gave me ___ useful piece of advice. (a/an/the)', answer:['a'],
  ru:'он дал мне один полезный совет',
  why:'артикль цепляется к piece, а не к advice: a piece. Перед useful звук [j], поэтому a, не an.' },
{ g:'Кванторы', r5:true, tag:['quant2'], type:'error',
  q:'The furnitures in the office are new.',
  tokens:['The','furnitures','in','the','office','are','new'], answer:1, fix:'furniture',
  ru:'мебель в офисе новая',
  why:'furniture неисчисляемое: furniture is new. Множественного числа у него нет.' },
{ g:'Кванторы', r5:true, tag:['quant2'], type:'choose',
  q:'___ money you gave me was enough.',
  options:['A','The','—'], answer:1,
  ru:'денег, которые ты дал, хватило',
  why:'конкретные, названные дальше деньги → the. Неисчисляемое артикль the берёт спокойно.' },
{ g:'Кванторы', r5:true, tag:['quant2'], type:'choose',
  q:'I’d like to be ___ engineer.',
  options:['a','an','the'], answer:1,
  ru:'я хочу быть инженером',
  why:'профессия всегда с артиклем, а перед гласным звуком → an.' },
{ g:'Кванторы', r5:true, tag:['quant2'], type:'choose',
  q:'She plays ___ piano every evening.',
  options:['a','the','—'], answer:1,
  ru:'она играет на пианино каждый вечер',
  why:'музыкальный инструмент → play THE piano. А вот play football — без артикля.' },
{ g:'Кванторы', r5:true, tag:['quant2'], type:'choose',
  q:'He goes to ___ work by bike.',
  options:['a','the','—'], answer:2,
  ru:'он ездит на работу на велосипеде',
  why:'to work / to school / to bed — по назначению, без артикля.' },
{ g:'Кванторы', r5:true, tag:['quant2'], type:'pick',
  q:'Отметь ВСЕ неисчисляемые существительные.',
  options:['research','suggestion','equipment','result','knowledge'],
  answers:[0,2,4], ru:'',
  why:'suggestion и result считаются штуками. research, equipment, knowledge — нет: two researches не бывает.' },
{ g:'Кванторы', r5:true, tag:['quant2'], type:'error',
  q:'I have too many work to do.',
  tokens:['I','have','too','many','work','to','do'], answer:3, fix:'much',
  ru:'у меня слишком много работы',
  why:'work здесь неисчисляемое → too much work.' },
{ g:'Кванторы', r5:true, tag:['quant2'], type:'choose',
  q:'How ___ luggage are you taking?',
  options:['many','much','a lot'], answer:1,
  ru:'сколько багажа ты берёшь?',
  why:'luggage неисчисляемое → how much. Штуками — how many bags.' },
{ g:'Кванторы', r5:true, tag:['quant2'], type:'gap',
  q:'There were ___ of people at the station. (lots/much/many)', answer:['lots'],
  ru:'на вокзале было полно народу',
  why:'lots of работает и со счётным, и с неисчисляемым — безопасный вариант в речи.' },
{ g:'Кванторы', r5:true, tag:['quant2'], type:'choose',
  q:'___ of the students passed — only two failed.',
  options:['Most','Almost','The most'], answer:0,
  ru:'большинство студентов сдали, провалились только двое',
  why:'most of the — «большинство из». Almost так не работает, а the most — превосходная степень.' },
{ g:'Кванторы', r5:true, tag:['quant2'], type:'error',
  q:'Every students must bring an ID.',
  tokens:['Every','students','must','bring','an','ID'], answer:1, fix:'student',
  ru:'каждый студент должен принести удостоверение',
  why:'every / each + единственное число: every student.' },
{ g:'Кванторы', r5:true, tag:['quant2'], type:'choose',
  q:'I don’t have ___ experience with this software.',
  options:['many','much','a few'], answer:1,
  ru:'у меня мало опыта с этой программой',
  why:'experience «опыт» неисчисляемое → much. А experiences «случаи из жизни» — счётные.' },
{ g:'Кванторы', r5:true, tag:['quant2'], type:'mgap',
  q:'We stayed at ___ hotel near the station. ___ hotel was cheap and clean.',
  answer:[['a'],['The','the']],
  ru:'мы остановились в отеле у вокзала; отель был дешёвый и чистый',
  why:'первый раз называем → a, второй раз про него же → the. Это и есть вся логика артиклей.' },
{ g:'Кванторы', r5:true, tag:['quant2'], type:'choose',
  q:'She is ___ best student in the group.',
  options:['a','the','—'], answer:1,
  ru:'она лучшая студентка в группе',
  why:'превосходная степень всегда с the: the best, the most important.' },
{ g:'Кванторы', r5:true, tag:['quant2'], type:'error',
  q:'The life is hard sometimes.',
  tokens:['The','life','is','hard','sometimes'], answer:0, fix:'—',
  ru:'жизнь иногда тяжёлая',
  why:'понятие вообще → без артикля: Life is hard. The появилось бы, будь это чья-то конкретная жизнь.', mine:true },
{ g:'Кванторы', r5:true, tag:['quant2'], type:'choose',
  q:'There is ___ evidence that the method works.',
  options:['a little','a few','few'], answer:0,
  ru:'есть некоторые свидетельства, что метод работает',
  why:'evidence неисчисляемое → a little. Кусками — two pieces of evidence.' },
{ g:'Кванторы', r5:true, tag:['quant2'], type:'gap',
  q:'Neither of the answers ___ correct. (is/are)', answer:['is'],
  ru:'ни один из ответов не верен',
  why:'neither of + глагол в единственном. В речи говорят и are, но в письме проверяющий ждёт is.' },

/* ============================================================
   УСЛОВНЫЕ (tag:cond) — дальше идёт расширение программы вширь:
   зоны, где запаса хватало ровно на один заход теста.
   ============================================================ */
{ g:'Условия', r5:true, tag:['cond'], type:'choose',
  q:'If it ___ tomorrow, we’ll stay at home.',
  options:['rains','will rain','would rain'], answer:0,
  ru:'если завтра пойдёт дождь, останемся дома',
  why:'после if будущего времени не бывает: условие в Present, результат с will.' },
{ g:'Условия', r5:true, tag:['cond'], type:'choose',
  q:'If I ___ you, I’d take the offer.',
  options:['am','was','were'], answer:2,
  ru:'на твоём месте я бы согласился',
  why:'воображаемая ситуация → if I were. Это форма сослагательного, а не ошибка в числе.' },
{ g:'Условия', r5:true, tag:['cond'], type:'error',
  q:'We will start as soon as everyone will arrive.',
  tokens:['We','will','start','as','soon','as','everyone','will','arrive'], answer:7, fix:'—', altfix:'arrives',
  ru:'начнём, как только все соберутся',
  why:'после as soon as / when / until будущего не бывает — там Present: everyone arrives.' },
{ g:'Условия', r5:true, tag:['cond'], type:'mgap',
  q:'If she ___ (study) harder, she ___ (pass) the exam last June.',
  answer:[['had studied'],['would have passed']],
  ru:'если бы она больше занималась, сдала бы экзамен в июне',
  why:'сожаление о прошлом (третий тип): had + V3 → would have + V3.' },
{ g:'Условия', r5:true, tag:['cond'], type:'choose',
  q:'Water ___ at 100 degrees.',
  options:['boils','will boil','would boil'], answer:0,
  ru:'вода кипит при ста градусах',
  why:'всегда верный факт (нулевой тип): оба глагола в Present Simple.' },
{ g:'Условия', r5:true, tag:['cond'], type:'choose',
  q:'I wish this flat ___ a balcony.',
  options:['has','had','would have'], answer:1,
  ru:'вот бы в этой квартире был балкон',
  why:'I wish про настоящее → шаг назад по времени: wish it had.' },
{ g:'Условия', r5:true, tag:['cond'], type:'choose',
  q:'She wouldn’t have missed the train if she ___ earlier.',
  options:['left','had left','would leave'], answer:1,
  ru:'она бы не опоздала на поезд, если бы вышла раньше',
  why:'третий тип: в условии had left, в результате wouldn’t have missed.' },
{ g:'Условия', r5:true, tag:['cond'], type:'gap',
  q:'You won’t pass ___ you work harder. (unless/if/when)', answer:['unless'],
  ru:'ты не сдашь, если не возьмёшься всерьёз',
  why:'unless = if not. Отрицание уже внутри слова.' },
{ g:'Условия', r5:true, tag:['cond'], type:'error',
  q:'Unless you don’t hurry, we will be late.',
  tokens:['Unless','you','don’t','hurry,','we','will','be','late'], answer:2, fix:'—',
  ru:'если не поторопишься, опоздаем',
  why:'unless уже значит «если не». Второе отрицание переворачивает смысл.' },
{ g:'Условия', r5:true, tag:['cond'], type:'order',
  ru:'если бы я знал, я бы тебе сказал',
  tokens:['If','I','knew,','I','would','tell','you'],
  answer:'If I knew, I would tell you',
  why:'второй тип: условие в Past Simple, результат с would.' },
{ g:'Условия', r5:true, tag:['cond'], type:'choose',
  q:'I wish I ___ that email yesterday.',
  options:['didn’t send','hadn’t sent','wouldn’t send'], answer:1,
  ru:'зря я отправил то письмо вчера',
  why:'сожаление о прошлом → wish + had (not) + V3.' },
{ g:'Условия', r5:true, tag:['cond'], type:'choose',
  q:'If you ___ the instructions, nothing bad happens.',
  options:['follow','will follow','would follow'], answer:0,
  ru:'если следовать инструкции, ничего плохого не случится',
  why:'общее правило, всегда верное → нулевой тип, оба в Present.' },
{ g:'Условия', r5:true, tag:['cond'], type:'pick',
  q:'Отметь ВСЕ верно собранные условные.',
  options:[
    'If it rains, we will cancel the trip.',
    'If it will rain, we cancel the trip.',
    'If I were rich, I would travel more.',
    'If I would be rich, I would travel more.'],
  answers:[0,2], ru:'',
  why:'will и would в самом условии не ставят — только в результате.' },
{ g:'Условия', r5:true, tag:['cond'], type:'form',
  q:'If they ___ (not, book) early, they wouldn’t have got the seats.',
  answer:['hadn’t booked','had not booked'],
  ru:'если бы они не забронировали заранее, мест бы не досталось',
  why:'третий тип, отрицание в условии: hadn’t booked.' },
{ g:'Условия', r5:true, tag:['cond'], type:'choose',
  q:'What would you do if you ___ your job?',
  options:['lose','lost','would lose'], answer:1,
  ru:'что бы ты делал, если бы потерял работу?',
  why:'гипотеза про сейчас → второй тип: if you lost.' },
{ g:'Условия', r5:true, tag:['cond'], type:'choose',
  q:'___ you need any help, just let me know.',
  options:['Should','Would','Will'], answer:0,
  ru:'если понадобится помощь — скажи',
  why:'Should you need = if you need. Инверсия вместо if — вежливее и формальнее, годится для письма.' },

/* ============================================================
   -ING ИЛИ TO (tag:ger) — что идёт после глагола. Списком это
   не учится, поэтому половина вопросов — пары, где смысл
   меняется от формы: stop doing ≠ stop to do.
   ============================================================ */
{ g:'Инфинитив', r5:true, tag:['ger'], type:'choose',
  q:'She enjoys ___ in the mountains.',
  options:['to hike','hiking','hike'], answer:1,
  ru:'она любит ходить в горы',
  why:'enjoy + -ing, всегда.' },
{ g:'Инфинитив', r5:true, tag:['ger'], type:'choose',
  q:'We decided ___ the meeting.',
  options:['postponing','to postpone','postpone'], answer:1,
  ru:'мы решили перенести встречу',
  why:'decide + to + глагол.' },
{ g:'Инфинитив', r5:true, tag:['ger'], type:'choose',
  q:'I stopped ___ coffee after six — I couldn’t sleep.',
  options:['drinking','to drink','drink'], answer:0,
  ru:'я перестал пить кофе после шести',
  why:'stop doing = бросил это занятие.' },
{ g:'Инфинитив', r5:true, tag:['ger'], type:'choose',
  q:'On the way home he stopped ___ some bread.',
  options:['buying','to buy','buy'], answer:1,
  ru:'по дороге домой он остановился купить хлеба',
  why:'stop to do = остановился, ЧТОБЫ сделать. Та же пара, что выше, но смысл другой.' },
{ g:'Инфинитив', r5:true, tag:['ger'], type:'error',
  q:'I look forward to meet you.',
  tokens:['I','look','forward','to','meet','you'], answer:4, fix:'meeting',
  ru:'жду встречи',
  why:'в look forward TO это предлог, а не частица инфинитива → to meeting.' },
{ g:'Инфинитив', r5:true, tag:['ger'], type:'choose',
  q:'He avoided ___ the question.',
  options:['to answer','answering','answer'], answer:1,
  ru:'он ушёл от ответа',
  why:'avoid + -ing.' },
{ g:'Инфинитив', r5:true, tag:['ger'], type:'gap',
  q:'Would you mind ___ the window? (open)', answer:['opening'],
  ru:'не откроешь окно?',
  why:'mind + -ing. Вежливая просьба строится именно так.' },
{ g:'Инфинитив', r5:true, tag:['ger'], type:'choose',
  q:'She made me ___ it twice.',
  options:['to check','check','checking'], answer:1,
  ru:'она заставила меня проверить дважды',
  why:'make / let + человек + чистый глагол, без to.' },
{ g:'Инфинитив', r5:true, tag:['ger'], type:'choose',
  q:'They allowed us ___ early.',
  options:['leave','to leave','leaving'], answer:1,
  ru:'нам разрешили уйти пораньше',
  why:'allow somebody TO do. Сравни с let somebody do — там to нет.' },
{ g:'Инфинитив', r5:true, tag:['ger'], type:'choose',
  q:'I remember ___ the door — I’m sure I did.',
  options:['to lock','locking','lock'], answer:1,
  ru:'я помню, что закрыл дверь',
  why:'remember doing = помню то, что уже сделал.' },
{ g:'Инфинитив', r5:true, tag:['ger'], type:'choose',
  q:'Remember ___ the door when you leave.',
  options:['to lock','locking','lock'], answer:0,
  ru:'не забудь закрыть дверь, когда будешь уходить',
  why:'remember to do = не забыть сделать. Пара к предыдущему вопросу.' },
{ g:'Инфинитив', r5:true, tag:['ger'], type:'error',
  q:'It’s worth to read this article.',
  tokens:['It’s','worth','to','read','this','article'], answer:2, fix:'—', altfix:'reading',
  ru:'эту статью стоит прочитать',
  why:'worth + -ing: it’s worth reading. Инфинитива после worth не бывает.' },
{ g:'Инфинитив', r5:true, tag:['ger'], type:'choose',
  q:'I’m used to ___ up early.',
  options:['get','getting','got'], answer:1,
  ru:'я привык вставать рано',
  why:'be used TO + -ing («привык»). Не путать с used to do — «раньше делал».' },
{ g:'Инфинитив', r5:true, tag:['ger'], type:'pick',
  q:'Отметь ВСЕ глаголы, после которых идёт форма на -ing.',
  options:['suggest','decide','avoid','promise','keep'],
  answers:[0,2,4], ru:'',
  why:'decide и promise берут to + глагол. suggest / avoid / keep — только -ing.' },
{ g:'Инфинитив', r5:true, tag:['ger'], type:'order',
  ru:'она предложила встретиться в пятницу',
  tokens:['She','suggested','meeting','on','Friday'],
  answer:'She suggested meeting on Friday',
  why:'suggest + -ing. Вариант «suggested to meet» — самая частая ошибка в этой зоне.' },
{ g:'Инфинитив', r5:true, tag:['ger'], type:'choose',
  q:'He managed ___ the deadline.',
  options:['meeting','to meet','meet'], answer:1,
  ru:'он успел к дедлайну',
  why:'manage + to do — «сумел, справился».' },

/* ============================================================
   ПАССИВ (tag:passive) — половина академического письма.
   ============================================================ */
{ g:'Пассив', r5:true, tag:['passive'], type:'choose',
  q:'The results ___ next week.',
  options:['will publish','will be published','will been published'], answer:1,
  ru:'результаты опубликуют на следующей неделе',
  why:'будущий пассив: will + be + V3.' },
{ g:'Пассив', r5:true, tag:['passive'], type:'form',
  q:'The library ___ (rebuild) after the fire.', answer:['was rebuilt'],
  ru:'библиотеку отстроили заново после пожара',
  why:'прошедший пассив: was + третья форма.' },
{ g:'Пассив', r5:true, tag:['passive'], type:'error',
  q:'This report was wrote by an intern.',
  tokens:['This','report','was','wrote','by','an','intern'], answer:3, fix:'written',
  ru:'этот отчёт написал стажёр',
  why:'в пассиве нужна третья форма (written), а не вторая (wrote).' },
{ g:'Пассив', r5:true, tag:['passive'], type:'choose',
  q:'The data ___ at the moment.',
  options:['is analysing','is being analysed','is analysed being'], answer:1,
  ru:'данные сейчас анализируют',
  why:'пассив в процессе: is being + V3.' },
{ g:'Пассив', r5:true, tag:['passive'], type:'mgap',
  q:'The letter ___ (already, send).',
  answer:[['has already been sent']],
  ru:'письмо уже отправлено',
  why:'Perfect в пассиве: has been + V3, already встаёт после has.' },
{ g:'Пассив', r5:true, tag:['passive'], type:'choose',
  q:'The room must ___ before Friday.',
  options:['be cleaned','clean','been cleaned'], answer:0,
  ru:'комнату надо убрать до пятницы',
  why:'после модального — be + V3.' },
{ g:'Пассив', r5:true, tag:['passive'], type:'order',
  ru:'нам сказали подождать',
  tokens:['We','were','told','to','wait'],
  answer:'We were told to wait',
  why:'человек становится подлежащим: we were told. Русское безличное «нам сказали» так и переводится.' },
{ g:'Пассив', r5:true, tag:['passive'], type:'choose',
  q:'English ___ in more than fifty countries.',
  options:['speaks','is spoken','is speaking'], answer:1,
  ru:'на английском говорят больше чем в пятидесяти странах',
  why:'исполнитель не важен → пассив: is spoken.' },
{ g:'Пассив', r5:true, tag:['passive'], type:'error',
  q:'The windows was cleaned yesterday.',
  tokens:['The','windows','was','cleaned','yesterday'], answer:2, fix:'were',
  ru:'окна помыли вчера',
  why:'подлежащее во множественном → were. Пассив согласуется как обычный глагол.' },
{ g:'Пассив', r5:true, tag:['passive'], type:'choose',
  q:'Что уместнее в отчёте?',
  options:['We measured the samples twice.','The samples were measured twice.','Somebody measured the samples twice.'],
  answer:1, ru:'',
  why:'в академическом тексте важен объект, а не исполнитель → пассив.' },
{ g:'Пассив', r5:true, tag:['passive'], type:'form',
  q:'Nothing ___ (do) about it so far.', answer:['has been done'],
  ru:'до сих пор ничего не сделано',
  why:'Present Perfect Passive: has been + V3.' },
{ g:'Пассив', r5:true, tag:['passive'], type:'choose',
  q:'The car ___ by my brother last month.',
  options:['sold','was sold','was selling'], answer:1,
  ru:'машину продал мой брат в прошлом месяце',
  why:'машина не продаёт сама → пассив: was sold by.' },
{ g:'Пассив', r5:true, tag:['passive'], type:'mgap',
  q:'The building ___ (design) by Foster and ___ (open) in 2004.',
  answer:[['was designed'],['was opened','opened']],
  ru:'здание спроектировал Фостер, открыли его в 2004-м',
  why:'два пассива подряд; во втором by не нужен — исполнитель не важен.' },
{ g:'Пассив', r5:true, tag:['passive'], type:'pick',
  q:'Отметь ВСЕ верные пассивные предложения.',
  options:['It was happened yesterday.','The road is being repaired.','He was given a prize.','The prize was gave to him.'],
  answers:[1,2], ru:'',
  why:'happen пассива не имеет вовсе. В четвёртом нужна третья форма: was given.' },

/* ============================================================
   КОСВЕННАЯ РЕЧЬ (tag:reported) — сдвиг времён и порядок слов
   в косвенном вопросе: то, на чём чаще всего рассыпается пересказ.
   ============================================================ */
{ g:'Речь', r5:true, tag:['reported'], type:'choose',
  q:'She said she ___ tired.',
  options:['is','was','were'], answer:1,
  ru:'она сказала, что устала',
  why:'said в прошлом → всё придаточное отступает на шаг назад: is → was.' },
{ g:'Речь', r5:true, tag:['reported'], type:'choose',
  q:'He told ___ he would call back.',
  options:['to me','me','that me'], answer:1,
  ru:'он сказал мне, что перезвонит',
  why:'tell + кому, без предлога. Предлог нужен у say: say TO me.' },
{ g:'Речь', r5:true, tag:['reported'], type:'error',
  q:'She said me that the shop was closed.',
  tokens:['She','said','me','that','the','shop','was','closed'], answer:1, fix:'told',
  ru:'она сказала мне, что магазин закрыт',
  why:'say не берёт человека напрямую: либо told me, либо said to me.' },
{ g:'Речь', r5:true, tag:['reported'], type:'order',
  ru:'он спросил, где я живу',
  tokens:['He','asked','where','I','lived'],
  answer:'He asked where I lived',
  why:'в косвенном вопросе прямой порядок слов: where I lived, без do/did.' },
{ g:'Речь', r5:true, tag:['reported'], type:'choose',
  q:'She asked me ___ I had finished.',
  options:['that','if','what'], answer:1,
  ru:'она спросила, закончил ли я',
  why:'вопрос без вопросительного слова → if / whether.' },
{ g:'Речь', r5:true, tag:['reported'], type:'error',
  q:'He asked me where do I work.',
  tokens:['He','asked','me','where','do','I','work'], answer:4, fix:'—',
  ru:'он спросил, где я работаю',
  why:'в косвенном вопросе вспомогательный do исчезает: where I work.' },
{ g:'Речь', r5:true, tag:['reported'], type:'form',
  q:'«I will help you» → He said he ___ (help) me.', answer:['would help'],
  ru:'он сказал, что поможет',
  why:'will отступает на шаг назад и становится would.' },
{ g:'Речь', r5:true, tag:['reported'], type:'choose',
  q:'Tom said he ___ the film the day before.',
  options:['saw','had seen','has seen'], answer:1,
  ru:'Том сказал, что смотрел этот фильм накануне',
  why:'Past Simple в прямой речи → Past Perfect в косвенной.' },
{ g:'Речь', r5:true, tag:['reported'], type:'choose',
  q:'She told me ___ worry.',
  options:['don’t','not to','to not'], answer:1,
  ru:'она сказала мне не волноваться',
  why:'просьба в отрицании → told me NOT TO + глагол.' },
{ g:'Речь', r5:true, tag:['reported'], type:'choose',
  q:'«I saw her yesterday» в косвенной речи — это…',
  options:['He said he saw her yesterday.','He said he had seen her the day before.','He said he has seen her yesterday.'],
  answer:1, ru:'',
  why:'сдвигается и время (saw → had seen), и слово-указатель (yesterday → the day before).' },
{ g:'Речь', r5:true, tag:['reported'], type:'pick',
  q:'Отметь ВСЕ верные варианты.',
  options:['She said that she was late.','She told that she was late.','She told me that she was late.','She said me that she was late.'],
  answers:[0,2], ru:'',
  why:'tell требует адресата, say — наоборот, не берёт его без to.' },
{ g:'Речь', r5:true, tag:['reported'], type:'gap',
  q:'He suggested ___ we meet on Monday. (that/to/if)', answer:['that'],
  ru:'он предложил встретиться в понедельник',
  why:'suggest that + мы + глагол. Suggest us to meet — калька, так не говорят.' },

/* ============================================================
   МОДАЛЬНЫЕ (tag:modal) — догадки и степень уверенности.
   ============================================================ */
{ g:'Модальные', r5:true, tag:['modal'], type:'choose',
  q:'You ___ be joking!',
  options:['must','can','should'], answer:0,
  ru:'да ты шутишь!',
  why:'must — уверенная догадка «наверняка так и есть».' },
{ g:'Модальные', r5:true, tag:['modal'], type:'choose',
  q:'She ___ be at home — her car isn’t there.',
  options:['must','can’t','mustn’t'], answer:1,
  ru:'её точно нет дома — машины нет',
  why:'уверенное отрицание догадки → can’t be. mustn’t значит «запрещено».' },
{ g:'Модальные', r5:true, tag:['modal'], type:'choose',
  q:'You ___ come with us if you’re tired — we’ll manage.',
  options:['mustn’t','don’t have to','can’t'], answer:1,
  ru:'можешь не ехать с нами, если устал — справимся',
  why:'don’t have to = не обязан. mustn’t значило бы «нельзя», и смысл переворачивается.' },
{ g:'Модальные', r5:true, tag:['modal'], type:'error',
  q:'You must not to smoke here.',
  tokens:['You','must','not','to','smoke','here'], answer:3, fix:'—',
  ru:'здесь нельзя курить',
  why:'после модального идёт чистый глагол, без to.' },
{ g:'Модальные', r5:true, tag:['modal'], type:'choose',
  q:'He ___ have missed the train — he left an hour ago.',
  options:['must','can’t','should'], answer:1,
  ru:'он никак не мог опоздать на поезд — вышел час назад',
  why:'уверенность, что этого НЕ было → can’t have + V3.' },
{ g:'Модальные', r5:true, tag:['modal'], type:'choose',
  q:'I ___ have called her, but I forgot.',
  options:['should','must','could have been'], answer:0,
  ru:'надо было ей позвонить, но я забыл',
  why:'упрёк себе за прошлое → should have + V3.' },
{ g:'Модальные', r5:true, tag:['modal'], type:'choose',
  q:'They ___ have arrived by now — the flight landed at six.',
  options:['should','must not','can'], answer:0,
  ru:'они уже должны были долететь — самолёт сел в шесть',
  why:'ожидание по расчёту → should have + V3.' },
{ g:'Модальные', r5:true, tag:['modal'], type:'order',
  ru:'тебе не нужно было платить',
  tokens:['You','didn’t','have','to','pay'],
  answer:'You didn’t have to pay',
  why:'прошедшее от don’t have to. У must прошедшего нет вовсе.' },
{ g:'Модальные', r5:true, tag:['modal'], type:'choose',
  q:'«Он, наверное, забыл» — это…',
  options:['He must forget.','He must have forgotten.','He should forget.'],
  answer:1, ru:'',
  why:'догадка о прошлом → must have + V3.' },
{ g:'Модальные', r5:true, tag:['modal'], type:'gap',
  q:'When I was a child, I ___ swim very well. (can/could/must)', answer:['could'],
  ru:'в детстве я хорошо плавал',
  why:'умение в прошлом → could.' },
{ g:'Модальные', r5:true, tag:['modal'], type:'choose',
  q:'You ___ touch that — it’s dangerous.',
  options:['mustn’t','don’t have to','needn’t'], answer:0,
  ru:'не трогай — это опасно',
  why:'запрет → mustn’t. Остальные два значат «не обязательно».' },
{ g:'Модальные', r5:true, tag:['modal'], type:'pick',
  q:'Отметь ВСЕ верные догадки о прошлом.',
  options:['She might have left already.','She must have leave already.','She can’t have seen us.','She can’t saw us.'],
  answers:[0,2], ru:'',
  why:'формула одна: модальный + have + третья форма. leave и saw в неё не встают.' },
{ g:'Модальные', r5:true, tag:['modal'], type:'choose',
  q:'We ___ to submit the form by Friday.',
  options:['must','have','should'], answer:1,
  ru:'мы должны сдать форму до пятницы',
  why:'перед to может стоять только have: have to submit. must to не бывает.' },
{ g:'Модальные', r5:true, tag:['modal'], type:'form',
  q:'He ___ (may, not, know) about the change yet.', answer:['may not know'],
  ru:'он, возможно, ещё не знает об изменении',
  why:'осторожная догадка: may not + чистый глагол.' },

/* ============================================================
   ПРИДАТОЧНЫЕ (tag:rel) — who/which/that и запятая, которая
   меняет смысл предложения, а не оформление.
   ============================================================ */
{ g:'Придаточные', r5:true, tag:['rel'], type:'choose',
  q:'The man ___ helped us was very kind.',
  options:['which','who','whom'], answer:1,
  ru:'человек, который нам помог, был очень добр',
  why:'про людей → who. which только про вещи.' },
{ g:'Придаточные', r5:true, tag:['rel'], type:'choose',
  q:'That’s the argument ___ convinced the committee.',
  options:['who','that','what'], answer:1,
  ru:'вот довод, который убедил комиссию',
  why:'про вещь → that или which. what в роли «который» не работает.' },
{ g:'Придаточные', r5:true, tag:['rel'], type:'error',
  q:'The woman which lives next door is a doctor.',
  tokens:['The','woman','which','lives','next','door','is','a','doctor'], answer:2, fix:'who',
  ru:'женщина, которая живёт по соседству, — врач',
  why:'человек → who.' },
{ g:'Придаточные', r5:true, tag:['rel'], type:'choose',
  q:'My brother, ___ lives in Kazan, is a teacher.',
  options:['that','who','which'], answer:1,
  ru:'мой брат, который живёт в Казани, — учитель',
  why:'после запятой that не ставят никогда.' },
{ g:'Придаточные', r5:true, tag:['rel'], type:'choose',
  q:'The house ___ roof is red belongs to them.',
  options:['which','whose','who’s'], answer:1,
  ru:'дом с красной крышей принадлежит им',
  why:'принадлежность → whose, и для вещей тоже. who’s — это who is.' },
{ g:'Придаточные', r5:true, tag:['rel'], type:'error',
  q:'The film that I told you about it was great.',
  tokens:['The','film','that','I','told','you','about','it','was','great'], answer:7, fix:'—',
  ru:'фильм, о котором я тебе рассказывал, был отличный',
  why:'that уже заменяет дополнение — второй раз называть его нельзя.' },
{ g:'Придаточные', r5:true, tag:['rel'], type:'choose',
  q:'That’s the café ___ we first met.',
  options:['which','where','that'], answer:1,
  ru:'вот кафе, где мы впервые встретились',
  why:'про место → where.' },
{ g:'Придаточные', r5:true, tag:['rel'], type:'pick',
  q:'Отметь ВСЕ предложения, где запятые стоят верно.',
  options:[
    'My car, which is ten years old, still works.',
    'The man, who called you, is my boss.',
    'Students who arrive late will not be admitted.',
    'The book, that I bought, was cheap.'],
  answers:[0,2], ru:'',
  why:'запятые ставят, только когда придаточное — попутное замечание. Если оно определяет, о ком речь, запятых нет.' },
{ g:'Придаточные', r5:true, tag:['rel'], type:'gap',
  q:'The report ___ was published in May is online. (which/what/who)', answer:['which'],
  ru:'отчёт, опубликованный в мае, есть в сети',
  why:'про вещь и без запятой → which или that.' },
{ g:'Придаточные', r5:true, tag:['rel'], type:'order',
  ru:'человек, с которым я говорил, очень помог',
  tokens:['The','person','I','spoke','to','was','very','helpful'],
  answer:'The person I spoke to was very helpful',
  why:'слово «который» можно опустить целиком, если оно дополнение. Предлог остаётся в конце.' },
{ g:'Придаточные', r5:true, tag:['rel'], type:'choose',
  q:'Everything ___ he says is true.',
  options:['that','what','which'], answer:0,
  ru:'всё, что он говорит, — правда',
  why:'после everything / all / nothing идёт that, а не what.' },
{ g:'Придаточные', r5:true, tag:['rel'], type:'choose',
  q:'The results, ___ were unexpected, changed the plan.',
  options:['that','which','who'], answer:1,
  ru:'результаты, которые оказались неожиданными, изменили план',
  why:'попутное замечание в запятых → только which.' },

/* ============================================================
   ВОПРОСЫ И СРАВНЕНИЯ (tag:struct2) — косвенный вопрос теряет
   do/did, сравнение не удваивает степень.
   ============================================================ */
{ g:'Структура+', r5:true, tag:['struct2'], type:'choose',
  q:'Could you tell me ___?',
  options:['where is the station','where the station is','where is station'], answer:1,
  ru:'подскажете, где вокзал?',
  why:'вежливый вопрос внутри вопроса → прямой порядок слов.' },
{ g:'Структура+', r5:true, tag:['struct2'], type:'error',
  q:'Do you know what time does the shop open?',
  tokens:['Do','you','know','what','time','does','the','shop','open'], answer:5, fix:'—',
  ru:'не знаешь, во сколько открывается магазин?',
  why:'во второй части вопроса does не нужен: what time the shop opens.' },
{ g:'Структура+', r5:true, tag:['struct2'], type:'choose',
  q:'It was ___ a boring lecture that I fell asleep.',
  options:['so','such','too'], answer:1,
  ru:'лекция была такая скучная, что я уснул',
  why:'such + существительное с прилагательным; so — только с прилагательным.' },
{ g:'Структура+', r5:true, tag:['struct2'], type:'choose',
  q:'The exam was ___ difficult that nobody finished.',
  options:['such','so','very'], answer:1,
  ru:'экзамен был настолько трудный, что никто не дописал',
  why:'so + прилагательное + that. Пара к предыдущему вопросу.' },
{ g:'Структура+', r5:true, tag:['struct2'], type:'choose',
  q:'This flat isn’t ___ for four people.',
  options:['enough big','big enough','too big enough'], answer:1,
  ru:'эта квартира маловата для четверых',
  why:'enough идёт ПОСЛЕ прилагательного: big enough.' },
{ g:'Структура+', r5:true, tag:['struct2'], type:'choose',
  q:'She runs ___ than her brother.',
  options:['more fast','faster','fastest'], answer:1,
  ru:'она бегает быстрее брата',
  why:'короткое слово → -er, без more.' },
{ g:'Структура+', r5:true, tag:['struct2'], type:'order',
  ru:'этот отчёт не такой подробный, как прошлый',
  tokens:['This','report','is','not','as','detailed','as','the','last','one'],
  answer:'This report is not as detailed as the last one',
  why:'равенство и его отрицание — конструкция as … as.' },
{ g:'Структура+', r5:true, tag:['struct2'], type:'error',
  q:'He is more taller than me.',
  tokens:['He','is','more','taller','than','me'], answer:2, fix:'—',
  ru:'он выше меня',
  why:'степень уже внутри taller. Удваивать её через more нельзя.' },
{ g:'Структура+', r5:true, tag:['struct2'], type:'choose',
  q:'The more you practise, ___.',
  options:['the better you get','you get better','better you get'], answer:0,
  ru:'чем больше практикуешься, тем лучше получается',
  why:'конструкция the more … the better — с артиклем в обеих половинах.' },
{ g:'Структура+', r5:true, tag:['struct2'], type:'gap',
  q:'It’s ___ expensive for us — we can’t afford it. (too/enough/so)', answer:['too'],
  ru:'для нас это слишком дорого',
  why:'too = слишком, с отрицательным оттенком. very просто усиливает.' },
{ g:'Структура+', r5:true, tag:['struct2'], type:'choose',
  q:'Какой косвенный вопрос собран верно?',
  options:['I wonder why did he leave.','I wonder why he left.','I wonder why has he left.'],
  answer:1, ru:'',
  why:'внутри — обычное предложение, без инверсии и без вспомогательного.' },
{ g:'Структура+', r5:true, tag:['struct2'], type:'pick',
  q:'Отметь ВСЕ верные сравнения.',
  options:['She is the most intelligent person I know.','This one is more cheaper.','It’s twice as expensive as before.','He is more older than me.'],
  answers:[0,2], ru:'',
  why:'more + cheaper и more + older — двойная степень, так нельзя.' },

/* ============================================================
   КОЛЛОКАЦИИ (tag:coll) — что с чем живёт. Правил нет, есть
   привычка, поэтому вопросы короткие и их много.
   ============================================================ */
{ g:'Лексика', r5:true, lex:true, tag:['coll'], type:'choose',
  q:'She ___ a mistake in the calculation.',
  options:['did','made','took'], answer:1,
  ru:'она ошиблась в расчёте',
  why:'make a mistake. do a mistake не существует.' },
{ g:'Лексика', r5:true, lex:true, tag:['coll'], type:'choose',
  q:'Could you ___ me a favour?',
  options:['do','make','give'], answer:0,
  ru:'сделаешь мне одолжение?',
  why:'do a favour — здесь как раз do, а не make.' },
{ g:'Лексика', r5:true, lex:true, tag:['coll'], type:'choose',
  q:'I need to ___ a decision by Friday.',
  options:['do','make','take'], answer:1,
  ru:'мне надо принять решение до пятницы',
  why:'make a decision. Русское «принять» тянет к take — и это ошибка.' },
{ g:'Лексика', r5:true, lex:true, tag:['coll'], type:'choose',
  q:'He ___ attention to the details.',
  options:['pays','makes','gives'], answer:0,
  ru:'он обращает внимание на детали',
  why:'pay attention — единственный верный глагол.' },
{ g:'Лексика', r5:true, lex:true, tag:['coll'], type:'gap',
  q:'They ___ research on air quality. (conduct/make/take)', answer:['conduct'],
  ru:'они ведут исследование качества воздуха',
  why:'conduct research — академическая пара, прямо для письма.' },
{ g:'Лексика', r5:true, lex:true, tag:['coll'], type:'error',
  q:'I have to make my homework tonight.',
  tokens:['I','have','to','make','my','homework','tonight'], answer:3, fix:'do',
  ru:'мне сегодня надо сделать домашку',
  why:'do homework / do the washing — рутина идёт с do. make — про создание чего-то нового.' },
{ g:'Лексика', r5:true, lex:true, tag:['coll'], type:'choose',
  q:'The company ___ a profit last year.',
  options:['did','made','took'], answer:1,
  ru:'в прошлом году компания вышла в прибыль',
  why:'make a profit / make money.' },
{ g:'Лексика', r5:true, lex:true, tag:['coll'], type:'pick',
  q:'Отметь ВСЕ верные сочетания.',
  options:['make progress','do a mistake','take a risk','pay a visit'],
  answers:[0,2,3], ru:'',
  why:'ошибку только make. Остальные три — устойчивые пары.' },
{ g:'Лексика', r5:true, lex:true, tag:['coll'], type:'choose',
  q:'She ___ a strong impression on the interviewer.',
  options:['did','made','gave'], answer:1,
  ru:'она произвела сильное впечатление на интервьюера',
  why:'make an impression.' },
{ g:'Лексика', r5:true, lex:true, tag:['coll'], type:'choose',
  q:'Let’s ___ a break for ten minutes.',
  options:['do','make','take'], answer:2,
  ru:'давай сделаем перерыв на десять минут',
  why:'take a break — и здесь «сделать» переводится через take.' },
{ g:'Лексика', r5:true, lex:true, tag:['coll'], type:'gap',
  q:'Please ___ into account the cost of delivery. (take/make/do)', answer:['take'],
  ru:'учтите, пожалуйста, стоимость доставки',
  why:'take into account — «принять во внимание», целиком.' },
{ g:'Лексика', r5:true, lex:true, tag:['coll'], type:'choose',
  q:'He ___ a risk and it paid off.',
  options:['made','took','did'], answer:1,
  ru:'он рискнул, и это сработало',
  why:'take a risk.' },
{ g:'Лексика', r5:true, lex:true, tag:['coll'], type:'error',
  q:'The study makes an important role in the debate.',
  tokens:['The','study','makes','an','important','role','in','the','debate'], answer:2, fix:'plays',
  ru:'это исследование играет важную роль в дискуссии',
  why:'play a role — «играть роль», как и по-русски.' },
{ g:'Лексика', r5:true, lex:true, tag:['coll'], type:'choose',
  q:'They ___ the experiment three times.',
  options:['carried out','made out','took out'], answer:0,
  ru:'они провели эксперимент трижды',
  why:'carry out an experiment / a study — формальная пара для отчётов.' },

/* ============================================================
   ФРАЗОВЫЕ ГЛАГОЛЫ (tag:phrasal) — то, чем живая речь отличается
   от учебной. Берём те, что реально встретятся в тексте и письме.
   ============================================================ */
{ g:'Фразовые', r5:true, lex:true, tag:['phrasal'], type:'choose',
  q:'We had to ___ the meeting until Monday.',
  options:['put off','put on','put up'], answer:0,
  ru:'нам пришлось перенести встречу на понедельник',
  why:'put off = отложить.' },
{ g:'Фразовые', r5:true, lex:true, tag:['phrasal'], type:'choose',
  q:'The police are ___ the case.',
  options:['looking into','looking after','looking for'], answer:0,
  ru:'полиция изучает дело',
  why:'look into = разбираться, расследовать. look after — присматривать, look for — искать.' },
{ g:'Фразовые', r5:true, lex:true, tag:['phrasal'], type:'choose',
  q:'She ___ a great idea during the discussion.',
  options:['came up with','came across','came into'], answer:0,
  ru:'она придумала отличную идею в ходе обсуждения',
  why:'come up with = придумать. come across = наткнуться.' },
{ g:'Фразовые', r5:true, lex:true, tag:['phrasal'], type:'gap',
  q:'I ___ across an old photo yesterday. (came/went/put)', answer:['came'],
  ru:'вчера я наткнулся на старое фото',
  why:'come across = случайно найти.' },
{ g:'Фразовые', r5:true, lex:true, tag:['phrasal'], type:'choose',
  q:'Please ___ the form and hand it in.',
  options:['fill in','fill up','fill down'], answer:0,
  ru:'заполните бланк и сдайте',
  why:'fill in / fill out a form. fill up — про бак бензина.' },
{ g:'Фразовые', r5:true, lex:true, tag:['phrasal'], type:'choose',
  q:'He ___ smoking two years ago.',
  options:['gave up','gave in','gave away'], answer:0,
  ru:'он бросил курить два года назад',
  why:'give up = бросить привычку. Дальше -ing: give up smoking.' },
{ g:'Фразовые', r5:true, lex:true, tag:['phrasal'], type:'error',
  q:'I need to look after for my sister tonight.',
  tokens:['I','need','to','look','after','for','my','sister','tonight'], answer:5, fix:'—',
  ru:'мне сегодня вечером сидеть с сестрой',
  why:'look after уже полный: look after somebody. Второй предлог лишний.' },
{ g:'Фразовые', r5:true, lex:true, tag:['phrasal'], type:'pick',
  q:'Отметь ВСЕ фразовые со значением «отложить или отменить».',
  options:['put off','call off','set up','turn down'],
  answers:[0,1], ru:'',
  why:'set up = наладить, создать. turn down = отклонить или убавить.' },
{ g:'Фразовые', r5:true, lex:true, tag:['phrasal'], type:'choose',
  q:'They ___ his application because he applied too late.',
  options:['turned down','turned up','turned into'], answer:0,
  ru:'его заявку отклонили — подал слишком поздно',
  why:'turn down = отказать, отклонить.' },
{ g:'Фразовые', r5:true, lex:true, tag:['phrasal'], type:'choose',
  q:'The match was ___ because of the storm.',
  options:['called off','called on','called up'], answer:0,
  ru:'матч отменили из-за шторма',
  why:'call off = отменить совсем (а put off — только перенести).' },
{ g:'Фразовые', r5:true, lex:true, tag:['phrasal'], type:'choose',
  q:'We need to ___ a new system next year.',
  options:['set up','set off','set in'], answer:0,
  ru:'в следующем году надо развернуть новую систему',
  why:'set up = наладить, запустить.' },
{ g:'Фразовые', r5:true, lex:true, tag:['phrasal'], type:'gap',
  q:'Sales went ___ by 15% after the campaign. (up/on/over)', answer:['up'],
  ru:'после кампании продажи выросли на 15%',
  why:'go up / go down — самый простой способ описать динамику.' },
{ g:'Фразовые', r5:true, lex:true, tag:['phrasal'], type:'choose',
  q:'He didn’t ___ well with his colleagues.',
  options:['get on','get up','get over'], answer:0,
  ru:'у него не складывались отношения с коллегами',
  why:'get on with somebody = ладить.' },
{ g:'Фразовые', r5:true, lex:true, tag:['phrasal'], type:'error',
  q:'She is looking forward the trip.',
  tokens:['She','is','looking','forward','the','trip'], answer:3, fix:'forward to',
  ru:'она ждёт поездку с нетерпением',
  why:'look forward TO — предлог обязателен, и дальше идёт -ing или существительное.' },

/* ============================================================
   СЛОВООБРАЗОВАНИЕ (tag:wform) — одно слово в четырёх формах.
   На письме это половина «богатства языка» по критериям IELTS.
   ============================================================ */
{ g:'Словообразование', r5:true, lex:true, tag:['wform'], type:'gap',
  q:'We need to ___ the results carefully. (analysis → глагол)', answer:['analyse','analyze'],
  ru:'нам нужно внимательно проанализировать результаты',
  why:'analysis — существительное, analyse — глагол.' },
{ g:'Словообразование', r5:true, lex:true, tag:['wform'], type:'gap',
  q:'The ___ of the results took two weeks. (analyse → существительное)', answer:['analysis'],
  ru:'анализ результатов занял две недели',
  why:'пара к предыдущему: здесь нужно существительное.' },
{ g:'Словообразование', r5:true, lex:true, tag:['wform'], type:'choose',
  q:'The film was ___. I was ___ after ten minutes.',
  options:['boring / bored','bored / boring','boring / boring'], answer:0,
  ru:'фильм был скучный, и через десять минут мне стало скучно',
  why:'-ing описывает вещь, -ed — человека. Interesting film ↔ interested person.' },
{ g:'Словообразование', r5:true, lex:true, tag:['wform'], type:'choose',
  q:'This is an ___ decision for the whole team.',
  options:['importance','important','importantly'], answer:1,
  ru:'это важное решение для всей команды',
  why:'перед существительным нужно прилагательное.' },
{ g:'Словообразование', r5:true, lex:true, tag:['wform'], type:'gap',
  q:'She spoke very ___ about the plan. (confident → наречие)', answer:['confidently'],
  ru:'она говорила о плане очень уверенно',
  why:'как именно говорила → наречие на -ly.' },
{ g:'Словообразование', r5:true, lex:true, tag:['wform'], type:'choose',
  q:'The country faces serious ___ problems.',
  options:['economic','economical','economy'], answer:0,
  ru:'у страны серьёзные экономические проблемы',
  why:'economic = про экономику.' },
{ g:'Словообразование', r5:true, lex:true, tag:['wform'], type:'choose',
  q:'A small car is more ___ than an SUV.',
  options:['economic','economical','economy'], answer:1,
  ru:'маленькая машина экономичнее внедорожника',
  why:'economical = экономный, выгодный. Пара к предыдущему вопросу.' },
{ g:'Словообразование', r5:true, lex:true, tag:['wform'], type:'gap',
  q:'Air ___ has risen sharply in big cities. (pollute → существительное)', answer:['pollution'],
  ru:'загрязнение воздуха в больших городах резко выросло',
  why:'-tion — самый частый способ сделать существительное из глагола.' },
{ g:'Словообразование', r5:true, lex:true, tag:['wform'], type:'pick',
  q:'Отметь ВСЕ верные пары «глагол → существительное».',
  options:['decide → decision','succeed → success','argue → arguement','apply → application'],
  answers:[0,1,3], ru:'',
  why:'argument пишется без e после u — классическая опечатка на письме.' },
{ g:'Словообразование', r5:true, lex:true, tag:['wform'], type:'choose',
  q:'The results were ___ surprising.',
  options:['high','highly','height'], answer:1,
  ru:'результаты оказались крайне неожиданными',
  why:'усиление прилагательного → наречие highly.' },
{ g:'Словообразование', r5:true, lex:true, tag:['wform'], type:'gap',
  q:'He gave a very ___ answer. (use → прилагательное)', answer:['useful'],
  ru:'он дал очень полезный ответ',
  why:'-ful делает прилагательное: useful, helpful, powerful.' },
{ g:'Словообразование', r5:true, lex:true, tag:['wform'], type:'error',
  q:'She works very hardly.',
  tokens:['She','works','very','hardly'], answer:3, fix:'hard',
  ru:'она много работает',
  why:'hard уже наречие. hardly значит «едва» — смысл переворачивается.' },

/* ============================================================
   ПОХОЖИЕ СЛОВА (tag:confuse) — пары, которые путаются
   не от незнания, а от скорости.
   ============================================================ */
{ g:'Путаницы', r5:true, lex:true, tag:['confuse'], type:'choose',
  q:'The weather can ___ your mood.',
  options:['affect','effect','affection'], answer:0,
  ru:'погода может влиять на настроение',
  why:'affect — глагол «влиять».' },
{ g:'Путаницы', r5:true, lex:true, tag:['confuse'], type:'choose',
  q:'The new law had a positive ___ on small businesses.',
  options:['affect','effect','affects'], answer:1,
  ru:'новый закон положительно сказался на малом бизнесе',
  why:'effect — существительное «эффект». Пара к предыдущему.' },
{ g:'Путаницы', r5:true, lex:true, tag:['confuse'], type:'choose',
  q:'Can you ___ me your charger?',
  options:['borrow','lend','rent'], answer:1,
  ru:'одолжишь мне зарядку?',
  why:'lend = дать в долг. borrow = взять.' },
{ g:'Путаницы', r5:true, lex:true, tag:['confuse'], type:'choose',
  q:'I need to ___ a book from the library.',
  options:['borrow','lend','loan out'], answer:0,
  ru:'мне нужно взять книгу в библиотеке',
  why:'borrow FROM. Пара к предыдущему вопросу.' },
{ g:'Путаницы', r5:true, lex:true, tag:['confuse'], type:'error',
  q:'He told that he was busy.',
  tokens:['He','told','that','he','was','busy'], answer:1, fix:'said',
  ru:'он сказал, что занят',
  why:'tell требует адресата: told me that… Без него — said.' },
{ g:'Путаницы', r5:true, lex:true, tag:['confuse'], type:'choose',
  q:'Prices ___ by 5% last quarter.',
  options:['raised','rose','arose'], answer:1,
  ru:'цены выросли на 5% за квартал',
  why:'rise — сам растёт, без объекта.' },
{ g:'Путаницы', r5:true, lex:true, tag:['confuse'], type:'choose',
  q:'The company ___ prices by 5%.',
  options:['rose','raised','arisen'], answer:1,
  ru:'компания подняла цены на 5%',
  why:'raise — поднимает кто-то что-то. Пара к предыдущему.' },
{ g:'Путаницы', r5:true, lex:true, tag:['confuse'], type:'choose',
  q:'This job doesn’t ___ me — the hours are wrong.',
  options:['suit','fit','match'], answer:0,
  ru:'эта работа мне не подходит — неудобные часы',
  why:'suit = подходит по сути, по обстоятельствам.' },
{ g:'Путаницы', r5:true, lex:true, tag:['confuse'], type:'choose',
  q:'These shoes don’t ___ me — they’re too small.',
  options:['suit','fit','match'], answer:1,
  ru:'эти ботинки мне не подходят по размеру',
  why:'fit = подходит по размеру. Пара к предыдущему.' },
{ g:'Путаницы', r5:true, lex:true, tag:['confuse'], type:'pick',
  q:'Отметь ВСЕ верные предложения.',
  options:['I’m used to work here.','I used to work here.','I’m used to working here.','I use to work here.'],
  answers:[1,2], ru:'',
  why:'used to do = раньше делал. be used to doing = привык. Третьего варианта нет.' },
{ g:'Путаницы', r5:true, lex:true, tag:['confuse'], type:'choose',
  q:'The number of students ___ growing every year.',
  options:['are','is','were'], answer:1,
  ru:'число студентов растёт с каждым годом',
  why:'подлежащее — number, оно в единственном. А «a number of students ARE» — уже множественное.' },
{ g:'Путаницы', r5:true, lex:true, tag:['confuse'], type:'gap',
  q:'Please ___ me know if anything changes. (let/leave)', answer:['let'],
  ru:'дай знать, если что-то изменится',
  why:'let somebody know — устойчивое. leave = оставить.' },
{ g:'Путаницы', r5:true, lex:true, tag:['confuse'], type:'choose',
  q:'He ___ his keys at home.',
  options:['forgot','left','lost'], answer:1,
  ru:'он оставил ключи дома',
  why:'если названо место — только left. forget место не берёт.' },
{ g:'Путаницы', r5:true, lex:true, tag:['confuse'], type:'error',
  q:'The advice you gave me were very helpful.',
  tokens:['The','advice','you','gave','me','were','very','helpful'], answer:5, fix:'was',
  ru:'твой совет очень помог',
  why:'advice неисчисляемое → глагол в единственном: was.' },

/* ============================================================
   AWL · ЯДРО ДЛЯ ЭССЕ (tag:awl) — слова, которые проверяющий
   ждёт увидеть, и слова, которые выдают разговорный регистр.
   ============================================================ */
{ g:'Академика', r5:true, lex:true, tag:['awl'], type:'choose',
  q:'The study provides strong ___ for this claim.',
  options:['evidence','evidences','proofs'], answer:0,
  ru:'исследование даёт весомые основания для этого утверждения',
  why:'evidence неисчисляемое — формы evidences нет.' },
{ g:'Академика', r5:true, lex:true, tag:['awl'], type:'gap',
  q:'There is ___ evidence to support the theory. (sufficient/efficient)', answer:['sufficient'],
  ru:'свидетельств достаточно, чтобы поддержать теорию',
  why:'sufficient = достаточный. efficient = эффективный, про способ работы.' },
{ g:'Академика', r5:true, lex:true, tag:['awl'], type:'choose',
  q:'A more flexible ___ would solve the problem.',
  options:['approach','approaching','approached'], answer:0,
  ru:'более гибкий подход решил бы проблему',
  why:'approach как существительное — «подход», рабочая лошадка эссе.' },
{ g:'Академика', r5:true, lex:true, tag:['awl'], type:'choose',
  q:'The difference was ___ — under one per cent.',
  options:['significant','negligible','considerable'], answer:1,
  ru:'разница была ничтожной — меньше процента',
  why:'negligible = пренебрежимо малый. Два других значат «существенный».' },
{ g:'Академика', r5:true, lex:true, tag:['awl'], type:'choose',
  q:'Researchers ___ a survey of 400 students.',
  options:['made','conducted','did'], answer:1,
  ru:'исследователи провели опрос четырёхсот студентов',
  why:'conduct a survey / conduct research — формальная пара.' },
{ g:'Академика', r5:true, lex:true, tag:['awl'], type:'choose',
  q:'These factors ___ to the final result.',
  options:['contribute','consist','construct'], answer:0,
  ru:'эти факторы влияют на итоговый результат',
  why:'contribute TO — «вносить вклад».' },
{ g:'Академика', r5:true, lex:true, tag:['awl'], type:'pick',
  q:'Отметь ВСЕ слова, уместные в академическом эссе.',
  options:['a lot of','numerous','loads of','considerable'],
  answers:[1,3], ru:'',
  why:'a lot of и loads of — разговорные. В письме: numerous, considerable, a significant number of.' },
{ g:'Академика', r5:true, lex:true, tag:['awl'], type:'gap',
  q:'The findings ___ that the method works. (suggest/tell)', answer:['suggest'],
  ru:'результаты позволяют предположить, что метод работает',
  why:'suggest / indicate — осторожный вывод. Так формулируют, когда доказательство неполное.' },
{ g:'Академика', r5:true, lex:true, tag:['awl'], type:'choose',
  q:'The policy had a ___ impact on rural areas.',
  options:['big','substantial','huge'], answer:1,
  ru:'политика заметно повлияла на сельские районы',
  why:'substantial — формальный синоним к big.' },
{ g:'Академика', r5:true, lex:true, tag:['awl'], type:'choose',
  q:'This approach is ___ used in modern research.',
  options:['wide','widely','width'], answer:1,
  ru:'этот подход широко применяется в современных исследованиях',
  why:'как используется → наречие widely.' },
{ g:'Академика', r5:true, lex:true, tag:['awl'], type:'gap',
  q:'The two groups differ ___ in their results. (significant → наречие)', answer:['significantly'],
  ru:'две группы существенно расходятся в результатах',
  why:'differ significantly — почти штамп в академическом тексте, и это хорошо.' },
{ g:'Академика', r5:true, lex:true, tag:['awl'], type:'choose',
  q:'The report ___ three main factors.',
  options:['identifies','identical','identity'], answer:0,
  ru:'в отчёте выделены три основных фактора',
  why:'identify = выделять, определять. Нужен глагол.' },

/* ============================================================
   ГРАММАТИКА ДЛЯ ПИСЬМА (tag:wgram) — конструкции, которые
   отличают эссе на 6.5 от эссе на 5.5.
   ============================================================ */
{ g:'Регистр', r5:true, tag:['wgram'], type:'choose',
  q:'Что уместнее в академическом тексте?',
  options:['The results didn’t show any change.','The results showed no change.','The results don’t show nothing.'],
  answer:1, ru:'',
  why:'no + существительное вместо not any — короче и формальнее.' },
{ g:'Регистр', r5:true, tag:['wgram'], type:'choose',
  q:'Not only ___ the cost high, but the quality was poor.',
  options:['was','it was','the cost was'], answer:0,
  ru:'мало того что дорого — ещё и качество плохое',
  why:'после not only в начале предложения — инверсия: not only was the cost…' },
{ g:'Регистр', r5:true, tag:['wgram'], type:'order',
  ru:'без финансирования проект бы остановился',
  tokens:['Without','the','funding,','the','project','would','have','stopped'],
  answer:'Without the funding, the project would have stopped',
  why:'without заменяет целое условие «если бы не» — экономит половину предложения.' },
{ g:'Регистр', r5:true, tag:['wgram'], type:'choose',
  q:'Having ___ the data, the team published the report.',
  options:['analysed','analysing','analyse'], answer:0,
  ru:'проанализировав данные, команда опубликовала отчёт',
  why:'сокращённое придаточное: Having + V3 = «сделав то-то раньше».' },
{ g:'Регистр', r5:true, tag:['wgram'], type:'error',
  q:'Despite of the cost, the plan went ahead.',
  tokens:['Despite','of','the','cost,','the','plan','went','ahead'], answer:1, fix:'—',
  ru:'несмотря на стоимость, план запустили',
  why:'despite без of. In spite OF — с ним. Смешивать их нельзя.' },
{ g:'Регистр', r5:true, tag:['wgram'], type:'choose',
  q:'___ the weather was bad, the event took place.',
  options:['Despite','Although','However'], answer:1,
  ru:'хотя погода была плохая, мероприятие состоялось',
  why:'перед целым предложением → although. despite берёт только существительное.' },
{ g:'Регистр', r5:true, tag:['wgram'], type:'gap',
  q:'The problem is ___ complex to solve quickly. (too/very/so)', answer:['too'],
  ru:'задача слишком сложная, чтобы решить её быстро',
  why:'too + прилагательное + to + глагол — готовая конструкция для эссе.' },
{ g:'Регистр', r5:true, tag:['wgram'], type:'choose',
  q:'It is widely ___ that exercise improves memory.',
  options:['believe','believed','believing'], answer:1,
  ru:'широко признано, что спорт улучшает память',
  why:'безличный пассив it is believed / it is argued — способ сказать без «I think».' },
{ g:'Регистр', r5:true, tag:['wgram'], type:'choose',
  q:'Only after the reform ___ the numbers improve.',
  options:['did','was','has'], answer:0,
  ru:'только после реформы цифры пошли вверх',
  why:'only after в начале → инверсия с did.' },
{ g:'Регистр', r5:true, tag:['wgram'], type:'mgap',
  q:'If governments ___ (act) sooner, the crisis ___ (be) less severe.',
  answer:[['had acted'],['would have been']],
  ru:'если бы правительства действовали раньше, кризис был бы мягче',
  why:'третий тип условного — стандартный ход в аргументе про упущенное.' },

/* ============================================================
   АКАДЕМИЧЕСКАЯ ЛЕКСИКА ПИСЬМА (tag:wlex)
   ============================================================ */
{ g:'Академика', r5:true, lex:true, tag:['wlex'], type:'choose',
  q:'The essay ___ three possible solutions.',
  options:['tells','outlines','says'], answer:1,
  ru:'в эссе намечены три возможных решения',
  why:'outline = кратко изложить. tell и say так с текстом не работают.' },
{ g:'Академика', r5:true, lex:true, tag:['wlex'], type:'choose',
  q:'This argument is not supported by ___ data.',
  options:['reliable','reliably','rely'], answer:0,
  ru:'этот довод не подкреплён надёжными данными',
  why:'перед существительным → прилагательное reliable.' },
{ g:'Академика', r5:true, lex:true, tag:['wlex'], type:'gap',
  q:'The author ___ that education should be free. (argues/tells)', answer:['argues'],
  ru:'автор утверждает, что образование должно быть бесплатным',
  why:'argue that — как автор подаёт позицию. tell так не употребляется.' },
{ g:'Академика', r5:true, lex:true, tag:['wlex'], type:'choose',
  q:'Some people ___ that technology isolates us.',
  options:['claim','claim to','tell'], answer:0,
  ru:'некоторые считают, что технологии нас изолируют',
  why:'claim that — «утверждают», с оттенком «но это спорно».' },
{ g:'Академика', r5:true, lex:true, tag:['wlex'], type:'choose',
  q:'The government proposed a ___ solution to the housing crisis.',
  options:['viable','viably','viability'], answer:0,
  ru:'правительство предложило жизнеспособное решение жилищного кризиса',
  why:'viable = осуществимый. Перед существительным нужно прилагательное.' },
{ g:'Академика', r5:true, lex:true, tag:['wlex'], type:'pick',
  q:'Отметь ВСЕ связки, уместные в эссе.',
  options:['Moreover','And also','Furthermore','Plus'],
  answers:[0,2], ru:'',
  why:'And also и Plus — разговорные. В письме: moreover, furthermore, in addition.' },
{ g:'Академика', r5:true, lex:true, tag:['wlex'], type:'choose',
  q:'The government should ___ stricter regulations.',
  options:['do','implement','make up'], answer:1,
  ru:'государству следует ввести более строгие правила',
  why:'implement = внедрять, вводить в действие.' },
{ g:'Академика', r5:true, lex:true, tag:['wlex'], type:'gap',
  q:'The two approaches differ in ___ ways. (several/much)', answer:['several'],
  ru:'два подхода различаются в нескольких отношениях',
  why:'ways счётное → several. much только с неисчисляемым.' },
{ g:'Академика', r5:true, lex:true, tag:['wlex'], type:'choose',
  q:'This trend is likely to ___ in the coming decade.',
  options:['continue','continuous','continuously'], answer:0,
  ru:'эта тенденция, вероятно, продолжится в ближайшее десятилетие',
  why:'после to — глагол. Слово likely to — осторожный прогноз без «I think».' },
{ g:'Академика', r5:true, lex:true, tag:['wlex'], type:'choose',
  q:'The findings ___ earlier research.',
  options:['contradict','contradiction','contradictory'], answer:0,
  ru:'выводы противоречат более ранним исследованиям',
  why:'здесь нужен глагол: findings contradict.' },

/* ============================================================
   TASK 1 · ЯЗЫК ГРАФИКОВ (tag:task1)
   ============================================================ */
{ g:'Графики', r5:true, lex:true, tag:['task1'], type:'choose',
  q:'The number of visitors ___ sharply between 2010 and 2015.',
  options:['raised','rose','arisen'], answer:1,
  ru:'число посетителей резко выросло с 2010 по 2015 год',
  why:'rise — расти сам. raise — поднимать что-то.' },
{ g:'Графики', r5:true, lex:true, tag:['task1'], type:'choose',
  q:'Sales ___ at 40,000 units in June.',
  options:['peaked','topped up','climbed at'], answer:0,
  ru:'в июне продажи достигли пика в 40 000 штук',
  why:'peak AT + значение. Синоним: reached a peak of.' },
{ g:'Графики', r5:true, lex:true, tag:['task1'], type:'gap',
  q:'Exports fell ___ 20% to 8 million tonnes. (by/on/at)', answer:['by'],
  ru:'экспорт упал на 20% — до 8 миллионов тонн',
  why:'на сколько → by, до какой отметки → to. В одном предложении оба.' },
{ g:'Графики', r5:true, lex:true, tag:['task1'], type:'choose',
  q:'Coal ___ for 35% of total energy use.',
  options:['accounted','counted','made'], answer:0,
  ru:'на уголь приходилось 35% всего энергопотребления',
  why:'account for = составлять такую-то долю.' },
{ g:'Графики', r5:true, lex:true, tag:['task1'], type:'choose',
  q:'There was a ___ increase in prices.',
  options:['sharply','sharp','sharpen'], answer:1,
  ru:'произошёл резкий рост цен',
  why:'перед существительным increase → прилагательное sharp. С глаголом было бы rose sharply.' },
{ g:'Графики', r5:true, lex:true, tag:['task1'], type:'choose',
  q:'Prices rose ___ over the whole period.',
  options:['steady','steadily','steadiness'], answer:1,
  ru:'цены росли равномерно на протяжении всего периода',
  why:'при глаголе → наречие steadily. Пара к предыдущему вопросу.' },
{ g:'Графики', r5:true, lex:true, tag:['task1'], type:'error',
  q:'The amount of visitors doubled in 2019.',
  tokens:['The','amount','of','visitors','doubled','in','2019'], answer:1, fix:'number',
  ru:'число посетителей удвоилось в 2019 году',
  why:'visitors считаются штуками → the number of. amount — для неисчисляемого.' },
{ g:'Графики', r5:true, lex:true, tag:['task1'], type:'choose',
  q:'The figure remained ___ from March to July.',
  options:['stable','stably','stability'], answer:0,
  ru:'с марта по июль показатель не менялся',
  why:'после remain / stay идёт прилагательное: remained stable.' },
{ g:'Графики', r5:true, lex:true, tag:['task1'], type:'pick',
  q:'Отметь ВСЕ верные описания графика.',
  options:['Sales rose by 10%.','Sales rose of 10%.','Sales reached a peak of 40,000.','Sales peaked at 40,000.'],
  answers:[0,2,3], ru:'',
  why:'rise BY столько-то. Of здесь не работает, зато работает в «a peak of».' },
{ g:'Графики', r5:true, lex:true, tag:['task1'], type:'gap',
  q:'Overall, the chart shows a downward ___ in car use. (trend/tendency)', answer:['trend'],
  ru:'в целом график показывает нисходящую динамику использования машин',
  why:'a downward / upward trend — готовая фраза для вывода в Task 1.' },

/* ============================================================
   TASK 2 · ЯЗЫК АРГУМЕНТА (tag:task2)
   ============================================================ */
{ g:'Графики', r5:true, lex:true, tag:['task2'], type:'choose',
  q:'Какое начало эссе лучше?',
  options:['In my opinion I think that…','This essay will argue that…','I want to tell about…'],
  answer:1, ru:'',
  why:'«In my opinion I think» — удвоенное мнение. Позицию заявляют через будущее эссе.' },
{ g:'Графики', r5:true, lex:true, tag:['task2'], type:'choose',
  q:'Как осторожнее сказать «это вызывает преступность»?',
  options:['This causes crime.','This may contribute to crime.','This always causes crime.'],
  answer:1, ru:'',
  why:'hedging: may / tend to / contribute to. Категоричность на письме дорого стоит.' },
{ g:'Графики', r5:true, lex:true, tag:['task2'], type:'choose',
  q:'Какая связка вводит противопоставление?',
  options:['Moreover','Whereas','Therefore'], answer:1,
  ru:'',
  why:'whereas и while противопоставляют. moreover добавляет, therefore подводит итог.' },
{ g:'Графики', r5:true, lex:true, tag:['task2'], type:'gap',
  q:'To ___ up, the benefits outweigh the drawbacks. (sum/close)', answer:['sum'],
  ru:'подводя итог, плюсы перевешивают минусы',
  why:'to sum up — стандартная формула вывода.' },
{ g:'Графики', r5:true, lex:true, tag:['task2'], type:'pick',
  q:'Отметь ВСЕ фразы, которых в эссе быть не должно.',
  options:['I think it’s a big problem.','It can be argued that…','Lots of people say so.','This suggests that…'],
  answers:[0,2], ru:'',
  why:'разговорный регистр и ссылка в никуда. Формально: it can be argued, research suggests.' },
{ g:'Графики', r5:true, lex:true, tag:['task2'], type:'choose',
  q:'The benefits ___ the drawbacks.',
  options:['outweigh','overweight','outweight'], answer:0,
  ru:'плюсы перевешивают минусы',
  why:'outweigh — одно слово, пишется без t перед h.' },
{ g:'Графики', r5:true, lex:true, tag:['task2'], type:'choose',
  q:'В каком варианте пример настоящий?',
  options:['For example, many things happen.','For instance, Norway cut emissions by 30% in ten years.','For example, it is very important.'],
  answer:1, ru:'',
  why:'пример — это факт с цифрой или именем. Остальное только выглядит как пример.' },
{ g:'Графики', r5:true, lex:true, tag:['task2'], type:'choose',
  q:'Как закончить эссе без «I think»?',
  options:['In conclusion, I think it is good.','Overall, the evidence suggests that the benefits are greater.','So that is my opinion.'],
  answer:1, ru:'',
  why:'вывод строят на доказательстве, а не на себе: the evidence suggests.' },

/* ============================================================
   РЕГИСТР И СВЯЗНОСТЬ (tag:reg2)
   ============================================================ */
{ g:'Связки', r5:true, lex:true, tag:['reg2'], type:'choose',
  q:'The results were poor. ___, the project continued.',
  options:['However','But','Although'], answer:0,
  ru:'результаты были слабые. Тем не менее проект продолжили',
  why:'в начале нового предложения → however с запятой. But так обычно не ставят в письме.' },
{ g:'Связки', r5:true, lex:true, tag:['reg2'], type:'error',
  q:'Although the cost was high, but the plan went ahead.',
  tokens:['Although','the','cost','was','high,','but','the','plan','went','ahead'], answer:5, fix:'—',
  ru:'хотя стоимость была высокой, план запустили',
  why:'although уже вводит уступку — второй союз лишний. Это калька с русского «хотя…, но…».' },
{ g:'Связки', r5:true, lex:true, tag:['reg2'], type:'choose',
  q:'Формальный вариант слова «kids»:',
  options:['children','guys','folks'], answer:0, ru:'',
  why:'в эссе — children. Остальное разговорное.' },
{ g:'Связки', r5:true, lex:true, tag:['reg2'], type:'choose',
  q:'Формальный вариант выражения «get worse»:',
  options:['deteriorate','go downhill','get bad'], answer:0, ru:'',
  why:'deteriorate — одно слово вместо фразового глагола, и регистр сразу выше.' },
{ g:'Связки', r5:true, lex:true, tag:['reg2'], type:'gap',
  q:'Prices fell; ___, demand stayed the same. (however/but)', answer:['however'],
  ru:'цены упали; спрос, однако, не изменился',
  why:'после точки с запятой → however с запятой. Это связка, а не союз.' },
{ g:'Связки', r5:true, lex:true, tag:['reg2'], type:'pick',
  q:'Отметь ВСЁ, что не годится для формального письма.',
  options:['don’t','do not','it’s','it is'],
  answers:[0,2], ru:'',
  why:'сокращения — устная норма. В эссе пишут полностью.' },
{ g:'Связки', r5:true, lex:true, tag:['reg2'], type:'choose',
  q:'___ salaries rose, spending fell.',
  options:['Whereas','However','Despite'], answer:0,
  ru:'в то время как зарплаты росли, траты падали',
  why:'whereas связывает две половины одного предложения. However так не работает.' },
{ g:'Связки', r5:true, lex:true, tag:['reg2'], type:'choose',
  q:'Как убрать повтор: «The report is long. The report is useful»?',
  options:['The report is long. It is useful.','The report is long and the report is useful.','Report is long, report is useful.'],
  answer:0, ru:'',
  why:'отсылка местоимением вместо повтора — то, за что в критериях стоит «связность».' },
];
