/* ============================================================
   ПАЧКА 3 — уровень B1 → B2.

   Зачем отдельным файлом: пачки 1–2 (tests.js) — это A1/A2, они
   пройдены на 8/8 и больше ничего не измеряют. Здесь конструкции
   и лексика, с которых начинается реальный B1/B2: условные, пассив,
   косвенная речь, герундий/инфинитив, модальные догадки, придаточные,
   Perfect Continuous, кванторы, плюс лексический блок — коллокации,
   фразовые, словообразование, AWL, путаницы, регистр, язык графиков.

   Поля те же, что в tests.js. Метки: r3:true — пачка 3,
   lex:true — лексический вопрос, tag:[...] — из какого теста брать.

   Перенесено 2026-08-28 из прототипа eng.crs-projects.com
   (scripts/tests-b1.js), где эта пачка появилась 2026-08-17.
   ============================================================ */

export const B1_QUESTIONS = [

/* ============ УСЛОВНЫЕ (tag:cond) ============ */
{ g:'Условия', r3:true, tag:['cond'], type:'choose',
  q:'If it ___ tomorrow, we will stay at home.', options:['rains','will rain','rained'], answer:0,
  ru:'если завтра будет дождь, останемся дома',
  why:'1-й тип: после if — настоящее время, will живёт только в главной части.' },
{ g:'Условия', r3:true, tag:['cond'], type:'choose',
  q:'If I ___ you, I would apply this year.', options:['am','was','were'], answer:2,
  ru:'на твоём месте я бы подавал в этом году',
  why:'2-й тип, устойчивая формула: If I were you… (не was — это школьный маркер уровня).' },
{ g:'Условия', r3:true, tag:['cond'], type:'choose',
  q:'If I had known about the deadline, I ___ earlier.',
  options:['would apply','would have applied','applied'], answer:1,
  ru:'если бы я знал про дедлайн, подал бы раньше',
  why:'3-й тип (прошлое, уже не изменить): if + had + V3 → would have + V3.' },
{ g:'Условия', r3:true, tag:['cond'], type:'mgap',
  q:'If she ___ (study) harder, she ___ (pass) the exam.', answer:[['studied'],['would pass']],
  ru:'если бы она занималась больше, она бы сдала',
  why:'2-й тип: if + Past Simple → would + инфинитив. Прошедшая форма тут = «нереально сейчас», а не прошлое.' },
{ g:'Условия', r3:true, tag:['cond'], type:'error',
  q:'If I will have time, I will call you.',
  tokens:['If','I','will','have','time,','I','will','call','you'], answer:2, fix:'—',
  ru:'если у меня будет время, я позвоню',
  why:'после if будущее не ставят: If I have time, I will call you.' },
{ g:'Условия', r3:true, tag:['cond'], type:'gap',
  q:'I won’t go ___ you come with me. (если не / пока не)', answer:['unless'],
  ru:'я не пойду, если ты не пойдёшь со мной',
  why:'unless = if not. После unless — утвердительная форма.' },
{ g:'Условия', r3:true, tag:['cond'], type:'choose',
  q:'I wish I ___ more free time.', options:['have','had','would have'], answer:1,
  ru:'жаль, что у меня мало свободного времени',
  why:'wish про настоящее → Past Simple: I wish I had…' },
{ g:'Условия', r3:true, tag:['cond'], type:'choose',
  q:'She wishes she ___ that email yesterday.',
  options:['didn’t send','hadn’t sent','wouldn’t send'], answer:1,
  ru:'она жалеет, что отправила то письмо',
  why:'wish про прошлое → Past Perfect: hadn’t sent.' },
{ g:'Условия', r3:true, tag:['cond'], type:'mgap',
  q:'If you ___ (heat) water to 100 °C, it ___ (boil).', answer:[['heat'],['boils']],
  ru:'если нагреть воду до 100 °C, она кипит',
  why:'0-й тип (закон природы): обе части — Present Simple.' },
{ g:'Условия', r3:true, tag:['cond'], type:'order',
  ru:'если бы я знал, я бы тебе сказал',
  tokens:['If','I','had','known,','I','would','have','told','you'],
  answer:'If I had known, I would have told you',
  why:'3-й тип: had + V3 в условии, would have + V3 в результате.' },
{ g:'Условия', r3:true, tag:['cond'], type:'pick',
  q:'Отметь ВСЕ грамматически верные условные.',
  options:['If I were you, I would go.','If he will come, tell me.','If he comes, tell me.','If I had time, I would help.','If I would have money, I would buy it.'],
  answers:[0,2,3], ru:'',
  why:'После if — не will и не would. «If I would have» → If I had.' },
{ g:'Условия', r3:true, tag:['cond'], type:'error',
  q:'If I would have money, I would buy it.',
  tokens:['If','I','would','have','money,','I','would','buy','it'], answer:2, fix:'had',
  ru:'если бы у меня были деньги, я бы купил',
  why:'would живёт только в главной части: If I had money, I would buy it.' },
{ g:'Условия', r3:true, tag:['cond'], type:'choose',
  q:'He would be a great teacher if he ___ so shy.',
  options:['isn’t','weren’t','hadn’t been'], answer:1,
  ru:'он был бы отличным преподавателем, не будь он таким стеснительным',
  why:'2-й тип про настоящее → were (was в экзамене считают разговорным).' },
{ g:'Условия', r3:true, tag:['cond'], type:'choose',
  q:'___ we leave now, we’ll catch the last train.',
  options:['Unless','If','In case'], answer:1,
  ru:'если выйдем сейчас, успеем на последний поезд',
  why:'обычное условие → if. Unless = «если НЕ», сломает смысл.' },

/* ============ ПАССИВ (tag:passive) ============ */
{ g:'Пассив', r3:true, tag:['passive'], type:'choose',
  q:'The results ___ next week.',
  options:['will announce','will be announced','are announcing'], answer:1,
  ru:'результаты объявят на следующей неделе',
  why:'результаты не объявляют сами себя → пассив: will be + V3.' },
{ g:'Пассив', r3:true, tag:['passive'], type:'choose',
  q:'My application ___ yesterday.',
  options:['was submitted','submitted','has submitted'], answer:0,
  ru:'мою заявку подали вчера',
  why:'was/were + V3 — пассив в прошлом.' },
{ g:'Пассив', r3:true, tag:['passive'], type:'form',
  q:'The letters ___ (send) every Friday.', answer:['are sent'],
  ru:'письма отправляют каждую пятницу',
  why:'привычка + пассив → are + V3 (sent).' },
{ g:'Пассив', r3:true, tag:['passive'], type:'error',
  q:'The house was build in 1990.',
  tokens:['The','house','was','build','in','1990'], answer:3, fix:'built',
  ru:'дом построили в 1990-м',
  why:'в пассиве всегда третья форма: was built.' },
{ g:'Пассив', r3:true, tag:['passive'], type:'choose',
  q:'Who was this song ___ by?', options:['wrote','written','writing'], answer:1,
  ru:'кем написана эта песня?',
  why:'be + V3 → written; исполнитель вводится через by.' },
{ g:'Пассив', r3:true, tag:['passive'], type:'choose',
  q:'The bridge ___ at the moment.',
  options:['is repairing','is being repaired','repairs'], answer:1,
  ru:'мост сейчас ремонтируют',
  why:'пассив + «прямо сейчас» → is being + V3.' },
{ g:'Пассив', r3:true, tag:['passive'], type:'choose',
  q:'The documents must ___ before Friday.',
  options:['submit','be submitted','been submitted'], answer:1,
  ru:'документы нужно подать до пятницы',
  why:'после модального — be + V3.' },
{ g:'Пассив', r3:true, tag:['passive'], type:'gap',
  q:'English ___ spoken in more than 50 countries. (is/are)', answer:['is'],
  ru:'на английском говорят более чем в 50 странах',
  why:'English — единственное число → is spoken.' },
{ g:'Пассив', r3:true, tag:['passive'], type:'order',
  ru:'мне сказали подождать',
  tokens:['I','was','told','to','wait'], answer:'I was told to wait',
  why:'типовой пассив с людьми: I was told / I was asked / I was given.' },
{ g:'Пассив', r3:true, tag:['passive'], type:'error',
  q:'This film was directed from Christopher Nolan.',
  tokens:['This','film','was','directed','from','Christopher','Nolan'], answer:4, fix:'by',
  ru:'этот фильм снял Кристофер Нолан',
  why:'исполнитель действия в пассиве — только by, не from.' },
{ g:'Пассив', r3:true, tag:['passive'], type:'mgap',
  q:'The report ___ (write) by Anna and ___ (check) by me.',
  answer:[['was written'],['was checked','checked']],
  ru:'отчёт написала Анна, а проверил я',
  why:'два пассива подряд: во второй части was можно не повторять.' },
{ g:'Пассив', r3:true, tag:['passive'], type:'choose',
  q:'A new metro line ___ in our district.',
  options:['is building','is being built','builds'], answer:1,
  ru:'в нашем районе строят новую ветку метро',
  why:'линия не строит сама себя → is being built.' },

/* ============ КОСВЕННАЯ РЕЧЬ (tag:reported) ============ */
{ g:'Речь', r3:true, tag:['reported'], type:'choose',
  q:'He said he ___ tired.', options:['is','was','has been'], answer:1,
  ru:'он сказал, что устал',
  why:'сдвиг времён: said → внутри прошлое (is → was).' },
{ g:'Речь', r3:true, tag:['reported'], type:'choose',
  q:'She told ___ that she would call.', options:['to me','me','for me'], answer:1,
  ru:'она сказала мне, что позвонит',
  why:'tell + кому (без to): told me. А вот say + to me.' },
{ g:'Речь', r3:true, tag:['reported'], type:'error',
  q:'He said me that he was busy.',
  tokens:['He','said','me','that','he','was','busy'], answer:1, fix:'told',
  ru:'он сказал мне, что занят',
  why:'said me — нельзя. Либо told me, либо said to me.' },
{ g:'Речь', r3:true, tag:['reported'], type:'gap',
  q:'«I am working.» → She said she ___ working.', answer:['was'],
  ru:'она сказала, что работает',
  why:'am → was при сдвиге времён.' },
{ g:'Речь', r3:true, tag:['reported'], type:'choose',
  q:'He asked me where I ___.', options:['live','lived','did live'], answer:1,
  ru:'он спросил, где я живу',
  why:'в косвенном вопросе — прямой порядок слов и сдвиг: where I lived.' },
{ g:'Речь', r3:true, tag:['reported'], type:'choose',
  q:'She asked ___ I had finished.', options:['that','if','what'], answer:1,
  ru:'она спросила, закончил ли я',
  why:'вопрос без вопросительного слова → if / whether.' },
{ g:'Речь', r3:true, tag:['reported'], type:'choose',
  q:'Which is right?',
  options:['She asked what time it was.','She asked what time was it.','She asked what time is it?'], answer:0,
  ru:'она спросила, который час',
  why:'косвенный вопрос = порядок утверждения: what time it was.' },
{ g:'Речь', r3:true, tag:['reported'], type:'order',
  ru:'он сказал, что позвонит позже',
  tokens:['He','said','he','would','call','later'], answer:'He said he would call later',
  why:'will → would при сдвиге.' },
{ g:'Речь', r3:true, tag:['reported'], type:'mgap',
  q:'«I saw her yesterday.» → He said he ___ (see) her ___ (yesterday → ?).',
  answer:[['had seen'],['the day before','the previous day']],
  ru:'он сказал, что видел её накануне',
  why:'Past Simple → Past Perfect; yesterday → the day before / the previous day.' },
{ g:'Речь', r3:true, tag:['reported'], type:'choose',
  q:'«Don’t be late.» → He told me ___ late.',
  options:['not to be','to not be','don’t be'], answer:0,
  ru:'он сказал мне не опаздывать',
  why:'приказ/просьба → (not) to + инфинитив: told me not to be late.' },
{ g:'Речь', r3:true, tag:['reported','ger'], type:'gap',
  q:'He suggested ___ (go) to the cinema.', answer:['going'],
  ru:'он предложил сходить в кино',
  why:'suggest + -ing (или suggest that we go). Это и твоя старая ошибка из первого теста.', mine:true },
{ g:'Речь', r3:true, tag:['reported'], type:'choose',
  q:'«I will help you,» he said. → He promised ___.',
  options:['to help me','helping me','that help me'], answer:0,
  ru:'он пообещал помочь мне',
  why:'promise / offer / agree / refuse → to + инфинитив.' },

/* ============ ГЕРУНДИЙ / ИНФИНИТИВ (tag:ger) ============ */
{ g:'Инфинитив', r3:true, tag:['ger'], type:'choose',
  q:'I enjoy ___ new languages.', options:['to learn','learning','learn'], answer:1,
  ru:'мне нравится учить языки',
  why:'enjoy / avoid / finish / mind / practise → только -ing.' },
{ g:'Инфинитив', r3:true, tag:['ger'], type:'choose',
  q:'She decided ___ abroad.', options:['studying','to study','study'], answer:1,
  ru:'она решила учиться за границей',
  why:'decide / want / plan / hope / promise → to + инфинитив.' },
{ g:'Инфинитив', r3:true, tag:['ger'], type:'choose',
  q:'I’m looking forward to ___ you.', options:['see','seeing','saw'], answer:1,
  ru:'жду встречи с тобой',
  why:'здесь to — предлог, а после предлога всегда -ing: looking forward to seeing.' },
{ g:'Инфинитив', r3:true, tag:['ger'], type:'error',
  q:'I suggest to take a break.',
  tokens:['I','suggest','to','take','a','break'], answer:2, fix:'taking',
  ru:'предлагаю сделать перерыв',
  why:'suggest + -ing: I suggest taking a break.', mine:true },
{ g:'Инфинитив', r3:true, tag:['ger'], type:'mgap',
  q:'He stopped ___ (smoke) last year. On the way he stopped ___ (buy) a coffee.',
  answer:[['smoking'],['to buy']],
  ru:'он бросил курить · он остановился, чтобы купить кофе',
  why:'stop + -ing = бросить занятие; stop + to = остановиться ради чего-то. Разный смысл!' },
{ g:'Инфинитив', r3:true, tag:['ger'], type:'choose',
  q:'Remember ___ the door when you leave.', options:['locking','to lock'], answer:1,
  ru:'не забудь запереть дверь',
  why:'remember to do = не забыть сделать; remember doing = помнить, что делал.' },
{ g:'Инфинитив', r3:true, tag:['ger'], type:'choose',
  q:'He avoided ___ the question.', options:['to answer','answering'], answer:1,
  ru:'он ушёл от ответа',
  why:'avoid + -ing.' },
{ g:'Инфинитив', r3:true, tag:['ger'], type:'gap',
  q:'I’m interested in ___ (work) with data.', answer:['working'],
  ru:'мне интересно работать с данными',
  why:'после предлога (in / at / of / about) — только -ing.' },
{ g:'Инфинитив', r3:true, tag:['ger'], type:'pick',
  q:'Отметь ВСЕ глаголы, после которых идёт -ing.',
  options:['enjoy','decide','avoid','promise','finish'], answers:[0,2,4], ru:'',
  why:'decide / promise → to + инфинитив. enjoy / avoid / finish → -ing.' },
{ g:'Инфинитив', r3:true, tag:['ger'], type:'choose',
  q:'She made me ___ it again.', options:['to do','do','doing'], answer:1,
  ru:'она заставила меня переделать',
  why:'make / let + человек + голый инфинитив (без to).' },
{ g:'Инфинитив', r3:true, tag:['ger'], type:'choose',
  q:'It’s worth ___ this book.', options:['to read','reading'], answer:1,
  ru:'эту книгу стоит прочитать',
  why:'worth + -ing — устойчиво.' },
{ g:'Инфинитив', r3:true, tag:['ger'], type:'error',
  q:'I want going home.', tokens:['I','want','going','home'], answer:2, fix:'to go',
  ru:'я хочу домой',
  why:'want → to + инфинитив. Твой старый капкан с лишним -ing, но уровнем выше.', mine:true },
{ g:'Инфинитив', r3:true, tag:['ger','habit'], type:'order',
  ru:'я привык вставать рано',
  tokens:['I','am','used','to','getting','up','early'], answer:'I am used to getting up early',
  why:'be used to + -ing = «привык». Не путать с used to + инфинитив = «раньше делал».' },
{ g:'Инфинитив', r3:true, tag:['ger','habit'], type:'choose',
  q:'He used ___ in Moscow, but now he lives in Milan.',
  options:['to live','to living','living'], answer:0,
  ru:'раньше он жил в Москве',
  why:'used to + инфинитив = регулярно делал раньше и больше не делает.' },

/* ============ МОДАЛЬНЫЕ: ДОГАДКИ И УПРЁКИ (tag:modal) ============ */
{ g:'Модальные', r3:true, tag:['modal'], type:'choose',
  q:'The lights are on — they ___ at home.',
  options:['must be','can be','must have been'], answer:0,
  ru:'свет горит — они наверняка дома',
  why:'уверенная догадка про настоящее → must be.' },
{ g:'Модальные', r3:true, tag:['modal'], type:'choose',
  q:'It ___ be Karina — she’s at work right now.',
  options:['mustn’t','can’t','shouldn’t'], answer:1,
  ru:'это не может быть Карина',
  why:'уверенность в невозможности → can’t be. mustn’t = запрет, другое.' },
{ g:'Модальные', r3:true, tag:['modal'], type:'choose',
  q:'I ___ have studied harder — I failed the test.',
  options:['should','must','could'], answer:0,
  ru:'надо было заниматься усерднее',
  why:'упрёк себе за прошлое → should have + V3.' },
{ g:'Модальные', r3:true, tag:['modal'], type:'choose',
  q:'He ___ have forgotten — he never forgets anything.',
  options:['can’t','mustn’t','shouldn’t'], answer:0,
  ru:'не может быть, чтобы он забыл',
  why:'уверенность, что в прошлом этого не было → can’t have + V3.' },
{ g:'Модальные', r3:true, tag:['modal'], type:'gap',
  q:'You ___ have told me! (упрёк: надо было сказать)', answer:['should'],
  ru:'мог бы и сказать мне!',
  why:'should have + V3 — «надо было, но не сделал».' },
{ g:'Модальные', r3:true, tag:['modal'], type:'choose',
  q:'Maybe she left already — she ___ have gone home.',
  options:['must','might','can’t'], answer:1,
  ru:'возможно, она ушла домой',
  why:'неуверенная догадка → might / may have + V3.' },
{ g:'Модальные', r3:true, tag:['modal'], type:'error',
  q:'You must to submit the form today.',
  tokens:['You','must','to','submit','the','form','today'], answer:2, fix:'—',
  ru:'форму нужно подать сегодня',
  why:'после модального — без to: must submit.' },
{ g:'Модальные', r3:true, tag:['modal'], type:'choose',
  q:'We ___ wear a uniform at school — it was the rule.',
  options:['had to','must','should'], answer:0,
  ru:'в школе мы должны были носить форму',
  why:'у must нет прошедшего — в прошлом только had to.' },
{ g:'Модальные', r3:true, tag:['modal'], type:'choose',
  q:'You ___ pay — the entrance is free.',
  options:['mustn’t','don’t have to','shouldn’t'], answer:1,
  ru:'платить не нужно — вход бесплатный',
  why:'don’t have to = не обязан. mustn’t = нельзя, запрещено. Классическая ловушка.' },
{ g:'Модальные', r3:true, tag:['modal'], type:'pick',
  q:'Отметь ВСЕ фразы со значением «запрещено».',
  options:['You mustn’t park here.','You don’t have to park here.','Parking is not allowed.','You needn’t park here.'],
  answers:[0,2], ru:'',
  why:'don’t have to / needn’t = «не обязательно», а не запрет.' },
{ g:'Модальные', r3:true, tag:['modal'], type:'choose',
  q:'The window is broken — someone ___ it.',
  options:['must break','must have broken','should have broken'], answer:1,
  ru:'кто-то, видимо, разбил окно',
  why:'догадка про прошлое → must have + V3.' },
{ g:'Модальные', r3:true, tag:['modal'], type:'gap',
  q:'I ___ swim when I was five. (умел)', answer:['could'],
  ru:'я умел плавать в пять лет',
  why:'умение в прошлом → could.' },

/* ============ ПРИДАТОЧНЫЕ (tag:rel) ============ */
{ g:'Придаточные', r3:true, tag:['rel'], type:'choose',
  q:'The man ___ helped me was a teacher.', options:['which','who','whom'], answer:1,
  ru:'человек, который мне помог, был учителем',
  why:'про людей → who (или that). which — про вещи.' },
{ g:'Придаточные', r3:true, tag:['rel'], type:'choose',
  q:'This is the book ___ changed my mind.', options:['who','that','what'], answer:1,
  ru:'вот книга, которая меня переубедила',
  why:'про вещи → that / which. «what» в этой роли — типичная ошибка русскоговорящих.' },
{ g:'Придаточные', r3:true, tag:['rel'], type:'choose',
  q:'Milan, ___ is in the north, has two airports.',
  options:['that','which','what'], answer:1,
  ru:'Милан, который на севере, имеет два аэропорта',
  why:'после запятой (доп. информация) — только which, никогда that.' },
{ g:'Придаточные', r3:true, tag:['rel'], type:'error',
  q:'She is the girl what I told you about.',
  tokens:['She','is','the','girl','what','I','told','you','about'], answer:4, fix:'who',
  ru:'это та девушка, о которой я тебе говорил',
  why:'«what» не бывает относительным местоимением: who / that.' },
{ g:'Придаточные', r3:true, tag:['rel'], type:'gap',
  q:'That’s the student ___ laptop was stolen. (чей)', answer:['whose'],
  ru:'вот студент, у которого украли ноутбук',
  why:'принадлежность → whose.' },
{ g:'Придаточные', r3:true, tag:['rel'], type:'choose',
  q:'The hotel ___ we stayed was cheap.', options:['which','where','who'], answer:1,
  ru:'отель, где мы жили, был дешёвым',
  why:'место → where (или which … in).' },
{ g:'Придаточные', r3:true, tag:['rel'], type:'pick',
  q:'Отметь ВСЕ верные предложения.',
  options:['The film that I saw was great.','The film what I saw was great.','My brother, who lives in Rome, is a chef.','My brother, that lives in Rome, is a chef.'],
  answers:[0,2], ru:'',
  why:'what — не относительное местоимение; после запятой that не ставят.' },
{ g:'Придаточные', r3:true, tag:['rel'], type:'choose',
  q:'2026 is the year ___ we started planning the move.',
  options:['when','which','where'], answer:0,
  ru:'2026 — год, когда мы начали планировать переезд',
  why:'время → when.' },
{ g:'Придаточные', r3:true, tag:['rel'], type:'order',
  ru:'человек, который живёт по соседству, — врач',
  tokens:['The','man','who','lives','next','door','is','a','doctor'],
  answer:'The man who lives next door is a doctor',
  why:'придаточное стоит сразу после своего существительного.' },
{ g:'Придаточные', r3:true, tag:['rel'], type:'choose',
  q:'He passed the exam, ___ surprised everybody.',
  options:['that','which','what'], answer:1,
  ru:'он сдал экзамен, что всех удивило',
  why:'which может комментировать всё предложение целиком.' },

/* ============ PAST · НАРРАТИВ (tag:narr) — твоя просевшая зона ============ */
{ g:'Времена+', r3:true, tag:['narr'], type:'mgap',
  q:'When we ___ (arrive), the film ___ (already / start).',
  answer:[['arrived'],['had already started']],
  ru:'когда мы пришли, фильм уже начался',
  why:'два действия в прошлом: то, что раньше → Past Perfect (had started).', mine:true },
{ g:'Времена+', r3:true, tag:['narr'], type:'choose',
  q:'I ___ TV when the power went off.',
  options:['watched','was watching','had watched'], answer:1,
  ru:'я смотрел телевизор, когда вырубило свет',
  why:'длинный фон → Past Continuous; короткое действие прервало его → Past Simple.' },
{ g:'Времена+', r3:true, tag:['narr'], type:'choose',
  q:'By the time she called, I ___ the letter.',
  options:['wrote','had written','was writing'], answer:1,
  ru:'к тому времени, как она позвонила, я уже написал письмо',
  why:'«by the time» + завершённость до момента → Past Perfect.' },
{ g:'Времена+', r3:true, tag:['narr'], type:'choose',
  q:'We ___ in Saint Petersburg for five years before we moved.',
  options:['lived','had lived','were living'], answer:1,
  ru:'мы прожили в Петербурге пять лет до переезда',
  why:'период, закончившийся ДО другого прошлого события → had lived.' },
{ g:'Времена+', r3:true, tag:['narr','habit'], type:'gap',
  q:'I ___ to play football at school. (раньше регулярно)', answer:['used'],
  ru:'в школе я играл в футбол',
  why:'used to + инфинитив — привычка в прошлом, которой больше нет.' },
{ g:'Времена+', r3:true, tag:['narr'], type:'error',
  q:'I didn’t knew about the deadline.',
  tokens:['I','didn’t','knew','about','the','deadline'], answer:2, fix:'know',
  ru:'я не знал про дедлайн',
  why:'после did/didn’t — начальная форма: didn’t know.' },
{ g:'Времена+', r3:true, tag:['narr','habit'], type:'error',
  q:'She was used to walk to school every day.',
  tokens:['She','was','used','to','walk','to','school','every','day'], answer:1, fix:'—',
  ru:'она раньше ходила в школу пешком каждый день',
  why:'привычка в прошлом → used to walk (без was). Was used to = «была привычна» + -ing.' },
{ g:'Времена+', r3:true, tag:['narr'], type:'choose',
  q:'While I ___ dinner, someone ___ at the door.',
  options:['cooked / knocked','was cooking / knocked','was cooking / was knocking'], answer:1,
  ru:'пока я готовил ужин, кто-то постучал',
  why:'фон — Continuous, точечное событие — Simple.' },
{ g:'Времена+', r3:true, tag:['narr'], type:'order',
  ru:'к тому времени, как он приехал, поезд уже ушёл',
  tokens:['By','the','time','he','arrived,','the','train','had','left'],
  answer:'By the time he arrived, the train had left',
  why:'самое раннее действие уходит в had + V3.' },
{ g:'Времена+', r3:true, tag:['narr','perf2'], type:'choose',
  q:'They ___ for two hours when the rescue team found them.',
  options:['walked','had been walking','were walking'], answer:1,
  ru:'они шли уже два часа, когда их нашли',
  why:'длительность ДО момента в прошлом → Past Perfect Continuous (had been + -ing).' },
{ g:'Времена+', r3:true, tag:['narr'], type:'mgap',
  q:'He ___ (not / sleep) well last night because he ___ (drink) coffee late.',
  answer:[['didn’t sleep','did not sleep'],['had drunk','drank']],
  ru:'он плохо спал, потому что выпил кофе поздно',
  why:'основная линия — Past Simple; причина, случившаяся раньше → Past Perfect.' },
{ g:'Времена+', r3:true, tag:['narr'], type:'choose',
  q:'I ___ him at the airport yesterday.',
  options:['have met','met','had met'], answer:1,
  ru:'я встретил его вчера в аэропорту',
  why:'точное время в прошлом (yesterday) → Past Simple, Perfect запрещён.', mine:true },
{ g:'Времена+', r3:true, tag:['narr'], type:'gap',
  q:'Last year we ___ (go → V2) to Italy twice.', answer:['went'],
  ru:'в прошлом году мы дважды ездили в Италию',
  why:'last year → Past Simple: went.' },
{ g:'Времена+', r3:true, tag:['narr'], type:'pick',
  q:'Отметь ВСЕ предложения, где форма прошедшего верная.',
  options:['I have seen him last week.','I saw him last week.','She had already left when I came.','She has already left when I came.'],
  answers:[1,2], ru:'',
  why:'с last week — Past Simple; «уже ушла до моего прихода» → had left.', mine:true },

/* ============ PERFECT vs PERFECT CONTINUOUS (tag:perf2) ============ */
{ g:'Времена+', r3:true, tag:['perf2'], type:'choose',
  q:'I ___ English for three years.',
  options:['study','have been studying','am studying'], answer:1,
  ru:'я учу английский уже три года',
  why:'началось в прошлом и тянется до сейчас → have been + -ing.' },
{ g:'Времена+', r3:true, tag:['perf2'], type:'choose',
  q:'She’s exhausted — she ___ all day.',
  options:['worked','has been working','works'], answer:1,
  ru:'она вымотана — работала весь день',
  why:'важен процесс и его след сейчас → Present Perfect Continuous.' },
{ g:'Времена+', r3:true, tag:['perf2'], type:'choose',
  q:'I ___ three chapters today.',
  options:['have been reading','have read','am reading'], answer:1,
  ru:'я прочитал сегодня три главы',
  why:'есть результат в цифрах (сколько сделано) → Present Perfect, не Continuous.' },
{ g:'Времена+', r3:true, tag:['perf2'], type:'mgap',
  q:'How long ___ you ___ (wait)?', answer:[['have'],['been waiting']],
  ru:'как долго ты ждёшь?',
  why:'how long + процесс до сейчас → have you been waiting.' },
{ g:'Времена+', r3:true, tag:['perf2'], type:'gap',
  q:'«Он съездил в Рим и уже вернулся» → He has ___ to Rome. (been / gone)', answer:['been'],
  ru:'он был в Риме',
  why:'has been to = съездил и вернулся; has gone to = уехал и всё ещё там.', mine:true },
{ g:'Времена+', r3:true, tag:['perf2'], type:'error',
  q:'I am living here since 2020.',
  tokens:['I','am','living','here','since','2020'], answer:1, fix:'have been living',
  ru:'я живу здесь с 2020 года',
  why:'since → Present Perfect (Continuous): I have been living / I have lived here since 2020.' },
{ g:'Времена+', r3:true, tag:['perf2'], type:'choose',
  q:'We ___ each other since school.',
  options:['know','have known','have been knowing'], answer:1,
  ru:'мы знакомы со школы',
  why:'know — глагол состояния: Continuous не бывает даже в перфекте.', mine:true },
{ g:'Времена+', r3:true, tag:['perf2'], type:'gap',
  q:'for / since: I have known her ___ 2019.', answer:['since'],
  ru:'я знаю её с 2019 года',
  why:'since + точка отсчёта (2019, Monday, morning).' },
{ g:'Времена+', r3:true, tag:['perf2'], type:'gap',
  q:'for / since: We have lived here ___ five years.', answer:['for'],
  ru:'мы живём здесь пять лет',
  why:'for + отрезок времени (five years, two hours).' },
{ g:'Времена+', r3:true, tag:['perf2'], type:'choose',
  q:'The ground is wet — it ___.',
  options:['has rained','has been raining','rained'], answer:1,
  ru:'земля мокрая — шёл дождь',
  why:'виден след недавнего процесса → has been raining.' },
{ g:'Времена+', r3:true, tag:['perf2'], type:'choose',
  q:'I’ve been painting the room — I ___ two walls so far.',
  options:['have finished','have been finishing'], answer:0,
  ru:'я красил комнату — две стены готовы',
  why:'процесс → Continuous, но конкретный результат (две стены) → простой Perfect.' },
{ g:'Времена+', r3:true, tag:['perf2'], type:'pick',
  q:'Отметь ВСЕ глаголы, которые НЕ ставят в Perfect Continuous.',
  options:['know','wait','work','believe','study'], answers:[0,3], ru:'',
  why:'know / believe — состояния, у них нет процесса.' },

/* ============ АРТИКЛИ И КВАНТОРЫ (tag:quant) ============ */
{ g:'Кванторы', r3:true, tag:['quant'], type:'choose',
  q:'I have ___ money — I can’t buy it.', options:['a little','little','few'], answer:1,
  ru:'у меня мало денег',
  why:'little = мало (почти нет), негативно. a little = немного, но хватает.' },
{ g:'Кванторы', r3:true, tag:['quant'], type:'choose',
  q:'Don’t worry, we still have ___ time.', options:['a little','little','a few'], answer:0,
  ru:'немного времени ещё есть',
  why:'a little + неисчисляемое, позитивный смысл.' },
{ g:'Кванторы', r3:true, tag:['quant'], type:'choose',
  q:'How ___ information do you need?', options:['many','much','few'], answer:1,
  ru:'сколько информации тебе нужно?',
  why:'information — неисчисляемое → much.' },
{ g:'Кванторы', r3:true, tag:['quant'], type:'error',
  q:'I have many works to do today.',
  tokens:['I','have','many','works','to','do','today'], answer:3, fix:'work',
  ru:'у меня много работы сегодня',
  why:'work в значении «работа» неисчисляемо: a lot of work / much work.' },
{ g:'Кванторы', r3:true, tag:['quant'], type:'choose',
  q:'___ the students passed the exam.',
  options:['Most of','The most of','Most'], answer:0,
  ru:'большинство студентов сдали экзамен',
  why:'most of + the + существительное. Без the: most students.' },
{ g:'Кванторы', r3:true, tag:['quant'], type:'choose',
  q:'She gave me ___ advice.', options:['an','some','a'], answer:1,
  ru:'она дала мне совет',
  why:'advice неисчисляемо: some advice / a piece of advice, но не «an advice».' },
{ g:'Кванторы', r3:true, tag:['quant'], type:'choose',
  q:'I need ___ hour to finish.', options:['a','an','the'], answer:1,
  ru:'мне нужен час',
  why:'артикль по звуку: hour звучит с гласного → an.' },
{ g:'Кванторы', r3:true, tag:['quant'], type:'choose',
  q:'He plays ___ guitar and studies ___ physics.',
  options:['the / —','— / the','the / the'], answer:0,
  ru:'он играет на гитаре и изучает физику',
  why:'музыкальные инструменты — с the; названия наук — без артикля.' },
{ g:'Кванторы', r3:true, tag:['quant'], type:'pick',
  q:'Отметь ВСЕ неисчисляемые слова.',
  options:['advice','suggestion','furniture','chair','information'], answers:[0,2,4], ru:'',
  why:'у неисчисляемых нет -s и нет «a»: advice, furniture, information.' },
{ g:'Кванторы', r3:true, tag:['quant'], type:'choose',
  q:'There isn’t ___ sugar left.', options:['many','much','a few'], answer:1,
  ru:'сахара почти не осталось',
  why:'sugar неисчисляемо → much.' },
{ g:'Кванторы', r3:true, tag:['quant'], type:'error',
  q:'I bought a new furnitures yesterday.',
  tokens:['I','bought','a','new','furnitures','yesterday'], answer:4, fix:'piece of furniture',
  ru:'я купил новую мебель',
  why:'furniture без -s и без a: some furniture / a piece of furniture.' },
{ g:'Кванторы', r3:true, tag:['quant'], type:'choose',
  q:'___ of my parents are engineers.', options:['Both','Either','Neither'], answer:0,
  ru:'оба моих родителя — инженеры',
  why:'are + «оба» → Both of. Either/Neither тянут единственное число.' },

/* ============ ПРЕДЛОГИ · ПРОДВИНУТЫЕ (tag:prep2) ============ */
{ g:'Предлоги+', r3:true, tag:['prep2'], type:'gap',
  q:'She is responsible ___ the budget.', answer:['for'],
  ru:'она отвечает за бюджет',
  why:'responsible FOR — учить парой.' },
{ g:'Предлоги+', r3:true, tag:['prep2'], type:'choose',
  q:'He apologised ___ being late.', options:['of','for','about'], answer:1,
  ru:'он извинился за опоздание',
  why:'apologise FOR + -ing.' },
{ g:'Предлоги+', r3:true, tag:['prep2'], type:'choose',
  q:'I’m not familiar ___ this system.', options:['to','with','of'], answer:1,
  ru:'я не знаком с этой системой',
  why:'familiar WITH (но similar TO).' },
{ g:'Предлоги+', r3:true, tag:['prep2'], type:'mgap',
  q:'She succeeded ___ getting the grant and applied ___ a visa.',
  answer:[['in'],['for']],
  ru:'она смогла получить грант и подала на визу',
  why:'succeed IN + -ing; apply FOR (заявка на что-то).' },
{ g:'Предлоги+', r3:true, tag:['prep2'], type:'choose',
  q:'The number ___ international students has increased.',
  options:['of','in','for'], answer:0,
  ru:'число иностранных студентов выросло',
  why:'the number OF — фиксированная связка (важна для IELTS Task 1).' },
{ g:'Предлоги+', r3:true, tag:['prep2'], type:'gap',
  q:'Congratulations ___ your results! (on/with/for)', answer:['on'],
  ru:'поздравляю с результатами!',
  why:'congratulate / congratulations ON.' },
{ g:'Предлоги+', r3:true, tag:['prep2'], type:'pick',
  q:'Отметь ВСЕ верные пары «слово + предлог».',
  options:['aware of','consist in','similar to','different from','superior than'],
  answers:[0,2,3], ru:'',
  why:'consist OF, superior TO. Остальные верны.' },
{ g:'Предлоги+', r3:true, tag:['prep2'], type:'gap',
  q:'They accused him ___ cheating.', answer:['of'],
  ru:'его обвинили в списывании',
  why:'accuse OF (но blame FOR).' },
{ g:'Предлоги+', r3:true, tag:['prep2'], type:'choose',
  q:'I have been ___ Italy twice.', options:['in','to','at'], answer:1,
  ru:'я был в Италии дважды',
  why:'опыт-поездка → been TO. Твоя старая ошибка, держим в тесте.', mine:true },
{ g:'Предлоги+', r3:true, tag:['prep2'], type:'mgap',
  q:'The lecture starts ___ 9 ___ Monday morning.', answer:[['at'],['on']],
  ru:'лекция начинается в 9 в понедельник утром',
  why:'часы → at, день/дата → on. Твоя горячая зона.', mine:true },
{ g:'Предлоги+', r3:true, tag:['prep2'], type:'choose',
  q:'This is an exception ___ the rule.', options:['of','to','for'], answer:1,
  ru:'это исключение из правила',
  why:'exception TO the rule — по-русски «из», по-английски «to».' },
{ g:'Предлоги+', r3:true, tag:['prep2'], type:'error',
  q:'She insisted to pay for everyone.',
  tokens:['She','insisted','to','pay','for','everyone'], answer:2, fix:'on paying',
  ru:'она настояла на том, чтобы заплатить за всех',
  why:'insist ON + -ing.' },
{ g:'Предлоги+', r3:true, tag:['prep2'], type:'choose',
  q:'He is in charge ___ the whole project.', options:['of','for','with'], answer:0,
  ru:'он руководит всем проектом',
  why:'in charge OF — устойчивый оборот.' },
{ g:'Предлоги+', r3:true, tag:['prep2'], type:'gap',
  q:'There has been an increase ___ prices. (рост чего-то)', answer:['in'],
  ru:'цены выросли',
  why:'an increase IN + что растёт; an increase OF + на сколько.' },

/* ============ ВОПРОСЫ, СРАВНЕНИЯ, so/such (tag:struct2) ============ */
{ g:'Структура+', r3:true, tag:['struct2'], type:'choose',
  q:'Could you tell me where ___?',
  options:['is the station','the station is'], answer:1,
  ru:'подскажете, где вокзал?',
  why:'вежливый непрямой вопрос → порядок утверждения.' },
{ g:'Структура+', r3:true, tag:['struct2'], type:'choose',
  q:'It was ___ a difficult test that nobody finished.',
  options:['so','such','too'], answer:1,
  ru:'тест был настолько трудным, что никто не закончил',
  why:'such + (a) + прилагательное + существительное; so — только с прилагательным.' },
{ g:'Структура+', r3:true, tag:['struct2'], type:'choose',
  q:'The lecture was ___ boring that I left.',
  options:['such','so','very'], answer:1,
  ru:'лекция была такой скучной, что я ушёл',
  why:'so + прилагательное + that.' },
{ g:'Структура+', r3:true, tag:['struct2'], type:'choose',
  q:'This exam is ___ than the last one.',
  options:['more hard','harder','more harder'], answer:1,
  ru:'этот экзамен сложнее прошлого',
  why:'короткое прилагательное → -er, без more.' },
{ g:'Структура+', r3:true, tag:['struct2'], type:'choose',
  q:'The ___ you practise, the ___ you get.',
  options:['more / better','most / best','more / best'], answer:0,
  ru:'чем больше практики, тем лучше результат',
  why:'конструкция the + сравнительная, the + сравнительная.' },
{ g:'Структура+', r3:true, tag:['struct2'], type:'gap',
  q:'You’re coming with us, ___ you? (вопрос-хвостик)', answer:['aren’t'],
  ru:'ты ведь идёшь с нами?',
  why:'утверждение → хвостик отрицательный: aren’t you?' },
{ g:'Структура+', r3:true, tag:['struct2'], type:'error',
  q:'He is not enough old to drive.',
  tokens:['He','is','not','enough','old','to','drive'], answer:3, fix:'old enough',
  ru:'он недостаточно взрослый, чтобы водить',
  why:'enough идёт ПОСЛЕ прилагательного: old enough (но enough time — перед существительным).' },
{ g:'Структура+', r3:true, tag:['struct2'], type:'choose',
  q:'She speaks English ___ than I do.',
  options:['fluenter','more fluently','more fluent'], answer:1,
  ru:'она говорит по-английски свободнее меня',
  why:'speaks — глагол → нужно наречие: more fluently.' },
{ g:'Структура+', r3:true, tag:['struct2'], type:'order',
  ru:'ты не знаешь, во сколько начинается лекция?',
  tokens:['Do','you','know','what','time','the','lecture','starts'],
  answer:'Do you know what time the lecture starts',
  why:'внешний вопрос — с do, внутренний — прямым порядком (…the lecture starts).' },
{ g:'Структура+', r3:true, tag:['struct2'], type:'choose',
  q:'It’s ___ expensive for me.', options:['too','enough','so'], answer:0,
  ru:'для меня это слишком дорого',
  why:'too = «слишком» (негативный перебор).' },
{ g:'Структура+', r3:true, tag:['struct2'], type:'choose',
  q:'Milan is not ___ big ___ Moscow.',
  options:['so / as','as / as','more / than'], answer:1,
  ru:'Милан не такой большой, как Москва',
  why:'равенство/сравнение → (not) as … as.' },
{ g:'Структура+', r3:true, tag:['struct2'], type:'error',
  q:'I asked him where does he live.',
  tokens:['I','asked','him','where','does','he','live'], answer:4, fix:'—',
  ru:'я спросил, где он живёт',
  why:'в непрямом вопросе нет do/does: …where he lives.' },

/* ============ СВЯЗКИ И ЛОГИКА (tag:link) ============ */
{ g:'Связки', r3:true, tag:['link'], type:'choose',
  q:'___ the rain, we went out.', options:['Despite','Although','However'], answer:0,
  ru:'несмотря на дождь, мы вышли',
  why:'despite / in spite of + существительное (без of у despite!).' },
{ g:'Связки', r3:true, tag:['link'], type:'choose',
  q:'___ it was raining, we went out.', options:['Despite','Although','Because'], answer:1,
  ru:'хотя шёл дождь, мы вышли',
  why:'although + целое предложение (подлежащее + глагол).' },
{ g:'Связки', r3:true, tag:['link'], type:'choose',
  q:'The plan is risky. ___, it may work.',
  options:['However','Although','Despite'], answer:0,
  ru:'план рискованный. Тем не менее, может сработать',
  why:'however — связка между двумя предложениями, через точку/точку с запятой.' },
{ g:'Связки', r3:true, tag:['link'], type:'choose',
  q:'Costs rose; ___, profits fell.',
  options:['therefore','however','moreover'], answer:1,
  ru:'расходы выросли; однако прибыль упала',
  why:'контраст → however. therefore = следствие, moreover = добавление.' },
{ g:'Связки', r3:true, tag:['link'], type:'gap',
  q:'City life is fast, ___ village life is slow. (в то время как)', answer:['whereas','while'],
  ru:'городская жизнь быстрая, а деревенская медленная',
  why:'whereas / while — противопоставление двух фактов, любимая связка IELTS Task 1.' },
{ g:'Связки', r3:true, tag:['link'], type:'choose',
  q:'___ the high price, sales grew.',
  options:['In spite of','In spite','Despite of'], answer:0,
  ru:'несмотря на высокую цену, продажи выросли',
  why:'in spite OF, но despite без of.' },
{ g:'Связки', r3:true, tag:['link'], type:'pick',
  q:'Отметь ВСЕ связки контраста.',
  options:['however','moreover','whereas','therefore','nevertheless'],
  answers:[0,2,4], ru:'',
  why:'moreover — добавление, therefore — следствие.' },
{ g:'Связки', r3:true, tag:['link'], type:'choose',
  q:'Firstly… Secondly… ___, I would argue that…',
  options:['Finally','At the end','In the end'], answer:0,
  ru:'наконец, я бы сказал, что…',
  why:'перечисление закрывают словом finally; «at the end» — про место/время.' },
{ g:'Связки', r3:true, tag:['link'], type:'choose',
  q:'Формально: «___, the data suggest a clear trend.»',
  options:['So','Thus','And so'], answer:1,
  ru:'таким образом, данные показывают явный тренд',
  why:'thus / therefore — академический регистр; so — разговорный.' },
{ g:'Связки', r3:true, tag:['link'], type:'gap',
  q:'___ of the storm, the flight was cancelled. (из-за)', answer:['because'],
  ru:'из-за шторма рейс отменили',
  why:'because OF + существительное; because + предложение.' },

/* ============ КОЛЛОКАЦИИ (tag:coll, lex) ============ */
{ g:'Лексика', r3:true, lex:true, tag:['coll'], type:'choose',
  q:'to ___ a decision', options:['make','do','take'], answer:0,
  ru:'принять решение',
  why:'make a decision. Русское «принять» тянет к take — это калька.' },
{ g:'Лексика', r3:true, lex:true, tag:['coll'], type:'choose',
  q:'to ___ homework', options:['make','do','take'], answer:1,
  ru:'делать домашку',
  why:'do — рутина и работа (do homework / do the dishes); make — создавать результат.' },
{ g:'Лексика', r3:true, lex:true, tag:['coll'], type:'choose',
  q:'to ___ a photo', options:['make','take','do'], answer:1,
  ru:'сделать фото',
  why:'take a photo. «make a photo» — калька.' },
{ g:'Лексика', r3:true, lex:true, tag:['coll'], type:'choose',
  q:'to ___ attention to the details', options:['pay','give','make'], answer:0,
  ru:'обращать внимание на детали',
  why:'pay attention — фиксированная пара.' },
{ g:'Лексика', r3:true, lex:true, tag:['coll'], type:'mgap',
  q:'Next week I need to ___ an exam and ___ progress with my essay.',
  answer:[['take'],['make']],
  ru:'сдавать экзамен и продвинуться с эссе',
  why:'take an exam (сдавать), make progress (продвигаться).' },
{ g:'Лексика', r3:true, lex:true, tag:['coll'], type:'pick',
  q:'Отметь ВСЕ верные сочетания.',
  options:['make a mistake','do a mistake','take a break','make a break','do research'],
  answers:[0,2,4], ru:'',
  why:'make a mistake, take a break, do research.' },
{ g:'Лексика', r3:true, lex:true, tag:['coll'], type:'gap',
  q:'to ___ a promise (сдержать обещание)', answer:['keep'],
  ru:'сдержать обещание',
  why:'make a promise — дать, keep a promise — сдержать, break a promise — нарушить.' },
{ g:'Лексика', r3:true, lex:true, tag:['coll'], type:'choose',
  q:'to ___ an opportunity', options:['take','make','do'], answer:0,
  ru:'воспользоваться возможностью',
  why:'take / seize an opportunity.' },
{ g:'Лексика', r3:true, lex:true, tag:['coll'], type:'choose',
  q:'___ rain (сильный дождь)', options:['strong','heavy','big'], answer:1,
  ru:'сильный дождь',
  why:'heavy rain / heavy traffic, но strong wind / strong coffee.' },
{ g:'Лексика', r3:true, lex:true, tag:['coll'], type:'choose',
  q:'to ___ a risk', options:['take','do','make'], answer:0,
  ru:'рисковать',
  why:'take a risk.' },
{ g:'Лексика', r3:true, lex:true, tag:['coll'], type:'error',
  q:'She did a serious mistake in the report.',
  tokens:['She','did','a','serious','mistake','in','the','report'], answer:1, fix:'made',
  ru:'она допустила серьёзную ошибку в отчёте',
  why:'make a mistake — всегда make.' },
{ g:'Лексика', r3:true, lex:true, tag:['coll'], type:'gap',
  q:'to ___ money (зарабатывать)', answer:['earn','make'],
  ru:'зарабатывать деньги',
  why:'earn money / make money. «win money» — только про выигрыш.' },
{ g:'Лексика', r3:true, lex:true, tag:['coll'], type:'choose',
  q:'to ___ a course', options:['take','make','pass'], answer:0,
  ru:'проходить курс',
  why:'take a course; pass — это уже «сдать».' },
{ g:'Лексика', r3:true, lex:true, tag:['coll'], type:'pick',
  q:'Отметь ВСЕ глаголы, которые сочетаются со словом «research».',
  options:['carry out','do','make','conduct'], answers:[0,1,3], ru:'',
  why:'carry out / do / conduct research. «make research» — нет.' },

/* ============ ФРАЗОВЫЕ ГЛАГОЛЫ (tag:phrasal, lex) ============ */
{ g:'Фразовые', r3:true, lex:true, tag:['phrasal'], type:'choose',
  q:'They had to ___ the meeting until Friday.',
  options:['put off','put on','put up'], answer:0,
  ru:'перенести встречу на пятницу',
  why:'put off = отложить.' },
{ g:'Фразовые', r3:true, lex:true, tag:['phrasal'], type:'choose',
  q:'The police are ___ the case.',
  options:['looking after','looking into','looking for'], answer:1,
  ru:'полиция расследует дело',
  why:'look into = разбираться, расследовать; look after = заботиться; look for = искать.' },
{ g:'Фразовые', r3:true, lex:true, tag:['phrasal'], type:'choose',
  q:'I want to ___ a new hobby.', options:['take up','take off','take out'], answer:0,
  ru:'заняться новым хобби',
  why:'take up = начать заниматься чем-то.' },
{ g:'Фразовые', r3:true, lex:true, tag:['phrasal'], type:'choose',
  q:'We need to ___ a solution before Monday.',
  options:['come up with','come across','come over'], answer:0,
  ru:'придумать решение',
  why:'come up with = придумать; come across = наткнуться.' },
{ g:'Фразовые', r3:true, lex:true, tag:['phrasal'], type:'gap',
  q:'The plane will ___ off in ten minutes. (взлетать)', answer:['take'],
  ru:'самолёт взлетит через десять минут',
  why:'take off = взлетать (и «снимать одежду»).' },
{ g:'Фразовые', r3:true, lex:true, tag:['phrasal'], type:'choose',
  q:'She ___ smoking last year.', options:['gave up','gave in','gave away'], answer:0,
  ru:'она бросила курить',
  why:'give up = бросить; после него -ing.' },
{ g:'Фразовые', r3:true, lex:true, tag:['phrasal'], type:'choose',
  q:'I ___ an old photo while cleaning.',
  options:['came across','came into','came round'], answer:0,
  ru:'я случайно наткнулся на старое фото',
  why:'come across = наткнуться случайно.' },
{ g:'Фразовые', r3:true, lex:true, tag:['phrasal'], type:'choose',
  q:'Can you ___ the music? It’s too loud.',
  options:['turn down','turn off','turn up'], answer:0,
  ru:'сделай потише',
  why:'turn down = убавить; turn up = прибавить; turn off = выключить.' },
{ g:'Фразовые', r3:true, lex:true, tag:['phrasal'], type:'pick',
  q:'Отметь ВСЕ, что значит «продолжать».',
  options:['carry on','go on','put on','keep on'], answers:[0,1,3], ru:'',
  why:'put on = надевать / включать.' },
{ g:'Фразовые', r3:true, lex:true, tag:['phrasal','ger'], type:'error',
  q:'I am looking forward to hear from you.',
  tokens:['I','am','looking','forward','to','hear','from','you'], answer:5, fix:'hearing',
  ru:'жду вашего ответа',
  why:'look forward TO + -ing. Формула деловых писем — выучить целиком.' },
{ g:'Фразовые', r3:true, lex:true, tag:['phrasal'], type:'choose',
  q:'The experiment was ___ last year.',
  options:['carried out','carried on','carried away'], answer:0,
  ru:'эксперимент провели в прошлом году',
  why:'carry out = проводить (исследование, работу) — академическая связка.' },
{ g:'Фразовые', r3:true, lex:true, tag:['phrasal'], type:'gap',
  q:'We ___ out of milk this morning. (закончилось — форма прошедшего от run)', answer:['ran'],
  ru:'у нас закончилось молоко',
  why:'run out of = закончиться; run → ran.' },
{ g:'Фразовые', r3:true, lex:true, tag:['phrasal'], type:'choose',
  q:'He ___ his father — same eyes, same voice.',
  options:['takes after','takes over','takes on'], answer:0,
  ru:'он похож на отца',
  why:'take after = пойти в кого-то из родни.' },
{ g:'Фразовые', r3:true, lex:true, tag:['phrasal'], type:'choose',
  q:'Sales ___ by 20% last quarter.',
  options:['went up','went on','went off'], answer:0,
  ru:'продажи выросли на 20%',
  why:'go up = расти. Пригодится в описании графиков.' },

/* ============ СЛОВООБРАЗОВАНИЕ (tag:wform, lex) ============ */
{ g:'Словообразование', r3:true, lex:true, tag:['wform'], type:'gap',
  q:'analyse → существительное: ___', answer:['analysis'],
  ru:'анализ', why:'analyse (глагол) → analysis (сущ.), мн.ч. analyses.' },
{ g:'Словообразование', r3:true, lex:true, tag:['wform'], type:'gap',
  q:'succeed → существительное: ___', answer:['success'],
  ru:'успех', why:'succeed → success → successful → successfully.' },
{ g:'Словообразование', r3:true, lex:true, tag:['wform'], type:'gap',
  q:'decide → существительное: ___', answer:['decision'],
  ru:'решение', why:'-de → -sion: decide → decision.' },
{ g:'Словообразование', r3:true, lex:true, tag:['wform'], type:'gap',
  q:'able → существительное: ___', answer:['ability'],
  ru:'способность', why:'able → ability; отрицание — unable / inability.' },
{ g:'Словообразование', r3:true, lex:true, tag:['wform'], type:'choose',
  q:'This is a very ___ argument. (convince)',
  options:['convince','convincing','convinced'], answer:1,
  ru:'очень убедительный аргумент',
  why:'-ing = какой он сам (убедительный); -ed = что чувствую я.' },
{ g:'Словообразование', r3:true, lex:true, tag:['wform'], type:'choose',
  q:'I was ___ by the results. (surprise)',
  options:['surprising','surprised'], answer:1,
  ru:'я был удивлён результатами',
  why:'человек чувствует → -ed (surprised); вещь вызывает → -ing (surprising).' },
{ g:'Словообразование', r3:true, lex:true, tag:['wform'], type:'gap',
  q:'economy → прилагательное про экономику страны: ___', answer:['economic'],
  ru:'экономический', why:'economic growth / economic crisis.' },
{ g:'Словообразование', r3:true, lex:true, tag:['wform'], type:'choose',
  q:'An ___ car uses less fuel.', options:['economic','economical'], answer:1,
  ru:'экономичная машина',
  why:'economical = экономный, выгодный. economic = про экономику.' },
{ g:'Словообразование', r3:true, lex:true, tag:['wform'], type:'gap',
  q:'possible → противоположность: ___', answer:['impossible'],
  ru:'невозможно', why:'перед p/m/b приставка im-: impossible, immature.' },
{ g:'Словообразование', r3:true, lex:true, tag:['wform'], type:'gap',
  q:'strong → существительное: ___', answer:['strength'],
  ru:'сила', why:'strong → strength (как long → length).' },
{ g:'Словообразование', r3:true, lex:true, tag:['wform'], type:'choose',
  q:'The company’s ___ has grown. (produce)',
  options:['production','productive','produced'], answer:0,
  ru:'производство выросло',
  why:'после притяжательного нужно существительное → production.' },
{ g:'Словообразование', r3:true, lex:true, tag:['wform'], type:'mgap',
  q:'science → человек: ___ · прилагательное: ___',
  answer:[['scientist'],['scientific']],
  ru:'учёный · научный', why:'-ist = человек, -ific = признак.' },
{ g:'Словообразование', r3:true, lex:true, tag:['wform'], type:'gap',
  q:'able → глагол «дать возможность»: to ___', answer:['enable'],
  ru:'позволять, давать возможность', why:'приставка en- делает глагол: enable, ensure, encourage.' },
{ g:'Словообразование', r3:true, lex:true, tag:['wform'], type:'pick',
  q:'Отметь ВСЕ существительные.',
  options:['analysis','analyse','significance','significant','requirement'],
  answers:[0,2,4], ru:'',
  why:'analyse — глагол, significant — прилагательное.' },

/* ============ АКАДЕМИЧЕСКАЯ ЛЕКСИКА · AWL (tag:awl, lex) ============ */
{ g:'Академика', r3:true, lex:true, tag:['awl'], type:'choose',
  q:'a ___ increase = заметный, существенный рост',
  options:['significant','signify','signal'], answer:0,
  ru:'значительный рост', why:'significant — слово №1 в академическом английском.' },
{ g:'Академика', r3:true, lex:true, tag:['awl'], type:'choose',
  q:'These are the main ___ that affect the result.',
  options:['factors','facts','effects'], answer:0,
  ru:'основные факторы, влияющие на результат',
  why:'factor = фактор; fact = факт; effect = следствие.' },
{ g:'Академика', r3:true, lex:true, tag:['awl'], type:'gap',
  q:'Доказательства (неисчисляемое): the ___ shows that…', answer:['evidence'],
  ru:'данные показывают, что…',
  why:'evidence — без -s и без «an»: strong evidence, a piece of evidence.' },
{ g:'Академика', r3:true, lex:true, tag:['awl'], type:'choose',
  q:'as a ___ of the delay = в результате задержки',
  options:['consequence','conclusion','cause'], answer:0,
  ru:'вследствие задержки', why:'as a consequence / as a result of.' },
{ g:'Академика', r3:true, lex:true, tag:['awl'], type:'choose',
  q:'We do not have ___ data to prove it.',
  options:['sufficient','efficient','proficient'], answer:0,
  ru:'недостаточно данных', why:'sufficient = достаточный; efficient = эффективный; proficient = владеющий навыком.' },
{ g:'Академика', r3:true, lex:true, tag:['awl'], type:'choose',
  q:'the ___ stage = следующий, последующий этап',
  options:['previous','subsequent','current'], answer:1,
  ru:'последующий этап', why:'previous = предыдущий, current = текущий, subsequent = следующий за ним.' },
{ g:'Академика', r3:true, lex:true, tag:['awl'], type:'gap',
  q:'Подход, метод: a new ___ to the problem', answer:['approach'],
  ru:'новый подход к проблеме', why:'approach TO — и предлог тоже учить.' },
{ g:'Академика', r3:true, lex:true, tag:['awl'], type:'choose',
  q:'This ___ that the theory needs revision.',
  options:['indicates','indicates to','shows to'], answer:0,
  ru:'это указывает на то, что теорию надо пересмотреть',
  why:'indicate + that, без предлога.' },
{ g:'Академика', r3:true, lex:true, tag:['awl'], type:'choose',
  q:'The study ___ 200 students.',
  options:['involved','involved in','included in'], answer:0,
  ru:'в исследовании участвовали 200 студентов',
  why:'the study involved X = включало; be involved IN — уже про человека.' },
{ g:'Академика', r3:true, lex:true, tag:['awl'], type:'choose',
  q:'Академический синоним «стать больше»:',
  options:['increase','grow up','raise up'], answer:0,
  ru:'увеличиваться', why:'grow up = взрослеть; raise требует объект (raise prices).' },
{ g:'Академика', r3:true, lex:true, tag:['awl'], type:'gap',
  q:'Формальный синоним «поэтому» на «th…»: ___', answer:['thus','therefore'],
  ru:'таким образом', why:'thus / therefore / hence — регистр отчётов и эссе.' },
{ g:'Академика', r3:true, lex:true, tag:['awl'], type:'choose',
  q:'a ___ study = предварительное исследование',
  options:['preliminary','primary','prior'], answer:0,
  ru:'предварительное исследование', why:'primary = основной, prior = предшествующий (prior to).' },
{ g:'Академика', r3:true, lex:true, tag:['awl'], type:'pick',
  q:'Отметь ВСЕ слова со значением «влиять / влияние».',
  options:['impact','affect','effect','afford','influence'], answers:[0,1,2,4], ru:'',
  why:'afford = позволить себе (по деньгам) — не из этого ряда.' },
{ g:'Академика', r3:true, lex:true, tag:['awl'], type:'gap',
  q:'Ограничение исследования: a ___ of the study', answer:['limitation'],
  ru:'ограничение исследования', why:'limitation — стандартный раздел любой академической работы.' },
{ g:'Академика', r3:true, lex:true, tag:['awl'], type:'choose',
  q:'«Примерно» в академическом тексте:',
  options:['approximately','about like','around about'], answer:0,
  ru:'приблизительно', why:'approximately / roughly — нейтрально-формально.' },
{ g:'Академика', r3:true, lex:true, tag:['awl'], type:'choose',
  q:'The two groups were ___ in age but differed in income.',
  options:['similar','similarly','same'], answer:0,
  ru:'группы были похожи по возрасту',
  why:'were + прилагательное → similar; «same» требует the same.' },

/* ============ ПОХОЖИЕ СЛОВА (tag:confuse, lex) ============ */
{ g:'Путаницы', r3:true, lex:true, tag:['confuse'], type:'choose',
  q:'The weather ___ my mood.', options:['affects','effects'], answer:0,
  ru:'погода влияет на моё настроение',
  why:'affect — глагол «влиять», effect — существительное «эффект».' },
{ g:'Путаницы', r3:true, lex:true, tag:['confuse'], type:'choose',
  q:'The new law had a strong ___ on prices.',
  options:['affect','effect'], answer:1,
  ru:'закон сильно повлиял на цены', why:'после «a strong» нужно существительное → effect.' },
{ g:'Путаницы', r3:true, lex:true, tag:['confuse'], type:'choose',
  q:'Can you ___ me some money until Friday?',
  options:['borrow','lend'], answer:1,
  ru:'одолжи мне денег до пятницы',
  why:'lend = дать в долг; borrow = взять в долг.' },
{ g:'Путаницы', r3:true, lex:true, tag:['confuse'], type:'choose',
  q:'She ___ me how to code.', options:['learned','taught'], answer:1,
  ru:'она научила меня программировать',
  why:'teach = учить кого-то; learn = учиться самому.' },
{ g:'Путаницы', r3:true, lex:true, tag:['confuse'], type:'choose',
  q:'He ___ me that he was late.', options:['said','told'], answer:1,
  ru:'он сказал мне, что опаздывает', why:'told + me; said без адресата.' },
{ g:'Путаницы', r3:true, lex:true, tag:['confuse'], type:'choose',
  q:'My ___ starts at 9 — I work in IT.', options:['job','work'], answer:0,
  ru:'моя работа начинается в 9',
  why:'job — конкретная должность (исчисляемое), work — деятельность (неисчисляемое).' },
{ g:'Путаницы', r3:true, lex:true, tag:['confuse'], type:'choose',
  q:'We had a great ___ to Italy last summer.',
  options:['travel','trip','journey'], answer:1,
  ru:'отличная поездка в Италию',
  why:'trip — конкретная поездка; travel — процесс вообще (неисчисляемое).' },
{ g:'Путаницы', r3:true, lex:true, tag:['confuse'], type:'gap',
  q:'its / it’s: ___ raining again.', answer:['it’s'],
  ru:'снова дождь', why:'it’s = it is; its = его/её (принадлежность).' },
{ g:'Путаницы', r3:true, lex:true, tag:['confuse'], type:'choose',
  q:'I need your ___ before I decide.', options:['advice','advise'], answer:0,
  ru:'мне нужен твой совет', why:'advice — существительное, advise — глагол.' },
{ g:'Путаницы', r3:true, lex:true, tag:['confuse'], type:'choose',
  q:'She is ___ her sister.', options:['taller then','taller than'], answer:1,
  ru:'она выше сестры', why:'than — сравнение; then — потом.' },
{ g:'Путаницы', r3:true, lex:true, tag:['confuse'], type:'choose',
  q:'I ___ my keys yesterday.', options:['lost','loosed','loose'], answer:0,
  ru:'я потерял ключи', why:'lose (терять) → lost; loose = свободный, не туго.' },
{ g:'Путаницы', r3:true, lex:true, tag:['confuse'], type:'choose',
  q:'I am ___ in history.', options:['interesting','interested'], answer:1,
  ru:'я интересуюсь историей',
  why:'человеку интересно → interested IN; вещь интересная → interesting.' },
{ g:'Путаницы', r3:true, lex:true, tag:['confuse'], type:'error',
  q:'This information are very useful.',
  tokens:['This','information','are','very','useful'], answer:2, fix:'is',
  ru:'эта информация очень полезна',
  why:'information — неисчисляемое, единственное число → is.' },
{ g:'Путаницы', r3:true, lex:true, tag:['confuse'], type:'choose',
  q:'Be ___ — think before you act.', options:['sensible','sensitive'], answer:0,
  ru:'будь благоразумен', why:'sensible = разумный; sensitive = чувствительный.' },

/* ============ РЕГИСТР: ФОРМАЛЬНО / РАЗГОВОРНО (tag:formal, lex) ============ */
{ g:'Регистр', r3:true, lex:true, tag:['formal'], type:'choose',
  q:'Формально вместо «kids»:', options:['children','guys','folks'], answer:0,
  ru:'дети', why:'в эссе — нейтральная лексика: children.' },
{ g:'Регистр', r3:true, lex:true, tag:['formal'], type:'choose',
  q:'Формально вместо «a lot of research»:',
  options:['loads of research','a considerable amount of research'], answer:1,
  ru:'значительный объём исследований', why:'loads of / tons of — разговорное.' },
{ g:'Регистр', r3:true, lex:true, tag:['formal'], type:'choose',
  q:'Формально: «But the results were bad.» →',
  options:['However, the results were poor.','But the results were really bad.'], answer:0,
  ru:'однако результаты оказались слабыми',
  why:'предложение не начинают с But в академическом письме; bad → poor.' },
{ g:'Регистр', r3:true, lex:true, tag:['formal'], type:'pick',
  q:'Отметь ВСЁ, что НЕ подходит для академического эссе.',
  options:['don’t','do not','stuff','a significant number of','things like that'],
  answers:[0,2,4], ru:'',
  why:'сокращения и разговорные «stuff / things like that» в эссе не идут.' },
{ g:'Регистр', r3:true, lex:true, tag:['formal'], type:'choose',
  q:'Формальный синоним «find out»:',
  options:['determine','check out','figure out'], answer:0,
  ru:'установить, определить', why:'determine / establish — академический регистр.' },
{ g:'Регистр', r3:true, lex:true, tag:['formal'], type:'choose',
  q:'Формальный синоним «get» (получить):',
  options:['obtain','grab','pick up'], answer:0,
  ru:'получить', why:'obtain / acquire — формально.' },
{ g:'Регистр', r3:true, lex:true, tag:['formal'], type:'choose',
  q:'Осторожная формулировка: «This ___ that the trend will continue.»',
  options:['proves','suggests','says'], answer:1,
  ru:'это позволяет предположить, что тренд продолжится',
  why:'в академическом письме избегают категоричного proves → suggests / indicates.' },
{ g:'Регистр', r3:true, lex:true, tag:['formal'], type:'choose',
  q:'Начало эссе, которое любят экзаменаторы:',
  options:['In my opinion I think that…','It is often argued that…'], answer:1,
  ru:'часто утверждают, что…',
  why:'«In my opinion I think» — тавтология; безличная формула звучит взрослее.' },
{ g:'Регистр', r3:true, lex:true, tag:['formal'], type:'gap',
  q:'Формально «помогать»: to ___ students with their applications', answer:['assist'],
  ru:'помогать студентам', why:'assist — формальный help.' },
{ g:'Регистр', r3:true, lex:true, tag:['formal'], type:'choose',
  q:'Формально «показывать» (в отчёте):',
  options:['demonstrate','point out at','tell about'], answer:0,
  ru:'демонстрировать', why:'demonstrate / illustrate — отчётный регистр.' },

/* ============ ЯЗЫК ГРАФИКОВ · IELTS Task 1 (tag:ielts, lex) ============ */
{ g:'Графики', r3:true, lex:true, tag:['ielts'], type:'choose',
  q:'Sales ___ sharply in 2020.', options:['rose','raised','arised'], answer:0,
  ru:'продажи резко выросли',
  why:'rise → rose (сам растёт); raise требует объект: raise prices.' },
{ g:'Графики', r3:true, lex:true, tag:['ielts'], type:'choose',
  q:'There was a ___ decline in prices.', options:['slight','little','few'], answer:0,
  ru:'небольшое снижение цен', why:'slight / gradual / sharp — стандартные определения к динамике.' },
{ g:'Графики', r3:true, lex:true, tag:['ielts'], type:'gap',
  q:'Максимум: the figure ___ at 40% in May. (достигло пика)', answer:['peaked'],
  ru:'показатель достиг пика 40% в мае', why:'peak at — глагол «достичь максимума».' },
{ g:'Графики', r3:true, lex:true, tag:['ielts'], type:'choose',
  q:'Numbers ___ steady between 2010 and 2015.',
  options:['remained','stayed on','kept up'], answer:0,
  ru:'показатели оставались стабильными', why:'remain / stay steady — устойчиво.' },
{ g:'Графики', r3:true, lex:true, tag:['ielts'], type:'choose',
  q:'Cars ___ for 30% of all sales.', options:['accounted','counted','made'], answer:0,
  ru:'на автомобили пришлось 30% продаж', why:'account for = составлять долю.' },
{ g:'Графики', r3:true, lex:true, tag:['ielts'], type:'mgap',
  q:'The figure rose ___ 10% ___ 25%.', answer:[['from'],['to']],
  ru:'показатель вырос с 10% до 25%', why:'from … to …; «на сколько» — by 15%.' },
{ g:'Графики', r3:true, lex:true, tag:['ielts'], type:'choose',
  q:'The number of users ___ doubled over the period.',
  options:['nearly','near','nearby'], answer:0,
  ru:'число пользователей почти удвоилось', why:'nearly / almost — наречие степени.' },
{ g:'Графики', r3:true, lex:true, tag:['ielts'], type:'gap',
  q:'Резкое падение: a sharp ___ (существительное)', answer:['drop','decline','fall'],
  ru:'резкое падение', why:'a sharp drop / decline / fall — синонимы для повторов.' },
{ g:'Графики', r3:true, lex:true, tag:['ielts'], type:'choose',
  q:'Overall, the chart ___ that spending increased.',
  options:['shows','tells','speaks'], answer:0,
  ru:'в целом график показывает рост расходов',
  why:'the chart shows / illustrates. Overall — обязательное слово в Task 1.' },
{ g:'Графики', r3:true, lex:true, tag:['ielts'], type:'choose',
  q:'X was ___ higher than Y.', options:['significantly','significant','signify'], answer:0,
  ru:'X был значительно выше Y', why:'перед прилагательным нужно наречие → significantly.' },

/* ============ ДОБОР: чтобы короткие марафоны не повторялись ============ */
{ g:'Придаточные', r3:true, tag:['rel'], type:'choose',
  q:'The company ___ I work for is Italian.', options:['who','which','what'], answer:1,
  ru:'компания, в которой я работаю, — итальянская',
  why:'про организацию/вещь → which / that; предлог остаётся в конце.' },
{ g:'Придаточные', r3:true, tag:['rel'], type:'gap',
  q:'The reason ___ he left is simple. (почему)', answer:['why'],
  ru:'причина, по которой он ушёл, проста', why:'reason + why.' },
{ g:'Придаточные', r3:true, tag:['rel'], type:'error',
  q:'The people which live upstairs are noisy.',
  tokens:['The','people','which','live','upstairs','are','noisy'], answer:2, fix:'who',
  ru:'люди сверху шумные', why:'про людей — who / that, не which.' },
{ g:'Придаточные', r3:true, tag:['rel'], type:'choose',
  q:'Everything ___ he said was true.', options:['what','that','which'], answer:1,
  ru:'всё, что он сказал, было правдой',
  why:'после everything / all → that (или вообще ничего), но не what.' },

{ g:'Связки', r3:true, tag:['link'], type:'choose',
  q:'___ having little experience, she got the job.',
  options:['Despite','Although','Because'], answer:0,
  ru:'несмотря на малый опыт, она получила работу',
  why:'despite + -ing тоже работает: despite having…' },
{ g:'Связки', r3:true, tag:['link'], type:'gap',
  q:'Добавление в эссе: «___, the cost is lower.» (более того, на «more…»)', answer:['moreover'],
  ru:'более того, стоимость ниже', why:'moreover / furthermore — добавление аргумента.' },
{ g:'Связки', r3:true, tag:['link'], type:'choose',
  q:'The city is expensive; ___, salaries are higher there.',
  options:['on the other hand','in the other hand','from other hand'], answer:0,
  ru:'с другой стороны, зарплаты там выше', why:'on the other hand — фиксированная форма.' },
{ g:'Связки', r3:true, tag:['link'], type:'error',
  q:'Although the rain, we went out.',
  tokens:['Although','the','rain,','we','went','out'], answer:0, fix:'Despite',
  ru:'несмотря на дождь, мы вышли',
  why:'although требует подлежащее + глагол; перед существительным — despite / in spite of.' },

{ g:'Регистр', r3:true, lex:true, tag:['formal'], type:'choose',
  q:'Формально вместо «a lot of people think»:',
  options:['it is widely believed that','everybody knows that'], answer:0,
  ru:'широко распространено мнение, что…', why:'безличная формула — маркер академического стиля.' },
{ g:'Регистр', r3:true, lex:true, tag:['formal'], type:'choose',
  q:'Формальный синоним «make better»:',
  options:['improve','fix up','make nicer'], answer:0,
  ru:'улучшать', why:'improve / enhance — нейтрально-формально.' },
{ g:'Регистр', r3:true, lex:true, tag:['formal'], type:'gap',
  q:'Формально «показать разницу»: to ___ between two groups (различать)', answer:['distinguish'],
  ru:'различать', why:'distinguish between — академическая связка.' },
{ g:'Регистр', r3:true, lex:true, tag:['formal'], type:'pick',
  q:'Отметь ВСЁ, что уместно в формальном письме.',
  options:['I would like to enquire about…','Hey, quick question','Please find attached…','Cheers'],
  answers:[0,2], ru:'', why:'Hey / Cheers — только для друзей.' },

{ g:'Графики', r3:true, lex:true, tag:['ielts'], type:'choose',
  q:'The figure fell ___ 5% between 2020 and 2021.',
  options:['by','from','on'], answer:0,
  ru:'показатель упал на 5%', why:'на сколько → by; с… до… → from … to …' },
{ g:'Графики', r3:true, lex:true, tag:['ielts'], type:'choose',
  q:'There was a ___ rise in energy use.',
  options:['dramatic','dramatically','drama'], answer:0,
  ru:'резкий рост потребления энергии', why:'перед существительным — прилагательное: a dramatic rise.' },
{ g:'Графики', r3:true, lex:true, tag:['ielts'], type:'gap',
  q:'Минимум: the number ___ (достигло дна) at 5% in 2015. (bottomed / …)', answer:['bottomed out','bottomed'],
  ru:'показатель достиг минимума', why:'bottom out = достичь низшей точки; синоним — reached a low of 5%.' },
{ g:'Графики', r3:true, lex:true, tag:['ielts'], type:'choose',
  q:'The two lines followed a ___ pattern.',
  options:['similar','same','equal'], answer:0,
  ru:'две линии вели себя похоже', why:'a similar pattern; «same» требует the same.' },
];
