/* ============================================================
   ПАЧКА 4 · РЕМОНТ — вопросы под конкретные пробоины.

   Собрана 2026-08-28 не «по темам вообще», а по журналу ошибок
   (Мир/Английский/Прогресс.md, Устная-практика/Ошибки.md) и по
   единственному провалу в замерах: Past 4/7 при 8/8 везде рядом.

   Пять зон, по убыванию доказанности:
     narr2  — Past-нарратив: Simple ↔ Continuous ↔ Perfect, used to
     prep3  — предлоги: 4 повтора, горячая зона №1
     perf3  — Present Perfect ↔ Past Simple ↔ Perfect Continuous
     ing2   — лишний -ing и глаголы состояния
     quant2 — артикли, неисчисляемые, кванторы

   Метки: r4:true — пачка 4, mine:true — построено на твоей
   реальной ошибке из журнала. Вопросы новые: пачку 3 ты уже
   прорешал на прототипе, повторять её смысла нет.
   ============================================================ */

export const FIX_QUESTIONS = [

/* ============================================================
   PAST · НАРРАТИВ (tag:narr2) — главная пробоина, 4/7.
   Диагноз: три прошедших времени по отдельности знакомы, но когда
   они стоят в одном рассказе, выбор рассыпается. Поэтому почти
   каждый вопрос — не одинокая форма, а два действия рядом.
   ============================================================ */
{ g:'Past', r4:true, tag:['narr2'], type:'mgap',
  q:'When we ___ (arrive), the film ___ (already, start).',
  answer:[['arrived'],['had already started','had started']],
  ru:'когда мы пришли, фильм уже начался',
  why:'два прошлых действия: то, что раньше → Past Perfect (had started), то, что позже → Past Simple.' },
{ g:'Past', r4:true, tag:['narr2'], type:'choose',
  q:'I ___ dinner when the lights went out.',
  options:['cooked','was cooking','had cooked'], answer:1,
  ru:'я готовил ужин, когда вырубился свет',
  why:'длинный фон, который прервали → Past Continuous. Короткое действие-прерывание идёт в Simple.' },
{ g:'Past', r4:true, tag:['narr2'], type:'choose',
  q:'She ___ in Milan for two years before she ___ back.',
  options:['lived / moved','had lived / moved','was living / had moved'], answer:1,
  ru:'она прожила в Милане два года, прежде чем вернулась',
  why:'«до того как» → раньшее действие в Past Perfect: had lived … before she moved.' },
{ g:'Past', r4:true, tag:['narr2'], type:'error',
  q:'I was knowing the answer, but I said nothing.',
  tokens:['I','was','knowing','the','answer,','but','I','said','nothing'], answer:2, fix:'knew',
  ru:'я знал ответ, но ничего не сказал',
  why:'know — состояние, Continuous не берёт даже в прошлом: I knew. Твой лишний -ing в прошедшей форме.', mine:true },
{ g:'Past', r4:true, tag:['narr2'], type:'choose',
  q:'I ___ smoke, but I quit three years ago.',
  options:['used to','was using to','am used to'], answer:0,
  ru:'раньше я курил, но бросил три года назад',
  why:'привычка в прошлом, которой больше нет → used to + начальная форма.' },
{ g:'Past', r4:true, tag:['narr2'], type:'error',
  q:'I didn’t used to like coffee.',
  tokens:['I','didn’t','used','to','like','coffee'], answer:2, fix:'use',
  ru:'раньше я не любил кофе',
  why:'после didn’t — начальная форма: didn’t use to. То же правило, что didn’t go, а не didn’t went.' },
{ g:'Past', r4:true, tag:['narr2'], type:'order',
  ru:'к тому времени, как я приехал, поезд уже ушёл',
  tokens:['By','the','time','I','arrived,','the','train','had','left'],
  answer:'By the time I arrived, the train had left',
  why:'«by the time + Past Simple» почти всегда тянет Past Perfect во второй части.' },
{ g:'Past', r4:true, tag:['narr2'], type:'mgap',
  q:'While she ___ (write) the essay, her flatmate ___ (call) twice.',
  answer:[['was writing'],['called']],
  ru:'пока она писала эссе, соседка позвонила дважды',
  why:'while + фон → Past Continuous; сколько-то раз, законченно → Past Simple.' },
{ g:'Past', r4:true, tag:['narr2'], type:'choose',
  q:'Что верно про порядок событий: «When I got home, she had cooked dinner»?',
  options:['сначала я пришёл, потом она готовила','сначала она приготовила, потом я пришёл','одновременно'],
  answer:1, ru:'',
  why:'had cooked = раньше. Past Perfect всегда отматывает назад относительно второго действия.' },
{ g:'Past', r4:true, tag:['narr2'], type:'choose',
  q:'When I got home, she ___ dinner — так что мы сели есть через пять минут.',
  options:['cooked','was cooking','had been cooking'], answer:1,
  ru:'когда я пришёл, она готовила ужин',
  why:'процесс в момент моего прихода → Past Continuous. Сравни с had cooked — там уже готово.' },
{ g:'Past', r4:true, tag:['narr2'], type:'error',
  q:'Yesterday I have finished the application.',
  tokens:['Yesterday','I','have','finished','the','application'], answer:2, fix:'—', altfix:'finished',
  ru:'вчера я дозаполнил заявку',
  why:'есть «yesterday» — точка в прошлом → Past Simple: I finished. Perfect с точным временем не живёт.', mine:true },
{ g:'Past', r4:true, tag:['narr2'], type:'form',
  q:'He ___ (not, sleep) well before the interview, so he looked tired.',
  answer:['hadn’t slept','had not slept'],
  ru:'он плохо спал перед собеседованием, поэтому выглядел усталым',
  why:'причина «до того момента» → Past Perfect: hadn’t slept.' },
{ g:'Past', r4:true, tag:['narr2'], type:'choose',
  q:'We ___ for an hour when the rain finally stopped.',
  options:['walked','were walking','had been walking'], answer:2,
  ru:'мы шли уже час, когда дождь наконец кончился',
  why:'«уже сколько-то времени К моменту в прошлом» → Past Perfect Continuous (had been walking).' },
{ g:'Past', r4:true, tag:['narr2'], type:'pick',
  q:'Отметь ВСЕ предложения, где времена согласованы верно.',
  options:[
    'When he arrived, everyone had gone home.',
    'While I cooked, the phone was ringing.',
    'She was reading when I came in.',
    'I didn’t went to the meeting.'],
  answers:[0,2], ru:'',
  why:'2 — фон и прерывание перепутаны местами (While I WAS COOKING, the phone RANG). 4 — после didn’t начальная форма: go.' },
{ g:'Past', r4:true, tag:['narr2'], type:'choose',
  q:'As a child I ___ spend every summer at my grandmother’s.',
  options:['would','was','have'], answer:0,
  ru:'в детстве я проводил каждое лето у бабушки',
  why:'повторяющееся действие в прошлом → would + глагол (как used to, но только про действия, не про состояния).' },
{ g:'Past', r4:true, tag:['narr2'], type:'error',
  q:'I would live in Moscow when I was ten.',
  tokens:['I','would','live','in','Moscow','when','I','was','ten'], answer:1, fix:'lived',
  ru:'в десять лет я жил в Москве',
  why:'would не берёт состояния (жить, знать, любить) — только повторяющиеся действия. Здесь: lived / used to live.' },

/* ============================================================
   ПРЕДЛОГИ (tag:prep3) — 4 повтора в журнале, горячая зона №1.
   Пачка 2 закрыла in/on/at по времени. Здесь то, что реально
   встретится в тексте и эссе: пары «глагол + предлог» и
   «существительное + предлог», где русский подсказывает неверно.
   ============================================================ */
{ g:'Структура', r4:true, tag:['prep3'], type:'gap',
  q:'The results ___ the study were surprising. (of/from/about)', answer:['of'],
  ru:'результаты исследования оказались неожиданными',
  why:'результаты ЧЕГО → of. Русское «из» здесь сбивает.' },
{ g:'Структура', r4:true, tag:['prep3'], type:'choose',
  q:'She is responsible ___ the whole department.',
  options:['for','of','on'], answer:0,
  ru:'она отвечает за весь отдел', why:'responsible FOR — запоминать парой.' },
{ g:'Структура', r4:true, tag:['prep3'], type:'error',
  q:'This graph shows the increase of prices.',
  tokens:['This','graph','shows','the','increase','of','prices'], answer:5, fix:'in',
  ru:'график показывает рост цен',
  why:'an increase / a rise / a fall IN something. «of» скажет «рост, состоящий из цен». Ключевая пара для IELTS Task 1.' },
{ g:'Структура', r4:true, tag:['prep3'], type:'mgap',
  q:'It depends ___ the context, so it differs ___ country to country.',
  answer:[['on'],['from']],
  ru:'это зависит от контекста и различается от страны к стране',
  why:'depend ON, differ FROM. Два предлога, где русский даёт одинаковое «от».', mine:true },
{ g:'Структура', r4:true, tag:['prep3'], type:'pick',
  q:'Отметь ВСЕ верные пары «слово + предлог».',
  options:['succeed in','consist of','result to','similar with','aware of'],
  answers:[0,1,4], ru:'',
  why:'result IN (или result FROM), similar TO. Остальные три — верны.' },
{ g:'Структура', r4:true, tag:['prep3'], type:'gap',
  q:'Prices have risen ___ 20% since 2020. (by/on/at)', answer:['by'],
  ru:'цены выросли на 20% с 2020 года',
  why:'НА сколько выросло → BY. С… до… → from … to …' },
{ g:'Структура', r4:true, tag:['prep3'], type:'choose',
  q:'I’m not very good ___ maths, but I’m interested ___ statistics.',
  options:['in / at','at / in','at / on'], answer:1,
  ru:'я не силён в математике, но мне интересна статистика',
  why:'good AT, interested IN. Русское «в» покрывает оба — английский нет.', mine:true },
{ g:'Структура', r4:true, tag:['prep3'], type:'error',
  q:'She apologised about being late.',
  tokens:['She','apologised','about','being','late'], answer:2, fix:'for',
  ru:'она извинилась за опоздание', why:'apologise FOR something (но apologise TO somebody).' },
{ g:'Структура', r4:true, tag:['prep3'], type:'gap',
  q:'There is no solution ___ this problem. (to/of/for)', answer:['to'],
  ru:'у этой проблемы нет решения',
  why:'a solution TO a problem, an answer TO a question. Русское «решение проблемы» тянет на of — не поддавайся.' },
{ g:'Структура', r4:true, tag:['prep3'], type:'choose',
  q:'The city is famous ___ its architecture.',
  options:['by','for','with'], answer:1,
  ru:'город известен своей архитектурой',
  why:'famous FOR. «by» скажет «известен кем-то», это другое.' },
{ g:'Структура', r4:true, tag:['prep3'], type:'mgap',
  q:'I applied ___ a scholarship and waited ___ the answer for a month.',
  answer:[['for'],['for']],
  ru:'я подал на стипендию и месяц ждал ответа',
  why:'apply FOR something, wait FOR something. Оба предлога в русском невидимы — отсюда пропуски.' },
{ g:'Структура', r4:true, tag:['prep3'], type:'error',
  q:'We discussed about the deadline for an hour.',
  tokens:['We','discussed','about','the','deadline','for','an','hour'], answer:2, fix:'—',
  ru:'мы час обсуждали дедлайн',
  why:'discuss — без предлога: discuss something. Лишний «about» — калька с «говорить о».' },
{ g:'Структура', r4:true, tag:['prep3'], type:'pick',
  q:'Отметь ВСЕ предложения, где предлог (или его отсутствие) верны.',
  options:['I phoned to my mother.','She married a doctor.','He entered the room.','They explained me the rule.'],
  answers:[1,2], ru:'',
  why:'phone somebody, marry somebody, enter somewhere — без предлога. А explain берёт TO: explain the rule TO me.' },
{ g:'Структура', r4:true, tag:['prep3'], type:'gap',
  q:'The number of students went up ___ 400 to 650. (предлог)',
  answer:['from'], ru:'число студентов выросло с 400 до 650',
  why:'from 400 to 650. Пара from … to … — про интервал, by — про величину прироста.' },
{ g:'Структура', r4:true, tag:['prep3'], type:'choose',
  q:'She has a strong influence ___ her students.',
  options:['on','to','for'], answer:0,
  ru:'она сильно влияет на своих студентов',
  why:'influence / effect / impact ON. Все три — с ON, учить блоком.' },
{ g:'Структура', r4:true, tag:['prep3'], type:'error',
  q:'I have been in Italy three times.',
  tokens:['I','have','been','in','Italy','three','times'], answer:3, fix:'to',
  ru:'я был в Италии три раза',
  why:'опыт-поездка → been TO. «been in Italy» = «находился в Италии» (и, скорее всего, всё ещё там). Твоя ошибка, четвёртый заход.', mine:true },

/* ============================================================
   PERFECT ↔ PAST ↔ PERFECT CONTINUOUS (tag:perf3)
   Журнал: «did + been» и пропуск have. Пачка 2 давала это на
   коротких фразах; здесь — на выборе между тремя формами,
   где подсказка не в маркере, а в смысле.
   ============================================================ */
{ g:'Present', r4:true, tag:['perf3'], type:'choose',
  q:'— Where’s Anna? — She ___ to the library, she’ll be back at six.',
  options:['has been','has gone','went'], answer:1,
  ru:'она ушла в библиотеку',
  why:'has GONE = ушла и ещё там. has BEEN = была и вернулась. Это разные вещи, а не синонимы.' },
{ g:'Present', r4:true, tag:['perf3'], type:'choose',
  q:'I ___ this book three times — it’s my favourite.',
  options:['have read','have been reading','read'], answer:0,
  ru:'я перечитывал эту книгу три раза',
  why:'сколько РАЗ сделано → Present Perfect Simple. Continuous считает время, а не разы.' },
{ g:'Present', r4:true, tag:['perf3'], type:'choose',
  q:'I ___ for three hours and I’m still not finished.',
  options:['have worked','have been working','worked'], answer:1,
  ru:'я работаю уже три часа и всё ещё не закончил',
  why:'процесс тянется и не закончен → Present Perfect Continuous (have been working).' },
{ g:'Present', r4:true, tag:['perf3'], type:'mgap',
  q:'She ___ (live) here since 2019, and last year she ___ (buy) a flat.',
  answer:[['has lived','has been living'],['bought']],
  ru:'она живёт здесь с 2019-го, а в прошлом году купила квартиру',
  why:'since + до сих пор → Present Perfect; last year — точка в прошлом → Past Simple. В одном предложении оба.' },
{ g:'Present', r4:true, tag:['perf3'], type:'error',
  q:'Did you ever have been to a real IELTS test?',
  tokens:['Did','you','ever','have','been','to','a','real','IELTS','test'], answer:0, fix:'Have',
  ru:'ты когда-нибудь был на настоящем IELTS?',
  why:'опыт → Have you ever been. did и have/been в одном вопросе не живут. Ошибка из Рубежа 2 в новой обёртке.', mine:true },
{ g:'Present', r4:true, tag:['perf3'], type:'choose',
  q:'How long ___ you ___ your current job?',
  options:['did / have','have / had','are / having'], answer:1,
  ru:'как долго ты на нынешней работе?',
  why:'how long + всё ещё так → Present Perfect: have you had.' },
{ g:'Present', r4:true, tag:['perf3'], type:'gap',
  q:'I ___ (know) her for ten years. (have + V3)', answer:['have known','known'],
  ru:'я знаю её десять лет',
  why:'know — состояние, Continuous не берёт даже здесь: have known, не «have been knowing».' },
{ g:'Present', r4:true, tag:['perf3'], type:'pick',
  q:'Отметь ВСЕ предложения, где время выбрано верно.',
  options:[
    'I have seen him last Friday.',
    'I haven’t seen him since Friday.',
    'She has been to Paris twice.',
    'We have been waiting since 9 am.'],
  answers:[1,2,3], ru:'',
  why:'1 — есть «last Friday» → I saw him. Остальные три верны: since, twice, been waiting.' },
{ g:'Present', r4:true, tag:['perf3'], type:'choose',
  q:'The kitchen is a mess — someone ___ .',
  options:['cooked','has been cooking','had cooked'], answer:1,
  ru:'на кухне бардак — кто-то тут готовил',
  why:'видимый след процесса прямо сейчас → Present Perfect Continuous.' },
{ g:'Present', r4:true, tag:['perf3'], type:'form',
  q:'She ___ (not, finish) the report yet, so don’t ask.',
  answer:['hasn’t finished','has not finished'],
  ru:'она ещё не закончила отчёт',
  why:'yet → Present Perfect, отрицание: hasn’t finished.' },
{ g:'Present', r4:true, tag:['perf3'], type:'order',
  ru:'я только что отправил документы',
  tokens:['I','have','just','sent','the','documents'],
  answer:'I have just sent the documents',
  why:'just между have и V3. И именно sent (V3), а не send — твоя ошибка «i already send docs».', mine:true },
{ g:'Present', r4:true, tag:['perf3'], type:'choose',
  q:'В каком предложении Present Perfect НЕ подходит?',
  options:['I ___ never tried sushi.','She ___ already left.','We ___ moved here in 2021.'],
  answer:2, ru:'',
  why:'«in 2021» — точное время в прошлом → Past Simple: we moved. Perfect не берёт точку на календаре.' },
{ g:'Present', r4:true, tag:['perf3'], type:'mgap',
  q:'— ___ you ___ (finish)? — Not yet, I ___ (still, work) on it.',
  answer:[['have'],['finished'],['am still working','still am working']],
  ru:'— закончил? — нет ещё, всё ещё работаю',
  why:'вопрос о результате → Have you finished; процесс прямо сейчас → am working.' },
{ g:'Present', r4:true, tag:['perf3'], type:'error',
  q:'How long are you learning English?',
  tokens:['How','long','are','you','learning','English'], answer:2, fix:'have',
  ru:'как долго ты учишь английский?',
  why:'«сколько времени уже» → have you been learning. Present Continuous меряет «сейчас», а не длительность до сейчас.' },

/* ============================================================
   ЛИШНИЙ -ING И СОСТОЯНИЯ (tag:ing2) — 2 повтора в журнале.
   Пачка 2 давала список стативов. Здесь — засада посложнее:
   часть этих глаголов МОЖЕТ идти в -ing, но меняет смысл.
   ============================================================ */
{ g:'Present', r4:true, tag:['ing2'], type:'choose',
  q:'I ___ about moving to Italy — what do you think?',
  options:['think','am thinking','thinks'], answer:1,
  ru:'я подумываю о переезде в Италию',
  why:'think ABOUT = обдумывать, это действие → можно -ing. А «I think it’s a good idea» (мнение) — только Simple.' },
{ g:'Present', r4:true, tag:['ing2'], type:'choose',
  q:'This soup ___ strange — did you add something?',
  options:['is tasting','tastes','taste'], answer:1,
  ru:'этот суп странный на вкус',
  why:'taste как «иметь вкус» — состояние → Simple. «I am tasting the soup» = я его пробую, это действие.' },
{ g:'Present', r4:true, tag:['ing2'], type:'pick',
  q:'Отметь ВСЁ, что сказано верно.',
  options:[
    'I’m having a shower.',
    'I’m having a car.',
    'She’s seeing the doctor at four.',
    'I’m seeing what you mean.'],
  answers:[0,2], ru:'',
  why:'have/see как состояние (владеть, понимать) — без -ing: I have a car, I see what you mean. Как действие (принимать душ, встречаться) — можно.' },
{ g:'Present', r4:true, tag:['ing2'], type:'error',
  q:'I am needing more time for the essay.',
  tokens:['I','am','needing','more','time','for','the','essay'], answer:2, fix:'need',
  ru:'мне нужно больше времени на эссе',
  why:'need — состояние, -ing не берёт вообще: I need.', mine:true },
{ g:'Present', r4:true, tag:['ing2'], type:'choose',
  q:'Every morning I ___ the same bus, but this week I ___ .',
  options:['am taking / walk','take / am walking','take / walk'], answer:1,
  ru:'каждое утро я езжу на одном автобусе, но на этой неделе хожу пешком',
  why:'привычка → Simple (take), временное отклонение на этой неделе → Continuous (am walking). Твоя пара ошибок разом.', mine:true },
{ g:'Present', r4:true, tag:['ing2'], type:'gap',
  q:'Sorry, I ___ (not, understand) the question. (Simple!)',
  answer:['don’t understand','do not understand'],
  ru:'извини, я не понимаю вопрос',
  why:'understand — состояние: don’t understand, никогда «am not understanding».' },
{ g:'Present', r4:true, tag:['ing2'], type:'choose',
  q:'He ___ very rude today — normally he ___ so polite.',
  options:['is being / is','is / is being','being / is'], answer:0,
  ru:'сегодня он ведёт себя грубо — обычно он такой вежливый',
  why:'is being = ведёт себя так временно (поведение). Постоянное свойство → is.' },
{ g:'Present', r4:true, tag:['ing2'], type:'error',
  q:'The report is containing three sections.',
  tokens:['The','report','is','containing','three','sections'], answer:3, fix:'contains',
  ru:'отчёт состоит из трёх разделов',
  why:'contain / consist / belong / include — состояния, только Simple: contains.' },
{ g:'Present', r4:true, tag:['ing2'], type:'mgap',
  q:'She ___ (look) at the chart now and ___ (think) it shows growth.',
  answer:[['is looking'],['thinks']],
  ru:'она сейчас смотрит на график и считает, что он показывает рост',
  why:'look — действие, сейчас → is looking. think как мнение — состояние → thinks. В одном предложении оба режима.' },
{ g:'Present', r4:true, tag:['ing2'], type:'choose',
  q:'Какой глагол НЕ может идти в -ing ни в каком значении?',
  options:['have','see','belong'], answer:2,
  ru:'', why:'belong — чистое состояние. have и see меняют смысл и в -ing идут (have a shower, see a doctor).' },

/* ============================================================
   АРТИКЛИ, НЕИСЧИСЛЯЕМЫЕ, КВАНТОРЫ (tag:quant2)
   Журнал: «a time». Дальше это же правило решает половину
   ошибок в эссе — там неисчисляемых больше всего.
   ============================================================ */
{ g:'Структура', r4:true, tag:['quant2'], type:'pick',
  q:'Отметь ВСЕ слова, перед которыми нельзя ставить «a/an».',
  options:['advice','suggestion','information','research','question'],
  answers:[0,2,3], ru:'',
  why:'advice / information / research — неисчисляемые (a piece of advice). А suggestion и question считаются.' },
{ g:'Структура', r4:true, tag:['quant2'], type:'error',
  q:'He gave me a very useful advice.',
  tokens:['He','gave','me','a','very','useful','advice'], answer:3, fix:'—',
  ru:'он дал мне очень полезный совет',
  why:'advice неисчисляемо: useful advice, или a piece of advice. Тот же капкан, что «a time».', mine:true },
{ g:'Структура', r4:true, tag:['quant2'], type:'choose',
  q:'There is ___ evidence for this claim — almost none.',
  options:['little','a little','few'], answer:0,
  ru:'доказательств почти нет',
  why:'little = мало и это плохо; a little = немного, но есть. evidence неисчисляемо, поэтому не few.' },
{ g:'Структура', r4:true, tag:['quant2'], type:'choose',
  q:'___ students passed, so the teacher was pleased.',
  options:['Few','A few','Little'], answer:1,
  ru:'несколько студентов сдали, и преподаватель был доволен',
  why:'«и это хорошо» → a few. Голое few прозвучало бы «сдали единицы».' },
{ g:'Структура', r4:true, tag:['quant2'], type:'mgap',
  q:'How ___ money do you need, and how ___ hours will it take?',
  answer:[['much'],['many']],
  ru:'сколько денег нужно и сколько часов это займёт?',
  why:'money неисчисляемо → much; hours считаются → many.' },
{ g:'Структура', r4:true, tag:['quant2'], type:'choose',
  q:'___ university I applied to has already replied.',
  options:['A','The','—'], answer:1,
  ru:'университет, в который я подавал, уже ответил',
  why:'есть уточнение «который» → тот самый → the. А сама буква u здесь даёт звук [ju], поэтому было бы «a university».' },
{ g:'Структура', r4:true, tag:['quant2'], type:'error',
  q:'The life in a big city is expensive.',
  tokens:['The','life','in','a','big','city','is','expensive'], answer:0, fix:'—',
  ru:'жизнь в большом городе дорогая',
  why:'«жизнь вообще» → без артикля: Life in a big city. The ставим, когда речь о конкретной жизни.' },
{ g:'Структура', r4:true, tag:['quant2'], type:'pick',
  q:'Отметь ВСЕ верные варианты.',
  options:['a lot of information','many informations','much information','informations'],
  answers:[0,2], ru:'',
  why:'information не имеет множественного числа вообще: a lot of / much information.' },
{ g:'Структура', r4:true, tag:['quant2'], type:'choose',
  q:'I have ___ time today, so let’s meet tomorrow.',
  options:['a little','little','a few'], answer:1,
  ru:'у меня сегодня мало времени',
  why:'смысл «почти нет, поэтому не получится» → little без a.' },
{ g:'Структура', r4:true, tag:['quant2'], type:'gap',
  q:'She plays ___ piano every evening. (a/the/—)',
  answer:['the'], ru:'она играет на пианино каждый вечер',
  why:'play THE piano — музыкальные инструменты идут с the. Сравни: works at a hospital, какая-то больница.' },
{ g:'Структура', r4:true, tag:['quant2'], type:'choose',
  q:'___ number of applicants ___ risen sharply.',
  options:['The / has','A / have','The / have'], answer:0,
  ru:'число заявок резко выросло',
  why:'THE number of = число (единственное) → has. A number of = несколько (множественное) → have. Пара для Task 1.' },
{ g:'Структура', r4:true, tag:['quant2'], type:'error',
  q:'Every students must bring their ID.',
  tokens:['Every','students','must','bring','their','ID'], answer:1, fix:'student',
  ru:'каждый студент должен принести удостоверение',
  why:'every / each + единственное число: every student. «Их» в конце при этом нормально — their как нейтральное.' },
];
