/* ============================================================
   TESTS — банк вопросов и сборка тестов курса IELTS.

   Движок тестов общий с остальными курсами, типы те же семь:
     choose — выбрать вариант
     gap    — вписать слово
     form   — поставить слово в нужную форму
     error  — нажать на неверное слово в предложении
     order  — собрать предложение из слов
     mgap   — вписать несколько слов
     pick   — отметить все верные

   Поля: g — часть курса (по ней собирается рубеж), t — id темы,
         ru — подсказка, why — разбор, phrase:true — вопрос
         на шаблон или устойчивую фразу (идёт в тест «Фразы»).

   Правило то же, что и в остальных курсах: спрашиваем только то,
   что есть в темах. Вопрос про то, чего в курсе нет, — не проверка,
   а угадайка, и врёт он в первую очередь оценке готовности.

   Здесь намеренно нет вопросов «в формате экзамена» — ни одного
   текста на 900 слов с сорока вопросами. Проверяется приём:
   отличил ли ты False от Not Given на одном предложении, увидел ли
   подмену типа задания. Выносливость тренируется на пробниках,
   а приём ставится здесь.
   ============================================================ */

export const QUESTIONS = [

/* ============ ЧАСТЬ 1 · ФОРМАТ ============ */

/* --- карта экзамена --- */
{ g:'Формат', t:'exam-map', type:'choose', q:'Сколько длится Reading и сколько там вопросов?',
  options:['60 минут · 40 вопросов','60 минут · 30 вопросов','45 минут · 40 вопросов'], answer:0,
  ru:'полторы минуты на вопрос', why:'60 минут на 40 вопросов, включая запись ответов. Отдельного времени на бланк нет.' },
{ g:'Формат', t:'exam-map', type:'choose', q:'В каком порядке идут первые три модуля?',
  options:['Reading · Listening · Writing','Listening · Reading · Writing','Writing · Listening · Reading'], answer:1,
  ru:'порядок фиксирован', why:'Listening, Reading, Writing — подряд, без перерывов между ними.' },
{ g:'Формат', t:'exam-map', type:'choose', q:'Сколько раз играет запись в Listening?',
  options:['Один','Два','Два, но только в 3 и 4 части'], answer:0,
  ru:'played once only', why:'Один раз. Поэтому пропущенный вопрос бросают сразу и идут дальше.' },
{ g:'Формат', t:'exam-map', type:'choose', q:'На компьютерном формате после Listening дают 10 минут на перенос ответов?',
  options:['Да, как на бумаге','Нет — только короткая проверка','Дают 5 минут'], answer:1,
  ru:'transfer time', why:'Десять минут — особенность бумажного бланка. На компьютере ответы уже введены.' },
{ g:'Формат', t:'exam-map', type:'choose', q:'Чем Academic отличается от General Training?',
  options:['Всеми четырьмя модулями','Только Reading и Writing','Только длительностью'], answer:1,
  ru:'Listening и Speaking одинаковые', why:'Listening и Speaking в обоих модулях идентичны; различаются Reading и Writing.' },
{ g:'Формат', t:'exam-map', type:'pick', q:'Отметь ВСЁ, что верно про Speaking.',
  options:['11–14 минут','Три части','Разговор с живым экзаменатором','Ведётся запись','Сдаётся только в один день с остальными'],
  answers:[0,1,2,3],
  why:'Speaking может быть в другой день — в пределах недели до или после письменной части.' },
{ g:'Формат', t:'exam-map', type:'gap', q:'Официальное название балла по девятибалльной шкале: ___ score.',
  answer:['band'], ru:'band score', why:'Band score — не «оценка» и не процент.', phrase:true },

/* --- баллы --- */
{ g:'Формат', t:'bands', type:'choose', q:'L 6.5 · R 7.0 · W 6.0 · S 6.5. Итоговый балл?',
  options:['6.0','6.5','7.0'], answer:1,
  ru:'среднее по четырём', why:'Среднее ровно 6.5 — округлять нечего.' },
{ g:'Формат', t:'bands', type:'choose', q:'L 7.0 · R 7.0 · W 6.0 · S 6.5. Итог?',
  options:['6.5','6.75','7.0'], answer:0,
  ru:'среднее 6.625', why:'Округляем до ближайшей половины: 6.5. Четвертей в итоге не бывает.' },
{ g:'Формат', t:'bands', type:'choose', q:'Среднее вышло 6.75. Итог?',
  options:['6.5','7.0','6.75'], answer:1,
  ru:'правило .75', why:'.75 округляется вверх до целого балла.' },
{ g:'Формат', t:'bands', type:'choose', q:'Среднее вышло 6.25. Итог?',
  options:['6.0','6.5','6.25'], answer:1,
  ru:'правило .25', why:'.25 округляется вверх до половины.' },
{ g:'Формат', t:'bands', type:'choose', q:'Академический Reading: 30 верных из 40 — это примерно…',
  options:['Band 6','Band 7','Band 8'], answer:1,
  ru:'сырой балл → band', why:'30–32 верных ≈ band 7. Границы немного плавают от версии к версии.' },
{ g:'Формат', t:'bands', type:'choose', q:'Что даёт больше прибавки к общему баллу?',
  options:['Поднять сильнейший модуль с 7.5 до 8','Поднять слабейший с 5.5 до 6.5','Разницы нет'], answer:1,
  ru:'считается среднее', why:'Балл в слабом модуле двигает среднее сильнее, и часто именно его требуют отдельным минимумом.' },
{ g:'Формат', t:'bands', type:'pick', q:'Отметь ВСЕ критерии, по которым оценивают Writing.',
  options:['Task achievement / response','Coherence and cohesion','Pronunciation','Lexical resource','Grammatical range and accuracy'],
  answers:[0,1,3,4],
  why:'Pronunciation — критерий Speaking. В Writing их четыре, и весят они одинаково.' },
{ g:'Формат', t:'bands', type:'choose', q:'One Skill Retake — это…',
  options:['Пересдача всего экзамена со скидкой','Пересдача одного модуля в течение 60 дней после полного теста','Апелляция'], answer:1,
  ru:'once per full test', why:'Один модуль, один раз, в течение 60 дней, только после компьютерного формата и не везде.' },
{ g:'Формат', t:'bands', type:'choose', q:'Task 1 и Task 2 весят в балле за Writing одинаково?',
  options:['Да','Нет — Task 2 весит больше','Нет — Task 1 весит больше'], answer:1,
  ru:'при нехватке времени', why:'Task 2 весит больше. Поэтому при нехватке времени жертвуют концовкой Task 1.' },

/* --- формат Reading --- */
{ g:'Формат', t:'reading-format', type:'choose', q:'Какие задания НЕ идут по порядку текста?',
  options:['True/False/Not Given','Matching headings','Sentence completion'], answer:1,
  ru:'matching в целом', why:'Все matching-задания порядка не держат. Остальные обычно держат.' },
{ g:'Формат', t:'reading-format', type:'choose', q:'Лимит «NO MORE THAN TWO WORDS». Ты пишешь «the local council». Что будет?',
  options:['Засчитают — артикль не считается','Не засчитают: это три слова','Засчитают половину балла'], answer:1,
  ru:'артикль — слово', why:'Артикль считается за слово. Превышение лимита — автоматический ноль.' },
{ g:'Формат', t:'reading-format', type:'choose', q:'Осталось 3 минуты и 5 неотвеченных вопросов. Что делать?',
  options:['Оставить пустыми, чтобы не портить','Заполнить все — за неверный ответ не штрафуют','Заполнить только те, где уверен'], answer:1,
  ru:'no penalty for wrong answers', why:'Штрафа за ошибку нет. Пустая строка — гарантированный ноль.' },
{ g:'Формат', t:'reading-format', type:'choose', q:'Формулировка «agree with the claims of the writer» означает…',
  options:['True / False / Not Given','Yes / No / Not Given — про мнение автора','Multiple choice'], answer:1,
  ru:'claims = мнение', why:'Claims of the writer — мнение, значит Yes/No/Not Given. Information — факты, значит TFNG.' },
{ g:'Формат', t:'reading-format', type:'gap', q:'Вводная строка задания TFNG: «Do the following statements agree with the ___ given in the passage?»',
  answer:['information'], ru:'это TFNG, а не YNNG', why:'Information — факты. У Yes/No/Not Given там стоит claims of the writer.', phrase:true },

/* --- формат Writing --- */
{ g:'Формат', t:'writing-format', type:'choose', q:'Минимальный объём Task 2?',
  options:['150 слов','200 слов','250 слов'], answer:2,
  ru:'at least', why:'От 250 слов. Task 1 — от 150.' },
{ g:'Формат', t:'writing-format', type:'choose', q:'Сколько минут отводится на Task 1?',
  options:['20','30','40'], answer:0,
  ru:'20 + 40 = 60', why:'20 минут на Task 1 и 40 на Task 2 — рекомендованная раскладка часа.' },
{ g:'Формат', t:'writing-format', type:'choose', q:'В Task 1 (Academic) уместно объяснить причины изменений на графике?',
  options:['Да, это показывает кругозор','Нет — только то, что видно на картинке','Только в последнем абзаце'], answer:1,
  ru:'report, not opinion', why:'Task 1 — пересказ данных. Причины, мнения и прогнозы считаются «не по заданию».' },
{ g:'Формат', t:'writing-format', type:'choose', q:'Написал Task 2 на 210 слов. Что будет?',
  options:['Ничего, смысл важнее','Штраф по Task response за недобор объёма','Снимут балл за грамматику'], answer:1,
  ru:'below the word limit', why:'Недобор минимума — прямой штраф по Task achievement / response.' },
{ g:'Формат', t:'writing-format', type:'gap', q:'Стандартная концовка задания Task 2: «Give reasons for your answer and include any relevant ___.»',
  answer:['examples'], ru:'стоит под каждым Task 2', why:'Примеры требуются формулировкой задания — это не украшение.', phrase:true },

/* --- IELTS vs Duolingo --- */
{ g:'Формат', t:'vs-duolingo', type:'choose', q:'IELTS 6.5 — это примерно какой балл Duolingo?',
  options:['95–100','120–125','150–155'], answer:1,
  ru:'официальная таблица Duolingo', why:'IELTS 6.5 ≈ DET 120–125. Цель 6.5–7.0 — это DET 120–135.' },
{ g:'Формат', t:'vs-duolingo', type:'choose', q:'Сколько длится Duolingo English Test?',
  options:['Около часа','2 часа 45 минут','Три с половиной часа'], answer:0,
  ru:'adaptive', why:'Около часа целиком — тест адаптивный и короче IELTS в три раза.' },
{ g:'Формат', t:'vs-duolingo', type:'choose', q:'Нужен тест для британской визы. Подойдёт Duolingo?',
  options:['Да, он принимается везде','Нет — для виз обычно требуется IELTS в версии UKVI','Да, если выше 130'], answer:1,
  ru:'visa requirements', why:'Визовые требования отдельные, и DET в утверждённый список обычно не входит.' },
{ g:'Формат', t:'vs-duolingo', type:'choose', q:'Шкала Duolingo English Test — это…',
  options:['0–9 с шагом 0.5','10–160 с шагом 5','0–120'], answer:1,
  ru:'разные шкалы', why:'10–160 с шагом в 5 баллов, против 0–9 с шагом 0.5 у IELTS.' },
{ g:'Формат', t:'vs-duolingo', type:'pick', q:'Отметь ВСЁ, чего Duolingo не проверяет так, как IELTS.',
  options:['Чтение длинных текстов целиком','Сорокаминутное эссе','Разговор с живым собеседником','Понимание английской речи','Выносливость на три часа'],
  answers:[0,1,2,4],
  why:'Речь на слух DET проверяет. А вот длинные тексты, длинное эссе, живой диалог и выносливость — нет.' },
{ g:'Формат', t:'vs-duolingo', type:'choose', q:'Зачем может пригодиться DET при подготовке к IELTS?',
  options:['Он заменяет IELTS в вузах','Как дешёвый быстрый замер уровня за месяц до экзамена','Он не пригодится вообще'], answer:1,
  ru:'результат за 48 часов', why:'Дешевле и быстрее — удобно как честный замер. Но готовиться всё равно надо к IELTS.' },

/* ============ ЧАСТЬ 2 · ЧТЕНИЕ ============ */

/* --- скольжение --- */
{ g:'Чтение', t:'skimming', type:'choose', q:'В вопросе встретилось «in 1997». Какой приём?',
  options:['Skimming — искать тему','Scanning — искать глазами само число','Читать абзац целиком'], answer:1,
  ru:'числа не перефразируют', why:'Даты, имена и цифры текст не переписывает — их находят глазами за секунды.' },
{ g:'Чтение', t:'skimming', type:'choose', q:'Абзац начинается с «However, …». Где искать его тему?',
  options:['В первом предложении','Во втором — первое цепляется за предыдущий абзац','В последнем'], answer:1,
  ru:'связка-разворот', why:'Связка в начале абзаца разворачивает предыдущую мысль; собственная тема идёт дальше.' },
{ g:'Чтение', t:'skimming', type:'choose', q:'Сколько времени разумно отдать первому из трёх текстов?',
  options:['17–18 минут','25 минут — он задаёт настрой','30 минут'], answer:0,
  ru:'третий текст сложнее', why:'Первый текст самый лёгкий. Переработав на нём, не успеешь третий, а вопросы стоят одинаково.' },
{ g:'Чтение', t:'skimming', type:'pick', q:'Отметь ВСЁ, что ищут глазами, не читая текст.',
  options:['Годы и даты','Имена собственные','Проценты','Основную мысль автора','Слова в кавычках'],
  answers:[0,1,2,4],
  why:'Основную мысль глазами не найти — её собирают из первых предложений абзацев.' },
{ g:'Чтение', t:'skimming', type:'choose', q:'Первое предложение абзаца несёт его тему примерно…',
  options:['Всегда','В восьми случаях из десяти','Примерно в половине'], answer:1,
  ru:'исключение — связки', why:'Восемь из десяти. Исключение — абзацы, начинающиеся с However, Nevertheless, Yet.' },

/* --- парафраз --- */
{ g:'Чтение', t:'paraphrase', type:'choose', q:'Текст: «the scheme was funded entirely by private donations». Вопрос: «the scheme received no public money». Как связаны?',
  options:['Это парафраз через отрицание','Это разные утверждения','Not Given'], answer:0,
  ru:'entirely private = no public', why:'Переход через отрицание — самый частый вид парафраза в TFNG.' },
{ g:'Чтение', t:'paraphrase', type:'choose', q:'Слово из вопроса нашлось в тексте дословно. Что это скорее всего?',
  options:['Ответ найден','Distractor — проверь смысл предложения целиком','Опечатка в задании'], answer:1,
  ru:'дословных совпадений избегают', why:'Дословные совпадения обычно расставлены как приманка.' },
{ g:'Чтение', t:'paraphrase', type:'choose', q:'В тексте «cars, buses and lorries», в вопросе «road vehicles». Какой это тип парафраза?',
  options:['Синоним','Обобщение перечисления','Смена залога'], answer:1,
  ru:'самый коварный', why:'Обобщение не подсвечивается ни одним словом — его ищут по смыслу.' },
{ g:'Чтение', t:'paraphrase', type:'choose', q:'Текст: «the council rejected the plan». Вопрос: «the plan was rejected». Это…',
  options:['Актив → пассив','Обобщение','Другое утверждение'], answer:0,
  ru:'смена залога', why:'Смена залога — четвёртый стандартный способ переписать то же самое.' },
{ g:'Чтение', t:'paraphrase', type:'gap', q:'Текст: «the museum charges no entry fee». Утверждение: «admission is ___».',
  answer:['free'], ru:'charges no entry fee', why:'Отрицание глагола переписано прилагательным. Слова free в тексте нет вообще.' },
{ g:'Чтение', t:'paraphrase', type:'choose', q:'Правило, экономящее баллы: ответ должен быть…',
  options:['Логичным','Показан пальцем в конкретном предложении','Похожим на вариант ответа'], answer:1,
  ru:'не можешь показать — это догадка', why:'Если предложение-источник не показывается, это догадка. Догадки почти всегда Not Given.' },

/* --- TFNG --- */
{ g:'Чтение', t:'tfng', type:'choose', q:'Текст: «Most of the settlements were abandoned by 1300». Утверждение: «Every settlement was abandoned by 1300».',
  options:['True','False','Not Given'], answer:1,
  ru:'most против every', why:'Текст прямо допускает, что часть осталась, — утверждение это отрицает. Противоречие = False.' },
{ g:'Чтение', t:'tfng', type:'choose', q:'Текст: «The company opened offices in Berlin and Madrid». Утверждение: «The Berlin office was more profitable».',
  options:['True','False','Not Given'], answer:2,
  ru:'тема совпала, утверждение нет', why:'Про прибыльность не сказано ничего — ни за, ни против.' },
{ g:'Чтение', t:'tfng', type:'choose', q:'Текст: «The library opened in 1904 and was extended twice». Утверждение: «It was extended three times».',
  options:['True','False','Not Given'], answer:1,
  ru:'разные числа', why:'Разные числа про одно и то же — всегда False, а не Not Given.' },
{ g:'Чтение', t:'tfng', type:'choose', q:'Текст: «The vaccine is usually given in two doses». Утверждение: «It must always be given in two doses».',
  options:['True','False','Not Given'], answer:1,
  ru:'usually против must always', why:'Usually допускает исключения, always их запрещает. Это противоречие.' },
{ g:'Чтение', t:'tfng', type:'choose', q:'Текст: «The vaccine is usually given in two doses». Утверждение: «The second dose follows four weeks later».',
  options:['True','False','Not Given'], answer:2,
  ru:'про интервал не сказано', why:'Та же тема, но про интервал текст молчит.' },
{ g:'Чтение', t:'tfng', type:'choose', q:'Текст: «Some researchers argue the effect is overstated». Утверждение: «All researchers believe this».',
  options:['True','False','Not Given'], answer:1,
  ru:'квантор', why:'Some против all — прямое противоречие.' },
{ g:'Чтение', t:'tfng', type:'choose', q:'Раздумываешь над утверждением больше минуты. Что ставить?',
  options:['True','False','Not Given'], answer:2,
  ru:'тактическое правило', why:'Долгие раздумья означают, что ты достраиваешь смысл, которого в тексте нет. Это и есть Not Given.' },
{ g:'Чтение', t:'tfng', type:'pick', q:'Отметь ВСЕ слова, из-за которых утверждение чаще всего оказывается False.',
  options:['all','only','sometimes','never','the first'], answers:[0,1,3,4],
  why:'Кванторы-абсолюты (all, only, never, always) и превосходные степени. «Sometimes» наоборот смягчает.' },
{ g:'Чтение', t:'tfng', type:'choose', q:'В чём разница между False и Not Given?',
  options:['False — текст противоречит, Not Given — текст молчит','False — ты не согласен, Not Given — не знаешь','Разницы нет'], answer:0,
  ru:'дело не в твоём мнении', why:'Тебе не надо знать, правда ли это. Надо знать, сказал ли это автор.' },

/* --- заголовки --- */
{ g:'Чтение', t:'headings', type:'choose', q:'Заголовок дословно повторяет фразу из абзаца. Скорее всего это…',
  options:['Верный ответ','Приманка: он покрывает деталь, а не абзац','Ошибка составителей'], answer:1,
  ru:'верный заголовок обобщает', why:'Совпадение слов почти всегда указывает на деталь.' },
{ g:'Чтение', t:'headings', type:'choose', q:'Заголовок подходит сразу к двум абзацам. Что это значит?',
  options:['Можно поставить в оба','Он слишком общий или тема абзаца определена неверно','Один абзац лишний'], answer:1,
  ru:'каждый заголовок один раз', why:'Совпадение на два абзаца — сигнал, что взята слишком широкая формулировка.' },
{ g:'Чтение', t:'headings', type:'choose', q:'Правильный порядок работы с Matching headings?',
  options:['Прочитать список, потом примерять к абзацам','Прочитать абзац, сформулировать тему своими словами, потом искать заголовок','Читать всё подряд'], answer:1,
  ru:'сначала абзац', why:'Примерять можно почти всё — так и попадают в приманку. Сначала своя формулировка.' },
{ g:'Чтение', t:'headings', type:'choose', q:'Почему заголовков всегда больше, чем абзацев?',
  options:['Чтобы было из чего выбрать','Лишние — приманки, их не надо «пристраивать»','Это ошибка вёрстки'], answer:1,
  ru:'distractors', why:'Лишние заголовки остаются неиспользованными — это норма, а не сигнал ошибки.' },

/* --- пропуски --- */
{ g:'Чтение', t:'completion', type:'choose', q:'В тексте: «farmers were encouraged to plant». Пропуск: «Farmers were ___ to plant». Ответ?',
  options:['encourage','encouraged','encouraging'], answer:1,
  ru:'форму не меняют', why:'Ответ берут из текста дословно, в той же форме.' },
{ g:'Чтение', t:'completion', type:'choose', q:'Пропуск: «a sudden ___ in demand». Что ищем?',
  options:['Глагол','Существительное в единственном числе','Прилагательное'], answer:1,
  ru:'после a sudden', why:'Артикль «a» и прилагательное «sudden» вместе задают существительное в единственном числе.' },
{ g:'Чтение', t:'completion', type:'choose', q:'Пропуск: «Samples were ___ at three-hour intervals». Какая форма?',
  options:['Инфинитив','Третья форма глагола — это пассив','Герундий'], answer:1,
  ru:'were + ___', why:'Пассивная конструкция требует причастия: collected, taken, analysed.' },
{ g:'Чтение', t:'completion', type:'choose', q:'Лимит ONE WORD ONLY, а в тексте «a wooden frame». Что писать?',
  options:['a wooden frame','wooden frame','То единственное слово, которое отвечает на вопрос'], answer:2,
  ru:'лимит жёсткий', why:'Два слова при лимите в одно — ноль. Выбирают то, что отвечает на вопрос.' },
{ g:'Чтение', t:'completion', type:'choose', q:'Ответ на вопрос 30 нашёлся выше ответа на вопрос 29. Что это значит?',
  options:['Нормально, порядок не важен','Скорее всего одна из находок неверна','Надо поменять их местами'], answer:1,
  ru:'completion идёт по порядку', why:'Задания на заполнение обычно следуют порядку текста. Нарушение — сигнал перепроверить.' },
{ g:'Чтение', t:'completion', type:'pick', q:'Отметь ВСЁ, из-за чего верный по смыслу ответ не засчитают.',
  options:['Превышен лимит слов','Изменена форма слова','Ошибка в написании','Ответ написан с заглавной буквы'],
  answers:[0,1,2],
  why:'Регистр букв не влияет. А лимит, форма и орфография — влияют, и проверяются строго.' },

/* ============ ЧАСТЬ 3 · ПИСЬМО ============ */

/* --- разбор вопроса --- */
{ g:'Письмо', t:'t2-question', type:'choose', q:'«Do the advantages outweigh the disadvantages?» Какой это тип?',
  options:['Плюсы и минусы — перечислить обе стороны','Opinion: надо решить, что перевешивает','Problem–solution'], answer:1,
  ru:'слово outweigh', why:'Outweigh требует вердикта. Перечисление без вывода — ответ не на вопрос.' },
{ g:'Письмо', t:'t2-question', type:'choose', q:'«Discuss both views and give your own opinion.» Что теряют чаще всего?',
  options:['Первую точку зрения','Собственное мнение','Вступление'], answer:1,
  ru:'три обязательных блока', why:'«Give your own opinion» — отдельное требование, а не украшение вывода.' },
{ g:'Письмо', t:'t2-question', type:'choose', q:'«Why is this happening, and is it a positive development?» Сколько ответов нужно?',
  options:['Один — про причины','Два: причины и оценка','Три'], answer:1,
  ru:'two-part', why:'Два вопроса — два ответа. Ответить на один значит выполнить половину задания.' },
{ g:'Письмо', t:'t2-question', type:'choose', q:'Вопрос про «unpaid community service in schools», а эссе про пользу волонтёрства вообще. Что будет?',
  options:['Хорошо, шире взгляд','Task response просядет: тема подменена','Ничего'], answer:1,
  ru:'ключевые слова темы', why:'Подмена темы — прямое снижение Task response при любом уровне английского.' },
{ g:'Письмо', t:'t2-question', type:'pick', q:'Отметь ВСЁ, что обязано быть в эссе типа problem–solution.',
  options:['Названные проблемы','Решение к каждой проблеме','Обе точки зрения','Позиция автора по каждому решению'],
  answers:[0,1],
  why:'Обе точки зрения — это discussion. Здесь важно, чтобы решений было столько же, сколько проблем.' },
{ g:'Письмо', t:'t2-question', type:'choose', q:'«To what extent do you agree?» Можно ли согласиться частично?',
  options:['Нет, только да или нет','Да — и это часто сильнее крайности','Только если объяснить в выводе'], answer:1,
  ru:'to what extent', why:'Формулировка прямо допускает степень. Но позиция всё равно должна быть одна и названная.' },

/* --- вступление --- */
{ g:'Письмо', t:'t2-intro', type:'choose', q:'Сколько предложений во вступлении Task 2?',
  options:['Два: перефраз темы и позиция','Пять — надо ввести в тему','Одно'], answer:0,
  ru:'рабочий минимум и максимум', why:'Два. Остальное лучше потратить на тела абзацев.' },
{ g:'Письмо', t:'t2-intro', type:'choose', q:'Тема: «Working from home is becoming more common». Какой перефраз рабочий?',
  options:['Working from home is becoming more popular.','Remote employment is increasingly widespread.','Nowadays working from home is a controversial issue.'], answer:1,
  ru:'меняем два слова из трёх', why:'Первый меняет одно слово, третий не пересказывает тему и добавляет пустой оборот.' },
{ g:'Письмо', t:'t2-intro', type:'choose', q:'Позиция во вступлении и в выводе разошлись. Что пострадает?',
  options:['Lexical resource','Coherence and cohesion','Ничего, это показывает гибкость'], answer:1,
  ru:'одна позиция от начала до конца', why:'Экзаменатор дочитывает и не понимает, что ты в итоге думаешь. Это удар по связности.' },
{ g:'Письмо', t:'t2-intro', type:'order', tokens:['While','uniforms','clearly','cost','families','money,','I','would','argue','that','they','reduce','inequality'],
  answer:'While uniforms clearly cost families money, I would argue that they reduce inequality',
  ru:'каркас «уступка + позиция»', why:'While X, I would argue that Y — рабочий каркас вступления: признаёт сильную сторону оппонента и заявляет свою.', phrase:true },
{ g:'Письмо', t:'t2-intro', type:'gap', q:'Каркас вступления: «It is often ___ that…» — вместо «Some people say».',
  answer:['argued','claimed','said'], ru:'academic voice', why:'It is often argued that… — нейтральный академический ввод темы.', phrase:true },

/* --- тело абзаца --- */
{ g:'Письмо', t:'t2-body', type:'choose', q:'Тезис: «Cycling to work improves health». Что здесь объяснение, а не повтор?',
  options:['This is because cycling is good for your health.','Thirty minutes of moderate exercise a day lowers heart-disease risk, and a commute supplies it without extra time.','Many people cycle to work nowadays.'], answer:1,
  ru:'объяснение = механизм', why:'Второй вариант называет механизм. Первый — тот же тезис другими словами.' },
{ g:'Письмо', t:'t2-body', type:'choose', q:'Сколько мыслей должно быть в одном теле абзаца?',
  options:['Одна, раскрытая до конца','Две-три, чтобы показать кругозор','Сколько поместится'], answer:0,
  ru:'one idea per paragraph', why:'Одна раскрытая мысль сильнее трёх названных. Несколько мыслей в абзаце — минус по Coherence.' },
{ g:'Письмо', t:'t2-body', type:'choose', q:'Рабочий размер тела абзаца?',
  options:['1–2 предложения','4–5 предложений, 80–110 слов','10 предложений'], answer:1,
  ru:'два тела + вступление + вывод ≈ 280 слов', why:'Абзац из одного предложения и абзац на 150 слов одинаково портят Coherence.' },
{ g:'Письмо', t:'t2-body', type:'pick', q:'Отметь ВСЁ, что входит в рабочую схему тела абзаца.',
  options:['Тезис','Объяснение механизма','Конкретный пример','Возврат к вопросу задания','Новая тема в последнем предложении'],
  answers:[0,1,2,3],
  why:'Новая тема в конце абзаца ломает его единство — это и есть «две мысли в одном абзаце».' },
{ g:'Письмо', t:'t2-body', type:'choose', q:'Пример «For example, in my country many people do this» — почему слабый?',
  options:['Нельзя писать про свою страну','В нём нет конкретики: ни места, ни времени, ни что изменилось','Слишком короткий'], answer:1,
  ru:'relevant example', why:'Пример не обязан быть проверяемым фактом — он обязан быть конкретным.' },
{ g:'Письмо', t:'t2-body', type:'gap', q:'Каркас перехода к объяснению: «This ___ because…» — вводит механизм, а не повтор тезиса.',
  answer:['matters'], ru:'This matters because…', why:'Заставляет объяснить, почему это важно, а не пересказать тезис.', phrase:true },

/* --- связность --- */
{ g:'Письмо', t:'t2-cohesion', type:'choose', q:'Что поднимает Coherence and cohesion сильнее всего?',
  options:['Связка в начале каждого предложения','Повтор ключевого слова и указатели (this, such)','Как можно более редкие связки'], answer:1,
  ru:'cohesion ≠ linking words', why:'Механическая расстановка связок балл снижает. Работают повторы, указатели и порядок «известное → новое».' },
{ g:'Письмо', t:'t2-cohesion', type:'choose', q:'«Air travel is convenient. However, it is fast.» Что не так?',
  options:['Ничего','However означает противопоставление, а его тут нет','Предложения слишком короткие'], answer:1,
  ru:'связка не по смыслу', why:'Связка, поставленная не по смыслу, хуже её отсутствия: слово выучено, но не понято.' },
{ g:'Письмо', t:'t2-cohesion', type:'choose', q:'«Firstly, I will discuss the advantages. Secondly, the disadvantages. Finally, my opinion.» Что с этим делать?',
  options:['Оставить — структура видна','Выбросить: эссе на 250 слов не нуждается в оглавлении','Перенести в вывод'], answer:1,
  ru:'тридцать слов лимита', why:'Пересказ структуры съедает лимит и ничего не сообщает по теме.' },
{ g:'Письмо', t:'t2-cohesion', type:'choose', q:'Ориентир по связкам в начале предложения — сколько на абзац?',
  options:['По одной на предложение','Не больше одной на абзац','Ни одной'], answer:1,
  ru:'остальное — внутри предложений', why:'Остальные соединения делают внутри предложений (which, while, since) и через повтор ключевых слов.' },
{ g:'Письмо', t:'t2-cohesion', type:'error',
  tokens:['The','cost','of','housing','has','risen','sharply.','Furthermore,','wages','have','stagnated.'],
  answer:7, fix:'while (одним предложением: …risen sharply while wages have stagnated)',
  ru:'две половины одной мысли', why:'Это была одна мысль, разрезанная надвое и склеенная связкой. Подчинение (while) даёт и связность, и сложное предложение.' },

/* --- Task 1 язык --- */
{ g:'Письмо', t:'t1-language', type:'choose', q:'Продажи выросли с 20 до 28 млн. Что верно?',
  options:['rose by 28 million','rose to 28 million','rose by 28%'], answer:1,
  ru:'by — насколько, to — до какого значения', why:'«Rose by 28 million» означало бы рост до 48. Верны «to 28 million», «by 8 million», «by 40%».' },
{ g:'Письмо', t:'t1-language', type:'choose', q:'Как сказать «вышло на плато и держится»?',
  options:['plummeted','levelled off','soared'], answer:1,
  ru:'plateau', why:'Levelled off / plateaued / remained stable — три способа сказать одно и то же.' },
{ g:'Письмо', t:'t1-language', type:'gap', q:'Обвал: numbers ___ from 800,000 to 300,000. (одно слово, самое сильное)',
  answer:['plummeted','collapsed'], ru:'резче, чем fell', why:'Plummeted / collapsed — для драматичных падений. Fell sharply тоже верно, но слабее.' },
{ g:'Письмо', t:'t1-language', type:'choose', q:'Как переписать «Sales rose sharply» существительным?',
  options:['There was a sharp rise in sales.','Sales were sharp rising.','A sales rise was sharply.'], answer:0,
  ru:'глагол ↔ существительное', why:'Переключение между «глагол + наречие» и «прилагательное + существительное» — и есть Grammatical range в Task 1.' },
{ g:'Письмо', t:'t1-language', type:'mgap', q:'In 2020 the figure for Germany was twice ___ for France, at 40% and 20% ___.',
  answer:[['that'],['respectively']], ru:'сравнение двух значений',
  why:'«The figure for X» спасает от повторов названий, «respectively» экономит целое предложение.', phrase:true },
{ g:'Письмо', t:'t1-language', type:'choose', q:'Доля выросла с 5% до 25%. Какой ход сильнее?',
  options:['rose by 20%','rose fivefold','became more'], answer:1,
  ru:'кратность', why:'Кратность показывает, что ты увидел отношение между цифрами, а не списал обе.' },
{ g:'Письмо', t:'t1-language', type:'pick', q:'Отметь ВСЕ прилагательные, которые сочетаются с «rise» и «fall».',
  options:['sharp','steady','gradual','strong-minded','marginal'], answers:[0,1,2,4],
  why:'Strong-minded — про характер человека. Остальные — стандартный набор для описания изменений.' },

/* --- Task 1 overview --- */
{ g:'Письмо', t:'t1-overview', type:'choose', q:'Где стоит overview в Task 1?',
  options:['В конце, вместо вывода','Сразу после вступления','Где угодно'], answer:1,
  ru:'вывода в Task 1 нет', why:'Сразу после вступления. Экзаменатор должен увидеть общую картину сразу.' },
{ g:'Письмо', t:'t1-overview', type:'choose', q:'Что НЕ должно быть в overview?',
  options:['Слово overall','Точные цифры','Упоминание всех групп данных'], answer:1,
  ru:'цифры — в теле', why:'Overview — про картину целиком, словами. Цифры идут ниже.' },
{ g:'Письмо', t:'t1-overview', type:'choose', q:'Написал Task 1 с подробными данными, но без overview. Потолок?',
  options:['7 — данные же есть','5 по Task achievement','Не влияет'], answer:1,
  ru:'обязательный абзац', why:'Отсутствие overview прямо ограничивает Task achievement, независимо от языка.' },
{ g:'Письмо', t:'t1-overview', type:'choose', q:'«The graph shows coffee consumption in four countries between 2000 and 2020.» Это overview?',
  options:['Да','Нет — это вступление: его можно написать, не глядя на график','Нет — это тело абзаца'], answer:1,
  ru:'простая проверка', why:'Если предложение пишется без взгляда на картинку, это вступление, а не overview.' },
{ g:'Письмо', t:'t1-overview', type:'choose', q:'Что идёт в overview для схемы процесса?',
  options:['Самая длинная стадия','Начало, конец, число стадий, есть ли цикл','Ничего — там нет тенденций'], answer:1,
  ru:'overview подстраивается под тип', why:'У процесса общая картина — это его границы и структура, а не тенденция.' },
{ g:'Письмо', t:'t1-overview', type:'gap', q:'Первое предложение overview обычно начинают словом «___,» — чтобы экзаменатор нашёл его за секунду.',
  answer:['overall'], ru:'маркер overview', why:'Overall — самый простой сигнал «здесь общая картина».', phrase:true },
{ g:'Письмо', t:'t1-overview', type:'pick', q:'Отметь ВСЁ, что входит в структуру Task 1.',
  options:['Вступление','Overview','Тело с цифрами','Вывод с мнением'], answers:[0,1,2],
  why:'Вывода в Task 1 нет, а мнения там нет тем более.' },

/* ============ ЧАСТЬ 4 · ЛЕКСИКА И ПРАВИЛА ============ */

/* --- шаблоны --- */
{ g:'Лексика', t:'templates', type:'choose', q:'Что экзаменатор скорее всего не засчитает?',
  options:['While cities offer more jobs, I would argue that the cost of living cancels this out.','It is undeniable that this issue has both positive and negative sides.','The main reason for this is that rents have risen faster than wages.'], answer:1,
  ru:'memorised language', why:'Второй подходит к любой теме — значит, ничего не сообщает про эту.' },
{ g:'Лексика', t:'templates', type:'choose', q:'Почему каркас «While X, I would argue that Y» учить можно?',
  options:['Он короткий','Он пустой без твоего содержания','Он редкий'], answer:1,
  ru:'граница', why:'Заученным считается кусок, несущий содержание. Служебный каркас его не несёт.' },
{ g:'Лексика', t:'templates', type:'gap', q:'Вердикт в вопросе «что перевешивает»: «On balance, the benefits ___ the drawbacks.»',
  answer:['outweigh'], ru:'ключевой глагол', why:'Outweigh — точный глагол для вердикта. «Are more than» — калька.', phrase:true },
{ g:'Лексика', t:'templates', type:'gap', q:'Переход к примеру, вместо затёртого «For example»: «A clear ___ of this is…»',
  answer:['illustration','example'], ru:'illustration', why:'A clear illustration of this is… — тот же смысл, но не первый попавшийся оборот.', phrase:true },
{ g:'Лексика', t:'templates', type:'choose', q:'Каркас Task 1 для перехода от overview к телу?',
  options:['In conclusion,','Looking at the figures in more detail,','To sum up,'], answer:1,
  ru:'вывода в Task 1 нет', why:'Два других — вывод, а его в Task 1 не пишут.', phrase:true },
{ g:'Лексика', t:'templates', type:'order', tokens:['Those','who','disagree','point','out','that','the','costs','fall','on','taxpayers'],
  answer:'Those who disagree point out that the costs fall on taxpayers',
  ru:'ввод чужой позиции в discussion', why:'Каркас для второй точки зрения — без него discussion превращается в монолог.', phrase:true },

/* --- лексика тем --- */
{ g:'Лексика', t:'topic-lexis', type:'choose', q:'Лучшая замена для «there are a lot of cars»?',
  options:['there is a big quantity of automobiles','traffic congestion is severe','there exist numerous vehicular units'], answer:1,
  ru:'точность, а не редкость', why:'Точное устойчивое сочетание. Два других звучат неестественно.' },
{ g:'Лексика', t:'topic-lexis', type:'choose', q:'Почему редкое слово может снизить Lexical resource?',
  options:['Редкие слова запрещены','Нарушенная сочетаемость или регистр считаются ошибкой','Экзаменатор их не знает'], answer:1,
  ru:'accuracy', why:'Критерий оценивает точность. «Make a congestion» — ошибка, а не богатство.' },
{ g:'Лексика', t:'topic-lexis', type:'gap', q:'Одно слово вместо «too many cars in the centre»: severe ___.',
  answer:['congestion'], ru:'congestion', why:'Suffer from congestion — стандартная сочетаемость для проблем города.' },
{ g:'Лексика', t:'topic-lexis', type:'gap', q:'«Poor people find it hard to move up in society» → social ___ remains limited.',
  answer:['mobility'], ru:'social mobility', why:'Понятие вместо описания и нейтральный регистр вместо «poor people».' },
{ g:'Лексика', t:'topic-lexis', type:'pick', q:'Отметь ВСЕ глаголы, которые сочетаются со словом «problem» или «issue».',
  options:['tackle','address','curb','celebrate','exacerbate'], answers:[0,1,2,4],
  why:'Tackle/address — взяться за, curb — ограничить, exacerbate — усугубить. Celebrate — нет.' },
{ g:'Лексика', t:'topic-lexis', type:'choose', q:'Как учить тематическую лексику, чтобы она работала на письме?',
  options:['Списком слов','Парами с глаголом: reduce congestion, cut emissions','По алфавиту'], answer:1,
  ru:'сочетаемость', why:'Слово без сочетаемости на письме превращается в ошибку.' },
{ g:'Лексика', t:'topic-lexis', type:'gap', q:'Стареющее население: an ___ population.',
  answer:['ageing','aging'], ru:'частая тема Task 2', why:'An ageing population — базовое понятие в темах про здравоохранение и пенсии.' },

/* --- осторожность --- */
{ g:'Лексика', t:'hedging', type:'choose', q:'Какой вариант сильнее с точки зрения экзаменатора?',
  options:['Technology always improves education.','Technology tends to improve access to education.','Technology may possibly perhaps improve education somewhat.'], answer:1,
  ru:'одно смягчение', why:'Первый опровергается контрпримером, третий — нагромождение. Второй точен.' },
{ g:'Лексика', t:'hedging', type:'choose', q:'Чем заменить «causes», если причинность не доказана?',
  options:['is associated with','definitely makes','always leads to'], answer:0,
  ru:'связь вместо причины', why:'«Is associated with» заявляет связь, не утверждая причину.' },
{ g:'Лексика', t:'hedging', type:'gap', q:'Самое короткое рабочее смягчение: graduates ___ to earn more. (два слова)',
  answer:['tend','tend to'], ru:'tend to', why:'Tend to — незаметно и работает почти везде.', phrase:true },
{ g:'Лексика', t:'hedging', type:'choose', q:'«Access to clean water is possibly somewhat important.» Что не так?',
  options:['Ничего','Смягчено очевидное — здесь нужен booster','Слишком коротко'], answer:1,
  ru:'clearly essential', why:'Смягчать очевидное — тоже ошибка: текст начинает звучать неуверенно везде.' },
{ g:'Лексика', t:'hedging', type:'pick', q:'Отметь ВСЁ, что смягчает утверждение.',
  options:['tend to','in most cases','undoubtedly','appear to','arguably'], answers:[0,1,3,4],
  why:'Undoubtedly — наоборот, booster: усиливает.' },
{ g:'Лексика', t:'hedging', type:'choose', q:'Сколько смягчений на одно утверждение — ориентир?',
  options:['Одно','Три-четыре','Чем больше, тем академичнее'], answer:0,
  ru:'it may possibly perhaps be…', why:'Три подряд читаются как неуверенность в собственном английском.' },

/* --- регистр --- */
{ g:'Лексика', t:'academic-tone', type:'choose', q:'Что уместно в Task 2?',
  options:['Isn’t it obvious that this is wrong?','It is widely held that this approach is flawed.','You know this is a bad idea.'], answer:1,
  ru:'полуформальный академический', why:'Первый — разделительный вопрос, третий — обращение к читателю. Оба устные.' },
{ g:'Лексика', t:'academic-tone', type:'choose', q:'Чем заменить «nowadays» в начале эссе?',
  options:['In today’s modern world','In recent decades / over the past twenty years','Ничем'], answer:1,
  ru:'конкретный период', why:'«In today’s modern world» — тавтология и типичный заученный оборот.' },
{ g:'Лексика', t:'academic-tone', type:'gap', q:'Академическая замена для «a lot of»: a ___ number of students. (одно слово)',
  answer:['considerable','significant','substantial','large'], ru:'a considerable number of', why:'A considerable / significant number of — нейтральный академический вариант.', phrase:true },
{ g:'Лексика', t:'academic-tone', type:'pick', q:'Отметь ВСЁ, за что снимают почти автоматически.',
  options:['Сокращения (don’t, it’s)','Обращение к читателю (you should)','Восклицательные знаки','Пассивный залог'],
  answers:[0,1,2],
  why:'Пассив в академическом письме уместен и часто желателен. Остальные три — устные приёмы.' },
{ g:'Лексика', t:'academic-tone', type:'error',
  tokens:['You','should','always','recycle','your','rubbish','to','help','the','planet'],
  answer:0, fix:'Households (Households should be encouraged to recycle waste)',
  ru:'обращение к читателю', why:'Подлежащим делают того, о ком речь: households, governments, employers.' },
{ g:'Лексика', t:'academic-tone', type:'choose', q:'«In my opinion, I think that this is a bad thing.» Что чинить?',
  options:['Двойное «по-моему» и пустое «bad thing»','Ничего','Слишком формально'], answer:0,
  ru:'in my view, this is harmful', why:'In my opinion + I think — избыточность. «Bad thing» ничего не сообщает.' },

/* --- ошибки --- */
{ g:'Лексика', t:'common-errors', type:'choose', q:'Какое предложение без ошибки?',
  options:['The amount of people who lives here is growing.','The number of people who live here is growing.','The number of people who lives here are growing.'], answer:1,
  ru:'number vs amount', why:'Number — для исчисляемого, «who live» согласуется с people, «is growing» — с number.' },
{ g:'Лексика', t:'common-errors', type:'form', q:'Since 2010 the population (grow) ___ by 15%.',
  answer:['has grown'], ru:'since требует перфекта', why:'Since всегда идёт с перфектом.' },
{ g:'Лексика', t:'common-errors', type:'choose', q:'Что верно?',
  options:['It depends from the situation.','It depends of the situation.','It depends on the situation.'], answer:2,
  ru:'предлог из русского', why:'Depend on. Предлог здесь калькируется из «зависит от».' },
{ g:'Лексика', t:'common-errors', type:'gap', q:'Верный предлог: a solution ___ the problem.',
  answer:['to'], ru:'решение проблемы', why:'Solution to, а не of — русское «решение проблемы» тянет неверный предлог.' },
{ g:'Лексика', t:'common-errors', type:'error',
  tokens:['Many','researches','show','that','sleep','strongly','affects','memory'],
  answer:1, fix:'research (Much research shows…)',
  ru:'неисчисляемое', why:'Research неисчисляемое: ни -s, ни many. И сказуемое тогда shows.' },
{ g:'Лексика', t:'common-errors', type:'error',
  tokens:['The','number','of','students','who','studies','abroad','has','doubled'],
  answer:5, fix:'study',
  ru:'согласование в придаточном', why:'Придаточное относится к students (множественное), а не к number.' },
{ g:'Лексика', t:'common-errors', type:'pick', q:'Отметь ВСЕ неисчисляемые существительные.',
  options:['information','research','advice','solution','equipment'], answers:[0,1,2,4],
  why:'Solution исчисляемое: a solution, two solutions. Остальные четыре — нет.' },
{ g:'Лексика', t:'common-errors', type:'choose', q:'«Every students must attend.» Как починить?',
  options:['Every student must attend.','Every students must attends.','Everyone students must attend.'], answer:0,
  ru:'every + единственное', why:'Every и each требуют единственного числа. Нужно множественное — бери all.' },
{ g:'Лексика', t:'common-errors', type:'choose', q:'«People which live in cities…» Что не так?',
  options:['Нужно who — which для вещей','Нужно what','Всё верно'], answer:0,
  ru:'who / which / that', why:'Who — для людей, which — для вещей, that — для обоих.' },
{ g:'Лексика', t:'common-errors', type:'choose', q:'Порядок вычитки за пять минут — с чего начинать?',
  options:['С запятых','С окончаний -s у глаголов и множественного числа','С синонимов'], answer:1,
  ru:'фиксированный список', why:'Окончания → артикли → времена → предлоги. По списку ловится больше, чем «на общее впечатление».' },
{ g:'Лексика', t:'common-errors', type:'gap', q:'Верный предлог: this has a strong influence ___ young people.',
  answer:['on'], ru:'influence on', why:'Существительное influence идёт с on; глагол influence — вообще без предлога.' },
];

/* ============================================================
   Тесты. Рубеж — по части курса, фокус — по одному навыку,
   «Фразы» — только шаблоны и устойчивые обороты.

   Каждый тест собирается заново при каждом заходе: состав
   вопросов случайный внутри своего пула, поэтому пересдать
   «на память» не получается.
   ============================================================ */
export const TESTS = [
  /* Рубежа по формату здесь намеренно нет. Знание, что в Reading сорок
     вопросов за час, — справка, а не навык: оно набирается за один урок,
     не проседает и в балл не конвертируется. Как тест оно делало ровно
     одно: давало лёгкие 100%, которые тянули оценку готовности вверх и
     маскировали то, что письмо не измерено. Вопросы группы «Формат»
     никуда не делись — они остались в пуле «Микса». */
  { id:'part2', title:'Рубеж · Чтение',          sub:'все приёмы второй части',
    aspect:'reading', filter:q=>q.g==='Чтение',  pick:12 },
  { id:'part3', title:'Рубеж · Письмо',          sub:'Task 1 и Task 2 целиком',
    aspect:'writing', filter:q=>q.g==='Письмо',  pick:12 },
  { id:'part4', title:'Рубеж · Лексика и правила', sub:'шаблоны, регистр, типичные ошибки',
    aspect:'lexis',   filter:q=>q.g==='Лексика', pick:12 },

  { id:'tfng-drill', title:'Фокус · True / False / Not Given', sub:'самый дорогой навык чтения',
    aspect:'reading', filter:q=>q.t==='tfng'||q.t==='paraphrase', pick:10, mixed:true },
  { id:'task2',      title:'Фокус · Task 2',      sub:'тип задания, вступление, абзац, связки',
    aspect:'writing', filter:q=>q.t.startsWith('t2-'), pick:10, mixed:true },
  { id:'task1',      title:'Фокус · Task 1',      sub:'язык изменения и overview',
    aspect:'writing', filter:q=>q.t.startsWith('t1-'), pick:10, mixed:true },
  { id:'accuracy',   title:'Фокус · Чистота языка', sub:'регистр и ошибки, которые стоят балла',
    aspect:'grammar', filter:q=>q.t==='common-errors'||q.t==='academic-tone'||q.t==='hedging', pick:12, mixed:true },

  { id:'phrases', title:'Фразы и шаблоны',        sub:'каркасы и обороты, которые вставляешь в текст',
    aspect:'lexis',   filter:q=>q.phrase, pick:10, mixed:true },
  { id:'mix',     title:'Микс · всё пройденное',  sub:'все части вперемешку — проверка на прочность',
    aspect:'format',  filter:()=>true, pick:20, mixed:true },
];
